In [7]:
import pandas as pd
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt
import goatools
from tqdm import tqdm

# BioMaRt mapping files

In [2]:
from pybiomart import Server

server = Server(host='http://www.ensembl.org')

dataset = (server.marts['ENSEMBL_MART_ENSEMBL']
                 .datasets['hsapiens_gene_ensembl'])

In [3]:
ensembl_gene_uniprot = dataset.query(attributes=['ensembl_gene_id', 'uniprotswissprot'])
ensembl_gene_uniprot = ensembl_gene_uniprot[~ensembl_gene_uniprot["UniProtKB/Swiss-Prot ID"].isnull()]
ensembl_gene_uniprot

        Gene stable ID UniProtKB/Swiss-Prot ID
0      ENSG00000198888                  P03886
1      ENSG00000198763                  P03891
2      ENSG00000198804                  P00395
3      ENSG00000198712                  P00403
4      ENSG00000228253                  P03928
...                ...                     ...
38143  ENSG00000142961                  Q70IA8
38144  ENSG00000116754                  Q05519
38146  ENSG00000283324              A0A1B0GV90
38148  ENSG00000077585                  O60478
38149  ENSG00000086619                  Q86YB8

[21444 rows x 2 columns]

In [4]:
ensembl_transcript_uniprot = dataset.query(attributes=['ensembl_transcript_id', 'uniprotswissprot'])
ensembl_transcript_uniprot = ensembl_transcript_uniprot[~ensembl_transcript_uniprot["UniProtKB/Swiss-Prot ID"].isnull()]
ensembl_transcript_uniprot

       Transcript stable ID UniProtKB/Swiss-Prot ID
0           ENST00000361390                  P03886
1           ENST00000361453                  P03891
2           ENST00000361624                  P00395
3           ENST00000361739                  P00403
4           ENST00000361851                  P03928
...                     ...                     ...
117913      ENST00000370951                  Q05519
117915      ENST00000370950                  Q05519
117921      ENST00000636087              A0A1B0GV90
117923      ENST00000366592                  O60478
117925      ENST00000354619                  Q86YB8

[48060 rows x 2 columns]

In [5]:
ensembl_gene_rnacentral = dataset.query(attributes=['ensembl_gene_id', 'rnacentral'])
ensembl_gene_rnacentral = ensembl_gene_rnacentral[~ensembl_gene_rnacentral["RNAcentral ID"].isnull()]
ensembl_gene_rnacentral

         Gene stable ID  RNAcentral ID
0       ENSG00000210049  URS00003E8921
1       ENSG00000211459  URS000044DFF6
2       ENSG00000210077  URS00002D2D8F
3       ENSG00000210082  URS000047A7F4
4       ENSG00000209082  URS000061A10B
...                 ...            ...
130084  ENSG00000286142  URS0000EEB0E2
130086  ENSG00000077585  URS0000D27E7B
130087  ENSG00000077585  URS00008C3E98
130088  ENSG00000222650  URS000064A434
130089  ENSG00000237922  URS00008B2715

[95016 rows x 2 columns]

In [6]:
ensembl_transcript_rnacentral = dataset.query(attributes=['ensembl_transcript_id', 'rnacentral'])
ensembl_transcript_rnacentral = ensembl_transcript_rnacentral[~ensembl_transcript_rnacentral["RNAcentral ID"].isnull()]
ensembl_transcript_rnacentral

       Transcript stable ID  RNAcentral ID
0           ENST00000387314  URS00003E8921
1           ENST00000389680  URS000044DFF6
2           ENST00000387342  URS00002D2D8F
3           ENST00000387347  URS000047A7F4
4           ENST00000386347  URS000061A10B
...                     ...            ...
266595      ENST00000650982  URS0000EEB0E2
266598      ENST00000366591  URS0000D27E7B
266600      ENST00000477559  URS00008C3E98
266601      ENST00000410718  URS000064A434
266602      ENST00000423792  URS00008B2715

[95029 rows x 2 columns]

# Settings

In [7]:
goa_human = "/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human.gaf"
goa_human_isoform = "/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_isoform.gaf"
goa_human_rna = "/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_rna.gaf"
gene_transcript = "gene"
uniprot_or_rnacentral = "uniprot"
#evidence_codes = ['EXP', 'IDA', 'IPI', 'IMP', 'IGI', 'IEP', 'HTP', 'HDA', 'HMP', 'HGI', 'HEP', 'IBA', 'IBD', 'IKR', 'IRD', 'TAS', 'NAS', 'IC', 'ND']
evidence_codes = None
columns = ["DB", "DB_Object_ID", "DB_Object_Symbol", "Qualifier", "GO_ID", "DB_Reference", "Evidence_Code", "With_or_From", "Aspect", "DB_Object_Name", "DB_Object_Synonym", "DB_Object_Type", "Taxon", "Date", "Assigned_by", "Annotation_Extension", "Annotation_Properties"]
databases = ["UniProt", "Reactome", "IntAct", "Ensembl", "GO_Central"]
#datbases = None

# GAF file creation

## Original GOA files

### Load original GAF

In [9]:
#gaf = pd.read_csv(goa_human_isoform, delimiter="\t", header=None, skiprows=27)
gaf = pd.read_csv(goa_human, delimiter="\t", header=None, skiprows=41)
#gaf = pd.read_csv(goa_human_rna, delimiter="\t", header=None, skiprows=23)
gaf.columns = columns
gaf

/data/analysis/ag-reils/ag-reils-shared/deps/miniconda3/envs/u006/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (15) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,DB,DB_Object_ID,DB_Object_Symbol,Qualifier,GO_ID,DB_Reference,Evidence_Code,With_or_From,Aspect,DB_Object_Name,DB_Object_Synonym,DB_Object_Type,Taxon,Date,Assigned_by,Annotation_Extension,Annotation_Properties
0,UniProtKB,A0A024RBG1,NUDT4B,enables,GO:0003723,GO_REF:0000043,IEA,UniProtKB-KW:KW-0694,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211010,UniProt,NaN,NaN
1,UniProtKB,A0A024RBG1,NUDT4B,enables,GO:0046872,GO_REF:0000043,IEA,UniProtKB-KW:KW-0479,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211010,UniProt,NaN,NaN
2,UniProtKB,A0A024RBG1,NUDT4B,enables,GO:0052840,GO_REF:0000003,IEA,EC:3.6.1.52,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211009,UniProt,NaN,NaN
3,UniProtKB,A0A024RBG1,NUDT4B,enables,GO:0052842,GO_REF:0000003,IEA,EC:3.6.1.52,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211009,UniProt,NaN,NaN
4,UniProtKB,A0A024RBG1,NUDT4B,located_in,GO:0005829,GO_REF:0000052,IDA,NaN,C,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20161204,HPA,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617523,UniProtKB,Q9UM73,ALK,involved_in,GO:0042127,PMID:21873635,IBA,PANTHER:PTN000699408|MGI:MGI:103305,P,ALK tyrosine kinase receptor,ALK,protein,taxon:9606,20181026,GO_Central,NaN,NaN
617524,UniProtKB,Q9H4H8,FAM83D,involved_in,GO:0007165,PMID:21873635,IBA,PANTHER:PTN004490657|UniProtKB:Q5T0W9|UniProtK...,P,Protein FAM83D,FAM83D|C20orf129,protein,taxon:9606,20200408,GO_Central,NaN,NaN
617525,UniProtKB,Q9BXS6,NUSAP1,is_active_in,GO:0005730,PMID:21873635,IBA,PANTHER:PTN001286938|MGI:MGI:2675669,C,Nucleolar and spindle-associated protein 1,NUSAP1|ANKT|BM-037|PRO0310,protein,taxon:9606,20170228,GO_Central,NaN,NaN
617526,UniProtKB,Q8NHG7,SVIP,involved_in,GO:1904153,PMID:21873635,IBA,PANTHER:PTN002173988|UniProtKB:Q8NHG7,P,Small VCP/p97-interacting protein,SVIP,protein,taxon:9606,20200702,GO_Central,NaN,NaN
617527,UniProtKB,Q9UJW8,ZNF180,enables,GO:0000981,PMID:21873635,IBA,PANTHER:PTN004701291|UniProtKB:Q86UQ0|MGI:MGI:...,F,Zinc finger protein 180,ZNF180,protein,taxon:9606,20210531,GO_Central,NaN,NaN

### Modify GAF + Map to genes/ transcripts

In [231]:
if uniprot_or_rnacentral == "uniprot":
    if databases:
        gaf = gaf[gaf["Assigned_by"].isin(databases)]
gaf

,DB,DB_Object_ID,DB_Object_Symbol,Qualifier,GO_ID,DB_Reference,Evidence_Code,With_or_From,Aspect,DB_Object_Name,DB_Object_Synonym,DB_Object_Type,Taxon,Date,Assigned_by,Annotation_Extension,Annotation_Properties
0,UniProtKB,A0A024RBG1,NUDT4B,enables,GO:0003723,GO_REF:0000043,IEA,UniProtKB-KW:KW-0694,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211010,UniProt,NaN,NaN
1,UniProtKB,A0A024RBG1,NUDT4B,enables,GO:0046872,GO_REF:0000043,IEA,UniProtKB-KW:KW-0479,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211010,UniProt,NaN,NaN
2,UniProtKB,A0A024RBG1,NUDT4B,enables,GO:0052840,GO_REF:0000003,IEA,EC:3.6.1.52,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211009,UniProt,NaN,NaN
3,UniProtKB,A0A024RBG1,NUDT4B,enables,GO:0052842,GO_REF:0000003,IEA,EC:3.6.1.52,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211009,UniProt,NaN,NaN
5,UniProtKB,A0A075B6H7,IGKV3-7,involved_in,GO:0002250,GO_REF:0000043,IEA,UniProtKB-KW:KW-1064,P,Probable non-functional immunoglobulin kappa v...,IGKV3-7,protein,taxon:9606,20211010,UniProt,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617523,UniProtKB,Q9UM73,ALK,involved_in,GO:0042127,PMID:21873635,IBA,PANTHER:PTN000699408|MGI:MGI:103305,P,ALK tyrosine kinase receptor,ALK,protein,taxon:9606,20181026,GO_Central,NaN,NaN
617524,UniProtKB,Q9H4H8,FAM83D,involved_in,GO:0007165,PMID:21873635,IBA,PANTHER:PTN004490657|UniProtKB:Q5T0W9|UniProtK...,P,Protein FAM83D,FAM83D|C20orf129,protein,taxon:9606,20200408,GO_Central,NaN,NaN
617525,UniProtKB,Q9BXS6,NUSAP1,is_active_in,GO:0005730,PMID:21873635,IBA,PANTHER:PTN001286938|MGI:MGI:2675669,C,Nucleolar and spindle-associated protein 1,NUSAP1|ANKT|BM-037|PRO0310,protein,taxon:9606,20170228,GO_Central,NaN,NaN
617526,UniProtKB,Q8NHG7,SVIP,involved_in,GO:1904153,PMID:21873635,IBA,PANTHER:PTN002173988|UniProtKB:Q8NHG7,P,Small VCP/p97-interacting protein,SVIP,protein,taxon:9606,20200702,GO_Central,NaN,NaN
617527,UniProtKB,Q9UJW8,ZNF180,enables,GO:0000981,PMID:21873635,IBA,PANTHER:PTN004701291|UniProtKB:Q86UQ0|MGI:MGI:...,F,Zinc finger protein 180,ZNF180,protein,taxon:9606,20210531,GO_Central,NaN,NaN

In [232]:
if evidence_codes:
    gaf = gaf[gaf["Evidence_Code"].isin(evidence_codes)]
gaf

,DB,DB_Object_ID,DB_Object_Symbol,Qualifier,GO_ID,DB_Reference,Evidence_Code,With_or_From,Aspect,DB_Object_Name,DB_Object_Synonym,DB_Object_Type,Taxon,Date,Assigned_by,Annotation_Extension,Annotation_Properties
0,UniProtKB,A0A024RBG1,NUDT4B,enables,GO:0003723,GO_REF:0000043,IEA,UniProtKB-KW:KW-0694,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211010,UniProt,NaN,NaN
1,UniProtKB,A0A024RBG1,NUDT4B,enables,GO:0046872,GO_REF:0000043,IEA,UniProtKB-KW:KW-0479,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211010,UniProt,NaN,NaN
2,UniProtKB,A0A024RBG1,NUDT4B,enables,GO:0052840,GO_REF:0000003,IEA,EC:3.6.1.52,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211009,UniProt,NaN,NaN
3,UniProtKB,A0A024RBG1,NUDT4B,enables,GO:0052842,GO_REF:0000003,IEA,EC:3.6.1.52,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211009,UniProt,NaN,NaN
5,UniProtKB,A0A075B6H7,IGKV3-7,involved_in,GO:0002250,GO_REF:0000043,IEA,UniProtKB-KW:KW-1064,P,Probable non-functional immunoglobulin kappa v...,IGKV3-7,protein,taxon:9606,20211010,UniProt,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617523,UniProtKB,Q9UM73,ALK,involved_in,GO:0042127,PMID:21873635,IBA,PANTHER:PTN000699408|MGI:MGI:103305,P,ALK tyrosine kinase receptor,ALK,protein,taxon:9606,20181026,GO_Central,NaN,NaN
617524,UniProtKB,Q9H4H8,FAM83D,involved_in,GO:0007165,PMID:21873635,IBA,PANTHER:PTN004490657|UniProtKB:Q5T0W9|UniProtK...,P,Protein FAM83D,FAM83D|C20orf129,protein,taxon:9606,20200408,GO_Central,NaN,NaN
617525,UniProtKB,Q9BXS6,NUSAP1,is_active_in,GO:0005730,PMID:21873635,IBA,PANTHER:PTN001286938|MGI:MGI:2675669,C,Nucleolar and spindle-associated protein 1,NUSAP1|ANKT|BM-037|PRO0310,protein,taxon:9606,20170228,GO_Central,NaN,NaN
617526,UniProtKB,Q8NHG7,SVIP,involved_in,GO:1904153,PMID:21873635,IBA,PANTHER:PTN002173988|UniProtKB:Q8NHG7,P,Small VCP/p97-interacting protein,SVIP,protein,taxon:9606,20200702,GO_Central,NaN,NaN
617527,UniProtKB,Q9UJW8,ZNF180,enables,GO:0000981,PMID:21873635,IBA,PANTHER:PTN004701291|UniProtKB:Q86UQ0|MGI:MGI:...,F,Zinc finger protein 180,ZNF180,protein,taxon:9606,20210531,GO_Central,NaN,NaN

In [233]:
if uniprot_or_rnacentral == "uniprot":
    if gene_transcript == "gene":
        gaf_joined = gaf.join(ensembl_gene_uniprot.set_index("UniProtKB/Swiss-Prot ID"), on="DB_Object_ID")
        gaf_joined["DB_Object_ID"] = gaf_joined["Gene stable ID"]
        del gaf_joined["Gene stable ID"]
        gaf_joined = gaf_joined[~gaf_joined["DB_Object_ID"].isnull()]
    if gene_transcript == "transcript":
        gaf_joined = gaf.join(ensembl_transcript_uniprot.set_index("UniProtKB/Swiss-Prot ID"), on="DB_Object_ID")
        gaf_joined["DB_Object_ID"] = gaf_joined["Transcript stable ID"]
        del gaf_joined["Transcript stable ID"]
        gaf_joined = gaf_joined[~gaf_joined["DB_Object_ID"].isnull()]
elif uniprot_or_rnacentral == "rnacentral":
    gaf["DB_Object_ID"] = gaf["DB_Object_ID"].apply(lambda x: x.split("_")[0])
    if gene_transcript == "gene":
        gaf_joined = gaf.join(ensembl_gene_rnacentral.set_index("RNAcentral ID"), on="DB_Object_ID")
        gaf_joined["DB_Object_ID"] = gaf_joined["Gene stable ID"]
        del gaf_joined["Gene stable ID"]
        gaf_joined = gaf_joined[~gaf_joined["DB_Object_ID"].isnull()]
    if gene_transcript == "transcript":
        gaf_joined = gaf.join(ensembl_transcript_rnacentral.set_index("RNAcentral ID"), on="DB_Object_ID")
        gaf_joined["DB_Object_ID"] = gaf_joined["Transcript stable ID"]
        del gaf_joined["Transcript stable ID"]
        gaf_joined = gaf_joined[~gaf_joined["DB_Object_ID"].isnull()]
gaf_joined

,DB,DB_Object_ID,DB_Object_Symbol,Qualifier,GO_ID,DB_Reference,Evidence_Code,With_or_From,Aspect,DB_Object_Name,DB_Object_Synonym,DB_Object_Type,Taxon,Date,Assigned_by,Annotation_Extension,Annotation_Properties
0,UniProtKB,ENSG00000177144,NUDT4B,enables,GO:0003723,GO_REF:0000043,IEA,UniProtKB-KW:KW-0694,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211010,UniProt,NaN,NaN
1,UniProtKB,ENSG00000177144,NUDT4B,enables,GO:0046872,GO_REF:0000043,IEA,UniProtKB-KW:KW-0479,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211010,UniProt,NaN,NaN
2,UniProtKB,ENSG00000177144,NUDT4B,enables,GO:0052840,GO_REF:0000003,IEA,EC:3.6.1.52,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211009,UniProt,NaN,NaN
3,UniProtKB,ENSG00000177144,NUDT4B,enables,GO:0052842,GO_REF:0000003,IEA,EC:3.6.1.52,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211009,UniProt,NaN,NaN
5,UniProtKB,ENSG00000282310,IGKV3-7,involved_in,GO:0002250,GO_REF:0000043,IEA,UniProtKB-KW:KW-1064,P,Probable non-functional immunoglobulin kappa v...,IGKV3-7,protein,taxon:9606,20211010,UniProt,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617523,UniProtKB,ENSG00000171094,ALK,involved_in,GO:0042127,PMID:21873635,IBA,PANTHER:PTN000699408|MGI:MGI:103305,P,ALK tyrosine kinase receptor,ALK,protein,taxon:9606,20181026,GO_Central,NaN,NaN
617524,UniProtKB,ENSG00000101447,FAM83D,involved_in,GO:0007165,PMID:21873635,IBA,PANTHER:PTN004490657|UniProtKB:Q5T0W9|UniProtK...,P,Protein FAM83D,FAM83D|C20orf129,protein,taxon:9606,20200408,GO_Central,NaN,NaN
617525,UniProtKB,ENSG00000137804,NUSAP1,is_active_in,GO:0005730,PMID:21873635,IBA,PANTHER:PTN001286938|MGI:MGI:2675669,C,Nucleolar and spindle-associated protein 1,NUSAP1|ANKT|BM-037|PRO0310,protein,taxon:9606,20170228,GO_Central,NaN,NaN
617526,UniProtKB,ENSG00000198168,SVIP,involved_in,GO:1904153,PMID:21873635,IBA,PANTHER:PTN002173988|UniProtKB:Q8NHG7,P,Small VCP/p97-interacting protein,SVIP,protein,taxon:9606,20200702,GO_Central,NaN,NaN
617527,UniProtKB,ENSG00000167384,ZNF180,enables,GO:0000981,PMID:21873635,IBA,PANTHER:PTN004701291|UniProtKB:Q86UQ0|MGI:MGI:...,F,Zinc finger protein 180,ZNF180,protein,taxon:9606,20210531,GO_Central,NaN,NaN

### Save file

In [234]:
from itertools import islice
#with open(goa_human_isoform, "r") as myfile:
#    head = list(islice(myfile, 27))
with open(goa_human, "r") as myfile:
    head = list(islice(myfile, 41))
#with open(goa_human_rna, "r") as myfile:
#    head = list(islice(myfile, 23))
head

['!gaf-version: 2.2\n',
 '!\n',
 '!generated-by: GOC\n',
 '!\n',
 '!date-generated: 2022-01-14T16:45\n',
 '!\n',
 '!Header from source association file:\n',
 '!=================================\n',
 '!\n',
 '!generated-by: GOC\n',
 '!\n',
 '!date-generated: 2022-01-14T04:41\n',
 '!\n',
 '!Header from goa_human source association file:\n',
 '!=================================\n',
 '!\n',
 '!The set of protein accessions included in this file is based on UniProt reference proteomes, which provide one protein per gene.\n',
 '!They include the protein sequences annotated in Swiss-Prot or the longest TrEMBL transcript if there is no Swiss-Prot record.\n',
 '!If a particular protein accession is not annotated with GO, then it will not appear in this file.\n',
 '!\n',
 '!Note that the annotation set in this file is filtered in order to reduce redundancy; the full, unfiltered set can be found in\n',
 '!ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gz\n',
 '!\n',
 '!date-generated: 2021-11-08 15:48\n',
 '!generated-by: UniProt\n',
 '!go-version: http://purl.obolibrary.org/obo/go/releases/2021-11-06/extensions/go-plus.owl\n',
 '!\n',
 '!=================================\n',
 '!\n',
 '!Header copied from paint_goa_human_valid.gaf\n',
 '!=================================\n',
 '!Created on Sun Jan  2 19:01:56 2022.\n',
 '!generated-by: PANTHER\n',
 '!date-generated: 2022-01-02\n',
 '!PANTHER version: v.15.0.\n',
 '!GO version: 2021-11-16.\n',
 '!\n',
 '!=================================\n',
 '!\n',
 '!Documentation about this header can be found here: https://github.com/geneontology/go-site/blob/master/docs/gaf_validation.md\n',
 '!\n']

In [235]:
# always remember, use files in a with statement
with open('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_databases_uniprot_reactome_ensembl_intact_gocentral_ensembl_gene_mapping.gaf', "w") as f2:
    for item in head:
        f2.write(item)

In [236]:
gaf_joined.to_csv('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_databases_uniprot_reactome_ensembl_intact_gocentral_ensembl_gene_mapping.gaf', mode="a", sep="\t", header=False, index=False)

## RNA DK using NPInterv4 database

### Load obodag

In [115]:
from goatools.obo_parser import GODag

obodag = GODag("/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/go-basic.obo")
len(obodag.keys())

/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/go-basic.obo: fmt(1.2) rel(2019-07-01) 47,413 GO Terms

47413

### Load GAF files

In [116]:
gaf_human = pd.read_csv('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_ensembl_gene_mapping.gaf', skiprows=41, header=None, delimiter="\t")
gaf_human_isoform = pd.read_csv('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_isoform_ensembl_gene_mapping.gaf', skiprows=27, header=None, delimiter="\t")
gaf_human_rna = pd.read_csv('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_rna_ensembl_gene_mapping.gaf', skiprows=23, header=None, delimiter="\t")
gaf = pd.concat([gaf_human, gaf_human_isoform])#, gaf_human_rna])
gaf

/data/analysis/ag-reils/ag-reils-shared/deps/miniconda3/envs/u006/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (15) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,UniProtKB,ENSG00000177144,NUDT4B,enables,GO:0003723,GO_REF:0000043,IEA,UniProtKB-KW:KW-0694,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211010,UniProt,NaN,NaN
1,UniProtKB,ENSG00000177144,NUDT4B,enables,GO:0046872,GO_REF:0000043,IEA,UniProtKB-KW:KW-0479,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211010,UniProt,NaN,NaN
2,UniProtKB,ENSG00000177144,NUDT4B,enables,GO:0052840,GO_REF:0000003,IEA,EC:3.6.1.52,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211009,UniProt,NaN,NaN
3,UniProtKB,ENSG00000177144,NUDT4B,enables,GO:0052842,GO_REF:0000003,IEA,EC:3.6.1.52,F,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20211009,UniProt,NaN,NaN
4,UniProtKB,ENSG00000177144,NUDT4B,located_in,GO:0005829,GO_REF:0000052,IDA,NaN,C,Diphosphoinositol polyphosphate phosphohydrola...,NUDT4B,protein,taxon:9606,20161204,HPA,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35506,UniProtKB,ENSG00000152217,SETBP1,enables,GO:0005515,PMID:32296183,IPI,UniProtKB:Q7KZS0,F,SET-binding protein,SETBP1|KIAA0437,protein,taxon:9606,20211030,IntAct,NaN,UniProtKB:Q9Y6X0-2
35507,UniProtKB,ENSG00000152217,SETBP1,enables,GO:0005515,PMID:32296183,IPI,UniProtKB:Q9BXN6,F,SET-binding protein,SETBP1|KIAA0437,protein,taxon:9606,20211030,IntAct,NaN,UniProtKB:Q9Y6X0-2
35508,UniProtKB,ENSG00000152217,SETBP1,enables,GO:0005515,PMID:32296183,IPI,UniProtKB:Q9H8W4,F,SET-binding protein,SETBP1|KIAA0437,protein,taxon:9606,20211030,IntAct,NaN,UniProtKB:Q9Y6X0-2
35509,UniProtKB,ENSG00000152217,SETBP1,enables,GO:0005515,PMID:32296183,IPI,UniProtKB:Q9NS26,F,SET-binding protein,SETBP1|KIAA0437,protein,taxon:9606,20211030,IntAct,NaN,UniProtKB:Q9Y6X0-2
35510,UniProtKB,ENSG00000133422,MORC2,enables,GO:0042802,PMID:29440755,IPI,UniProtKB:Q9Y6X9-1,F,ATPase MORC2,MORC2|KIAA0852|ZCWCC1,protein,taxon:9606,20211030,IntAct,NaN,UniProtKB:Q9Y6X9-1

### Load NPInterv4

In [117]:
file_npinterv4 = "/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/interaction_NPInterv4.txt"
npinterv4 = pd.read_csv(file_npinterv4, sep="\t", dtype=str)
npinterv4 = npinterv4[npinterv4['organism']=="Homo sapiens"]
npinterv4 = npinterv4[~(npinterv4['tarID']=="-")]
npinterv4 = npinterv4[~(npinterv4['ncID']=="-")]
npinterv4 = npinterv4[npinterv4['tarID'].notna()]
npinterv4 = npinterv4[npinterv4['ncID'].notna()]
npinterv4

,interID,ncName,ncID,ncType,tarName,tarID,tarType,interDescription,experiment,reference,organism,tissueOrCell,tag,class,level,datasource
3,ncRI-40000004,7SK,NONHSAG040596,lncRNA,MYC,NM_002467,protein,Electrophoretic mobility shift experiment indi...,EMSA,9018369,Homo sapiens,-,regulatory;promoter as action site,regulatory,RNA-RNA,Literature mining
4,ncRI-40000005,7SK,NONHSAG040596,lncRNA,ABO,NM_020469,protein,Promoters pU6 and p7SK proved to express high ...,-,22522162,Homo sapiens,-,regulatory,regulatory,RNA-RNA,Literature mining
5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,15201869;15994294;17671421;20675720;20926576;1...,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining
6,ncRI-40000007,7SK,NONHSAG040596,lncRNA,Oct1,P20263,protein,PTF and Oct-1 enhance transcription from the 7...,-,1535687,Homo sapiens,-,ncRNA is regulated,regulatory,DNA-TF,Literature mining
7,ncRI-40000008,7SK,NONHSAG040596,lncRNA,Tat,P17735,protein,Tat efficiently replaces HEXIM1 on the 7SK snR...,-,20976203;20471949,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1100531,ncRI-41100533,hsa-miR-151b,MI0003772,miRNA,NUFIP2,ENSG00000108256,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database
1100532,ncRI-41100534,hsa-miR-151b,MI0003772,miRNA,SLC15A4,ENSG00000139370,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database
1100533,ncRI-41100535,hsa-miR-151b,MI0003772,miRNA,TBC1D10B,ENSG00000169221,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database
1100534,ncRI-41100536,hsa-miR-548d-5p,MI0003671,miRNA,HDLBP,ENSG00000115677,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database
1100535,ncRI-41100537,hsa-miR-548d-5p,MI0003671,miRNA,ZMYND8,ENSG00000101040,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database

In [118]:
npinterv4['ncID'] = npinterv4['ncID'].str.split(';')
npinterv4 = npinterv4.explode('ncID')
npinterv4['tarID'] = npinterv4['tarID'].str.split(';')
npinterv4 = npinterv4.explode('tarID')
npinterv4

,interID,ncName,ncID,ncType,tarName,tarID,tarType,interDescription,experiment,reference,organism,tissueOrCell,tag,class,level,datasource
3,ncRI-40000004,7SK,NONHSAG040596,lncRNA,MYC,NM_002467,protein,Electrophoretic mobility shift experiment indi...,EMSA,9018369,Homo sapiens,-,regulatory;promoter as action site,regulatory,RNA-RNA,Literature mining
4,ncRI-40000005,7SK,NONHSAG040596,lncRNA,ABO,NM_020469,protein,Promoters pU6 and p7SK proved to express high ...,-,22522162,Homo sapiens,-,regulatory,regulatory,RNA-RNA,Literature mining
5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,15201869;15994294;17671421;20675720;20926576;1...,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining
6,ncRI-40000007,7SK,NONHSAG040596,lncRNA,Oct1,P20263,protein,PTF and Oct-1 enhance transcription from the 7...,-,1535687,Homo sapiens,-,ncRNA is regulated,regulatory,DNA-TF,Literature mining
7,ncRI-40000008,7SK,NONHSAG040596,lncRNA,Tat,P17735,protein,Tat efficiently replaces HEXIM1 on the 7SK snR...,-,20976203;20471949,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1100531,ncRI-41100533,hsa-miR-151b,MI0003772,miRNA,NUFIP2,ENSG00000108256,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database
1100532,ncRI-41100534,hsa-miR-151b,MI0003772,miRNA,SLC15A4,ENSG00000139370,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database
1100533,ncRI-41100535,hsa-miR-151b,MI0003772,miRNA,TBC1D10B,ENSG00000169221,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database
1100534,ncRI-41100536,hsa-miR-548d-5p,MI0003671,miRNA,HDLBP,ENSG00000115677,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database
1100535,ncRI-41100537,hsa-miR-548d-5p,MI0003671,miRNA,ZMYND8,ENSG00000101040,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database

### BioMaRt mapping files

#### RNACentral to ENSG

In [119]:
from pybiomart import Server

server = Server(host='http://www.ensembl.org')

dataset = (server.marts['ENSEMBL_MART_ENSEMBL']
                 .datasets['hsapiens_gene_ensembl'])

In [120]:
ensembl_gene_gene_name = dataset.query(attributes=['ensembl_gene_id', 'external_gene_name'])
ensembl_gene_gene_name["Gene name"] = ensembl_gene_gene_name["Gene name"].astype("str")
ensembl_gene_gene_name

        Gene stable ID Gene name
0      ENSG00000210049     MT-TF
1      ENSG00000211459   MT-RNR1
2      ENSG00000210077     MT-TV
3      ENSG00000210082   MT-RNR2
4      ENSG00000209082    MT-TL1
...                ...       ...
68000  ENSG00000286142       nan
68001  ENSG00000077585   GPR137B
68002  ENSG00000222650  RNU2-70P
68003  ENSG00000237922       nan
68004  ENSG00000086619     ERO1B

[68005 rows x 2 columns]

In [121]:
ensembl_gene_uniprot = dataset.query(attributes=['ensembl_gene_id', 'uniprotswissprot'])
ensembl_gene_uniprot = ensembl_gene_uniprot[~ensembl_gene_uniprot["UniProtKB/Swiss-Prot ID"].isnull()]
ensembl_gene_uniprot.columns = ['ensembl_code', 'tar_ncRNA_code']
ensembl_gene_uniprot['rnacentral_idcode'] = [np.nan] * len(ensembl_gene_uniprot)
ensembl_gene_uniprot

          ensembl_code tar_ncRNA_code  rnacentral_idcode
0      ENSG00000198888         P03886                NaN
1      ENSG00000198763         P03891                NaN
2      ENSG00000198804         P00395                NaN
3      ENSG00000198712         P00403                NaN
4      ENSG00000228253         P03928                NaN
...                ...            ...                ...
38143  ENSG00000142961         Q70IA8                NaN
38144  ENSG00000116754         Q05519                NaN
38146  ENSG00000283324     A0A1B0GV90                NaN
38148  ENSG00000077585         O60478                NaN
38149  ENSG00000086619         Q86YB8                NaN

[21444 rows x 3 columns]

In [122]:
mapping_file_rna_central_ensembl = "/dh-projects/uk_bb_intergenics/analysis/data/genopheno/scrnaseq/databases/RNAcentral/ensembl.tsv"
df_mapping_file_rna_central_ensembl = pd.read_csv(mapping_file_rna_central_ensembl, sep="\t", dtype=str, header= None)
df_mapping_file_rna_central_ensembl.columns = ["rnacentral_idcode", 1, 2, "species", 4, "ensembl_code"]
df_mapping_file_rna_central_ensembl = df_mapping_file_rna_central_ensembl[df_mapping_file_rna_central_ensembl["species"] == "9606"] 
df_mapping_file_rna_central_ensembl = df_mapping_file_rna_central_ensembl.loc[:, ["rnacentral_idcode", "ensembl_code"]]
df_mapping_file_rna_central_ensembl["ensembl_code"] = df_mapping_file_rna_central_ensembl["ensembl_code"].map(
    lambda ensembl_code: ensembl_code.split(".")[0])
df_mapping_file_rna_central_ensembl

        rnacentral_idcode     ensembl_code
0           URS0000000055  ENSG00000226803
1           URS00000000C9  ENSG00000248309
2           URS00000000FD  ENSG00000234279
3           URS0000000344  ENSG00000282594
4           URS0000000351  ENSG00000235427
...                   ...              ...
1427803     URS0002186B52  ENSG00000228147
1428829     URS0002186C00  ENSG00000188004
1429187     URS0002186D5F  ENSG00000188185
1429446     URS0002186E53  ENSG00000197568
1429684     URS0002186F40  ENSG00000225889

[54371 rows x 2 columns]

#### Other ncRNA identifiers to RNACentral 
Source: http://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/id_mapping/database_mappings/

In [123]:
mapping_file_noncode_rna_central = "/dh-projects/uk_bb_intergenics/analysis/data/genopheno/scrnaseq/databases/RNAcentral/noncode.tsv"
df_mapping_file_noncode_rna_central = pd.read_csv(mapping_file_noncode_rna_central, sep="\t", dtype=str, header= None)
df_mapping_file_noncode_rna_central.columns = ["rnacentral_idcode", 1, 2, "species", 4, "tar_ncRNA_code"]
df_mapping_file_noncode_rna_central = df_mapping_file_noncode_rna_central[df_mapping_file_noncode_rna_central["species"] == "9606"] 
df_mapping_file_noncode_rna_central = df_mapping_file_noncode_rna_central.loc[:, ["rnacentral_idcode", "tar_ncRNA_code"]]
df_mapping_file_noncode_rna_central["tar_ncRNA_code"] = df_mapping_file_noncode_rna_central["tar_ncRNA_code"].map(
    lambda noncode_code: noncode_code.split(".")[0])

mapping_file_mirbase_rna_central = "/dh-projects/uk_bb_intergenics/analysis/data/genopheno/scrnaseq/databases/RNAcentral/mirbase.tsv"
df_mapping_file_mirbase_rna_central = pd.read_csv(mapping_file_mirbase_rna_central, sep="\t", dtype=str, header = None)
df_mapping_file_mirbase_rna_central.columns = ["rnacentral_idcode", 1, "tar_ncRNA_code", "species", 4, 5]
df_mapping_file_mirbase_rna_central = df_mapping_file_mirbase_rna_central[df_mapping_file_mirbase_rna_central["species"] == "9606"] 
df_mapping_file_mirbase_rna_central = df_mapping_file_mirbase_rna_central.loc[:, ["rnacentral_idcode", "tar_ncRNA_code"]]

In [124]:
df_mapping_file_noncode_rna_central

       rnacentral_idcode tar_ncRNA_code
0          URS0000000055  NONHSAG044006
1          URS00000000C9  NONHSAG040980
2          URS00000000FD  NONHSAG030952
3          URS00000002D9  NONHSAG053806
4          URS0000000344  NONHSAG051423
...                  ...            ...
171524     URS00009C5F69  NONHSAG018506
171533     URS00009C5F72  NONHSAG031885
171539     URS00009C5F78  NONHSAG031385
171543     URS00009C5F7C  NONHSAG023181
171544     URS00009C5F7D  NONHSAG050377

[83623 rows x 2 columns]

In [125]:
df_mapping_file_mirbase_rna_central

      rnacentral_idcode tar_ncRNA_code
4         URS00000011DF   MIMAT0022711
9         URS0000001A7A      MI0003639
11        URS0000001EB3      MI0000089
125       URS00000037E8   MIMAT0019825
136       URS0000004CA3   MIMAT0018944
...                 ...            ...
86126     URS0000D5676C      MI0039727
86598     URS0000D56919      MI0033421
87125     URS0000D56AF1   MIMAT0044658
87156     URS0000D56B0E   MIMAT0048635
87281     URS0000D56B84      MI0039718

[4573 rows x 2 columns]

In [126]:
df_mapping_file_ncRNA_rna_central = pd.concat([df_mapping_file_noncode_rna_central, df_mapping_file_mirbase_rna_central], axis=0)
df_mapping_file_ncRNA_rna_central

      rnacentral_idcode tar_ncRNA_code
0         URS0000000055  NONHSAG044006
1         URS00000000C9  NONHSAG040980
2         URS00000000FD  NONHSAG030952
3         URS00000002D9  NONHSAG053806
4         URS0000000344  NONHSAG051423
...                 ...            ...
86126     URS0000D5676C      MI0039727
86598     URS0000D56919      MI0033421
87125     URS0000D56AF1   MIMAT0044658
87156     URS0000D56B0E   MIMAT0048635
87281     URS0000D56B84      MI0039718

[88196 rows x 2 columns]

### Map to Ensembl Code and combine with RNACentral <-> ENSG

In [127]:
df_mapping_file_ncRNA_rna_central_ensembl = df_mapping_file_ncRNA_rna_central.join(df_mapping_file_rna_central_ensembl.set_index("rnacentral_idcode"), on="rnacentral_idcode")
df_mapping_file_ncRNA_rna_central_ensembl = df_mapping_file_ncRNA_rna_central_ensembl[~df_mapping_file_ncRNA_rna_central_ensembl["ensembl_code"].isnull()]
df_mapping_file_rna_central_ensembl["tar_ncRNA_code"] = df_mapping_file_rna_central_ensembl["ensembl_code"]
df_mapping_file_ncRNA_rna_central_ensembl = pd.concat([df_mapping_file_ncRNA_rna_central_ensembl, df_mapping_file_rna_central_ensembl, ensembl_gene_uniprot], axis=0)
df_mapping_file_ncRNA_rna_central_ensembl

      rnacentral_idcode tar_ncRNA_code     ensembl_code
0         URS0000000055  NONHSAG044006  ENSG00000226803
1         URS00000000C9  NONHSAG040980  ENSG00000248309
2         URS00000000FD  NONHSAG030952  ENSG00000234279
4         URS0000000344  NONHSAG051423  ENSG00000282594
5         URS0000000351  NONHSAG048609  ENSG00000235427
...                 ...            ...              ...
38143               NaN         Q70IA8  ENSG00000142961
38144               NaN         Q05519  ENSG00000116754
38146               NaN     A0A1B0GV90  ENSG00000283324
38148               NaN         O60478  ENSG00000077585
38149               NaN         Q86YB8  ENSG00000086619

[96643 rows x 3 columns]

### Combine npinter file with ENSG mappings

In [128]:
npinterv4 = npinterv4.join(df_mapping_file_ncRNA_rna_central_ensembl.set_index("tar_ncRNA_code"), on="ncID")
npinterv4 = npinterv4[~npinterv4["ensembl_code"].isnull()]
npinterv4.rename(columns={'rnacentral_idcode':'ncID_rnacentral_code', 'ensembl_code':'ncID_ensembl_code'}, inplace=True)
npinterv4

,interID,ncName,ncID,ncType,tarName,tarID,tarType,interDescription,experiment,reference,organism,tissueOrCell,tag,class,level,datasource,ncID_rnacentral_code,ncID_ensembl_code
3,ncRI-40000004,7SK,NONHSAG040596,lncRNA,MYC,NM_002467,protein,Electrophoretic mobility shift experiment indi...,EMSA,9018369,Homo sapiens,-,regulatory;promoter as action site,regulatory,RNA-RNA,Literature mining,URS00004E902D,ENSG00000249352
4,ncRI-40000005,7SK,NONHSAG040596,lncRNA,ABO,NM_020469,protein,Promoters pU6 and p7SK proved to express high ...,-,22522162,Homo sapiens,-,regulatory,regulatory,RNA-RNA,Literature mining,URS00004E902D,ENSG00000249352
5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,15201869;15994294;17671421;20675720;20926576;1...,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352
6,ncRI-40000007,7SK,NONHSAG040596,lncRNA,Oct1,P20263,protein,PTF and Oct-1 enhance transcription from the 7...,-,1535687,Homo sapiens,-,ncRNA is regulated,regulatory,DNA-TF,Literature mining,URS00004E902D,ENSG00000249352
7,ncRI-40000008,7SK,NONHSAG040596,lncRNA,Tat,P17735,protein,Tat efficiently replaces HEXIM1 on the 7SK snR...,-,20976203;20471949,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1100531,ncRI-41100533,hsa-miR-151b,MI0003772,miRNA,NUFIP2,ENSG00000108256,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000075C169,ENSG00000265154
1100532,ncRI-41100534,hsa-miR-151b,MI0003772,miRNA,SLC15A4,ENSG00000139370,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000075C169,ENSG00000265154
1100533,ncRI-41100535,hsa-miR-151b,MI0003772,miRNA,TBC1D10B,ENSG00000169221,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000075C169,ENSG00000265154
1100534,ncRI-41100536,hsa-miR-548d-5p,MI0003671,miRNA,HDLBP,ENSG00000115677,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS0000759C79,ENSG00000263690
1100535,ncRI-41100537,hsa-miR-548d-5p,MI0003671,miRNA,ZMYND8,ENSG00000101040,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS0000759C79,ENSG00000263690

### ncID GO Retrievement

In [129]:
npinterv4_ncid = npinterv4.copy()
npinterv4_ncid

,interID,ncName,ncID,ncType,tarName,tarID,tarType,interDescription,experiment,reference,organism,tissueOrCell,tag,class,level,datasource,ncID_rnacentral_code,ncID_ensembl_code
3,ncRI-40000004,7SK,NONHSAG040596,lncRNA,MYC,NM_002467,protein,Electrophoretic mobility shift experiment indi...,EMSA,9018369,Homo sapiens,-,regulatory;promoter as action site,regulatory,RNA-RNA,Literature mining,URS00004E902D,ENSG00000249352
4,ncRI-40000005,7SK,NONHSAG040596,lncRNA,ABO,NM_020469,protein,Promoters pU6 and p7SK proved to express high ...,-,22522162,Homo sapiens,-,regulatory,regulatory,RNA-RNA,Literature mining,URS00004E902D,ENSG00000249352
5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,15201869;15994294;17671421;20675720;20926576;1...,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352
6,ncRI-40000007,7SK,NONHSAG040596,lncRNA,Oct1,P20263,protein,PTF and Oct-1 enhance transcription from the 7...,-,1535687,Homo sapiens,-,ncRNA is regulated,regulatory,DNA-TF,Literature mining,URS00004E902D,ENSG00000249352
7,ncRI-40000008,7SK,NONHSAG040596,lncRNA,Tat,P17735,protein,Tat efficiently replaces HEXIM1 on the 7SK snR...,-,20976203;20471949,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1100531,ncRI-41100533,hsa-miR-151b,MI0003772,miRNA,NUFIP2,ENSG00000108256,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000075C169,ENSG00000265154
1100532,ncRI-41100534,hsa-miR-151b,MI0003772,miRNA,SLC15A4,ENSG00000139370,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000075C169,ENSG00000265154
1100533,ncRI-41100535,hsa-miR-151b,MI0003772,miRNA,TBC1D10B,ENSG00000169221,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000075C169,ENSG00000265154
1100534,ncRI-41100536,hsa-miR-548d-5p,MI0003671,miRNA,HDLBP,ENSG00000115677,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS0000759C79,ENSG00000263690
1100535,ncRI-41100537,hsa-miR-548d-5p,MI0003671,miRNA,ZMYND8,ENSG00000101040,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS0000759C79,ENSG00000263690

In [130]:
npinterv4_ncid["ncID"] = npinterv4_ncid[['interID', 'ncName', 'ncID', 'ncType', 'tarName', 'tarID', 'tarType', 'interDescription', 'experiment', 'reference', 'organism', 'tissueOrCell', 'tag', 'class', 'level', 'datasource', 'ncID_rnacentral_code', 'ncID_ensembl_code']].groupby(['ncID_ensembl_code'])["ncID"].transform(lambda x: '; '.join(x))
npinterv4_ncid["ncType"] = npinterv4_ncid[['interID', 'ncName', 'ncID', 'ncType', 'tarName', 'tarID', 'tarType', 'interDescription', 'experiment', 'reference', 'organism', 'tissueOrCell', 'tag', 'class', 'level', 'datasource', 'ncID_rnacentral_code', 'ncID_ensembl_code']].groupby(['ncID_ensembl_code'])["ncType"].transform(lambda x: '; '.join(x))
npinterv4_ncid["reference"] = npinterv4_ncid[['interID', 'ncName', 'ncID', 'ncType', 'tarName', 'tarID', 'tarType', 'interDescription', 'experiment', 'reference', 'organism', 'tissueOrCell', 'tag', 'class', 'level', 'datasource', 'ncID_rnacentral_code', 'ncID_ensembl_code']].groupby(['ncID_ensembl_code'])["reference"].transform(lambda x: '; '.join(x))
npinterv4_ncid = npinterv4_ncid[["ncID", "ncType", "reference", 'ncID_ensembl_code', 'ncID_rnacentral_code', "tag", "level"]].drop_duplicates()
npinterv4_ncid["tag"] = npinterv4_ncid[["ncID", "ncType", "reference", "ncID_ensembl_code", "ncID_rnacentral_code", "tag", "level"]].groupby(["ncID_ensembl_code"])["tag"].transform(lambda x: ';'.join(x))
npinterv4_ncid["level"] = npinterv4_ncid[["ncID", "ncType", "reference", "ncID_ensembl_code", "ncID_rnacentral_code", "tag", "level"]].groupby(["ncID_ensembl_code"])["level"].transform(lambda x: ';'.join(x))
npinterv4_ncid = npinterv4_ncid[["ncID", "ncType", "reference", "ncID_ensembl_code", "ncID_rnacentral_code", "tag", "level"]].drop_duplicates()
npinterv4_ncid

,ncID,ncType,reference,ncID_ensembl_code,ncID_rnacentral_code,tag,level
3,NONHSAG040596; NONHSAG040596; NONHSAG040596; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,9018369; 22522162; 15201869;15994294;17671421;...,ENSG00000249352,URS00004E902D,regulatory;promoter as action site;regulatory;...,RNA-RNA;RNA-RNA;RNA-Protein;DNA-TF;RNA-Protein...
24,NONHSAG048195; NONHSAG048195; NONHSAG048195; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,25531890; 24164894;22955616; 25301781; 2384659...,ENSG00000243107,URS0000539BDF,miRNA target interaction;RNA-RNA interaction;n...,RNA-RNA;RNA-Protein;RNA-RNA
25,NONHSAG048720; NONHSAG048720; NONHSAG048720; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,25531890; 25301781; 24332178; -; 23023293; 263...,ENSG00000226770,URS0000477DCE,miRNA target interaction;RNA-RNA interaction;n...,RNA-RNA;RNA-Protein
28,NONHSAG048153; NONHSAG048153; NONHSAG048153; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,25531890; 25301781; -; 23023293; 26321680; 280...,ENSG00000233420,URS00003A4444,miRNA target interaction;RNA-RNA interaction;n...,RNA-RNA;RNA-Protein
29,NONHSAG019101; NONHSAG019101; NONHSAG019101; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,25531890; 25531890; 25301781; 25301781; -; -; ...,ENSG00000235560,URS000028AB2B,miRNA target interaction;RNA-RNA interaction;m...,RNA-RNA;RNA-RNA;RNA-Protein;RNA-Protein;RNA-RN...
...,...,...,...,...,...,...,...
1100453,ENSG00000199787,snoRNA,27184080,ENSG00000199787,URS000063D36F,RNA-RNA interaction,RNA-RNA
1100455,ENSG00000263764,snoRNA,27184080,ENSG00000263764,URS000063F175,RNA-RNA interaction,RNA-RNA
1100456,ENSG00000208892,snoRNA,27184080,ENSG00000208892,URS00006276F4,RNA-RNA interaction,RNA-RNA
1100460,ENSG00000200753,snoRNA,27184080,ENSG00000200753,URS000006D2A0,RNA-RNA interaction,RNA-RNA
1100515,MI0019145; MI0019145,miRNA; miRNA,23622248; 23622248,ENSG00000283146,URS000075B121,RNA-RNA interaction,RNA-RNA

In [131]:
npinterv4_ncid["go_terms"] = np.nan
npinterv4_ncid["taxonomy"] = 9606
npinterv4_ncid

,ncID,ncType,reference,ncID_ensembl_code,ncID_rnacentral_code,tag,level,go_terms,taxonomy
3,NONHSAG040596; NONHSAG040596; NONHSAG040596; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,9018369; 22522162; 15201869;15994294;17671421;...,ENSG00000249352,URS00004E902D,regulatory;promoter as action site;regulatory;...,RNA-RNA;RNA-RNA;RNA-Protein;DNA-TF;RNA-Protein...,NaN,9606
24,NONHSAG048195; NONHSAG048195; NONHSAG048195; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,25531890; 24164894;22955616; 25301781; 2384659...,ENSG00000243107,URS0000539BDF,miRNA target interaction;RNA-RNA interaction;n...,RNA-RNA;RNA-Protein;RNA-RNA,NaN,9606
25,NONHSAG048720; NONHSAG048720; NONHSAG048720; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,25531890; 25301781; 24332178; -; 23023293; 263...,ENSG00000226770,URS0000477DCE,miRNA target interaction;RNA-RNA interaction;n...,RNA-RNA;RNA-Protein,NaN,9606
28,NONHSAG048153; NONHSAG048153; NONHSAG048153; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,25531890; 25301781; -; 23023293; 26321680; 280...,ENSG00000233420,URS00003A4444,miRNA target interaction;RNA-RNA interaction;n...,RNA-RNA;RNA-Protein,NaN,9606
29,NONHSAG019101; NONHSAG019101; NONHSAG019101; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,25531890; 25531890; 25301781; 25301781; -; -; ...,ENSG00000235560,URS000028AB2B,miRNA target interaction;RNA-RNA interaction;m...,RNA-RNA;RNA-RNA;RNA-Protein;RNA-Protein;RNA-RN...,NaN,9606
...,...,...,...,...,...,...,...,...,...
1100453,ENSG00000199787,snoRNA,27184080,ENSG00000199787,URS000063D36F,RNA-RNA interaction,RNA-RNA,NaN,9606
1100455,ENSG00000263764,snoRNA,27184080,ENSG00000263764,URS000063F175,RNA-RNA interaction,RNA-RNA,NaN,9606
1100456,ENSG00000208892,snoRNA,27184080,ENSG00000208892,URS00006276F4,RNA-RNA interaction,RNA-RNA,NaN,9606
1100460,ENSG00000200753,snoRNA,27184080,ENSG00000200753,URS000006D2A0,RNA-RNA interaction,RNA-RNA,NaN,9606
1100515,MI0019145; MI0019145,miRNA; miRNA,23622248; 23622248,ENSG00000283146,URS000075B121,RNA-RNA interaction,RNA-RNA,NaN,9606

#### NC-iD GO-Terms Mapping

In [132]:
#For the nc version the GO terms are assigned to specific genes by specific tags and keywords in the NPInter database.
#The exact dictionary explaining the assignment of GO terms based on these tags is given here.
# For a simplified version please also refer to ./resources/single_cell/mapping_keyword_go_term_npinterv4.json.

manually_mapped_go_terms = {
    "bp_only": {
        "promoter as action site": "GO:0010468", #regulation of gene expression
        "ncRNA affects synthesis or function of protein": "GO:0040033",
        "expression, or processing, or function of ncRNA is affected": "GO:0034661", #ncRNA catabolic process
        "ncRNA targets mRNA": "GO:0016071"
    },
    "bp_mf": {
        "miRNA target interaction": "GO:0010586;GO:0010467;GO:0035198", #miRNA metabolic process
        "miRNA": "GO:0010586;GO:0035198", #miRNA metabolic process
        "promoter as action site": "GO:0001046",
        "DNA-TF": "GO:0008134;GO:0005515",
        "RNA-TF": "GO:0008134;GO:0005515",
        "lncRNA-TF": "GO:0008134;GO:0005515",
        "RNA-DNA": "GO:0003677;GO:0003723",
        "RNA-RNA": "GO:0003723",
        "DNA-DNA": "GO:0003677",
        "RNA-Protein": "GO:0005515",
        "DNA-Protein": "GO:0005515"
    }
}

#####################################################################################################


npinterv4_ncid_go_terms = npinterv4_ncid.copy()

for index, npinterv4_ncid_go_terms_uniprot_row in npinterv4_ncid_go_terms.iterrows():
    
    list_tags = set(npinterv4_ncid_go_terms_uniprot_row["tag"].split(";"))

    list_level = set(npinterv4_ncid_go_terms_uniprot_row["level"].split(";"))

    list_go_criteria = list_tags | list_level
    
    mf_false = True

    go_terms = set()

    for go_criteria in list_go_criteria:
        go = manually_mapped_go_terms["bp_only"].get(go_criteria)
        if go is not None:
            go_terms.add(go)
        go =  manually_mapped_go_terms["bp_mf"].get(go_criteria)
        if go is not None:
            go_terms.add(go)
            mf_false = False      

    go_terms.add("GO:0034660")

    if mf_false == True:
        go_terms.add("GO:0003674")
    
    go_terms = ";".join(go_terms)

    npinterv4_ncid_go_terms.loc[index, "go_terms"] = go_terms
    
npinterv4_ncid_go_terms

,ncID,ncType,reference,ncID_ensembl_code,ncID_rnacentral_code,tag,level,go_terms,taxonomy
3,NONHSAG040596; NONHSAG040596; NONHSAG040596; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,9018369; 22522162; 15201869;15994294;17671421;...,ENSG00000249352,URS00004E902D,regulatory;promoter as action site;regulatory;...,RNA-RNA;RNA-RNA;RNA-Protein;DNA-TF;RNA-Protein...,GO:0010468;GO:0040033;GO:0003723;GO:0034660;GO...,9606
24,NONHSAG048195; NONHSAG048195; NONHSAG048195; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,25531890; 24164894;22955616; 25301781; 2384659...,ENSG00000243107,URS0000539BDF,miRNA target interaction;RNA-RNA interaction;n...,RNA-RNA;RNA-Protein;RNA-RNA,GO:0010586;GO:0035198;GO:0003723;GO:0034660;GO...,9606
25,NONHSAG048720; NONHSAG048720; NONHSAG048720; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,25531890; 25301781; 24332178; -; 23023293; 263...,ENSG00000226770,URS0000477DCE,miRNA target interaction;RNA-RNA interaction;n...,RNA-RNA;RNA-Protein,GO:0010586;GO:0010467;GO:0035198;GO:0003723;GO...,9606
28,NONHSAG048153; NONHSAG048153; NONHSAG048153; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,25531890; 25301781; -; 23023293; 26321680; 280...,ENSG00000233420,URS00003A4444,miRNA target interaction;RNA-RNA interaction;n...,RNA-RNA;RNA-Protein,GO:0010586;GO:0010467;GO:0035198;GO:0003723;GO...,9606
29,NONHSAG019101; NONHSAG019101; NONHSAG019101; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,25531890; 25531890; 25301781; 25301781; -; -; ...,ENSG00000235560,URS000028AB2B,miRNA target interaction;RNA-RNA interaction;m...,RNA-RNA;RNA-RNA;RNA-Protein;RNA-Protein;RNA-RN...,GO:0010586;GO:0035198;GO:0003723;GO:0034660;GO...,9606
...,...,...,...,...,...,...,...,...,...
1100453,ENSG00000199787,snoRNA,27184080,ENSG00000199787,URS000063D36F,RNA-RNA interaction,RNA-RNA,GO:0003723;GO:0034660,9606
1100455,ENSG00000263764,snoRNA,27184080,ENSG00000263764,URS000063F175,RNA-RNA interaction,RNA-RNA,GO:0003723;GO:0034660,9606
1100456,ENSG00000208892,snoRNA,27184080,ENSG00000208892,URS00006276F4,RNA-RNA interaction,RNA-RNA,GO:0003723;GO:0034660,9606
1100460,ENSG00000200753,snoRNA,27184080,ENSG00000200753,URS000006D2A0,RNA-RNA interaction,RNA-RNA,GO:0003723;GO:0034660,9606
1100515,MI0019145; MI0019145,miRNA; miRNA,23622248; 23622248,ENSG00000283146,URS000075B121,RNA-RNA interaction,RNA-RNA,GO:0003723;GO:0034660,9606

In [133]:
npinterv4_ncid_go_terms["go_terms"] = npinterv4_ncid_go_terms["go_terms"].apply(lambda x: x.split(";"))
npinterv4_ncid_go_terms = npinterv4_ncid_go_terms.explode('go_terms')
npinterv4_ncid_go_terms

,ncID,ncType,reference,ncID_ensembl_code,ncID_rnacentral_code,tag,level,go_terms,taxonomy
3,NONHSAG040596; NONHSAG040596; NONHSAG040596; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,9018369; 22522162; 15201869;15994294;17671421;...,ENSG00000249352,URS00004E902D,regulatory;promoter as action site;regulatory;...,RNA-RNA;RNA-RNA;RNA-Protein;DNA-TF;RNA-Protein...,GO:0010468,9606
3,NONHSAG040596; NONHSAG040596; NONHSAG040596; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,9018369; 22522162; 15201869;15994294;17671421;...,ENSG00000249352,URS00004E902D,regulatory;promoter as action site;regulatory;...,RNA-RNA;RNA-RNA;RNA-Protein;DNA-TF;RNA-Protein...,GO:0040033,9606
3,NONHSAG040596; NONHSAG040596; NONHSAG040596; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,9018369; 22522162; 15201869;15994294;17671421;...,ENSG00000249352,URS00004E902D,regulatory;promoter as action site;regulatory;...,RNA-RNA;RNA-RNA;RNA-Protein;DNA-TF;RNA-Protein...,GO:0003723,9606
3,NONHSAG040596; NONHSAG040596; NONHSAG040596; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,9018369; 22522162; 15201869;15994294;17671421;...,ENSG00000249352,URS00004E902D,regulatory;promoter as action site;regulatory;...,RNA-RNA;RNA-RNA;RNA-Protein;DNA-TF;RNA-Protein...,GO:0034660,9606
3,NONHSAG040596; NONHSAG040596; NONHSAG040596; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,9018369; 22522162; 15201869;15994294;17671421;...,ENSG00000249352,URS00004E902D,regulatory;promoter as action site;regulatory;...,RNA-RNA;RNA-RNA;RNA-Protein;DNA-TF;RNA-Protein...,GO:0005515,9606
...,...,...,...,...,...,...,...,...,...
1100456,ENSG00000208892,snoRNA,27184080,ENSG00000208892,URS00006276F4,RNA-RNA interaction,RNA-RNA,GO:0034660,9606
1100460,ENSG00000200753,snoRNA,27184080,ENSG00000200753,URS000006D2A0,RNA-RNA interaction,RNA-RNA,GO:0003723,9606
1100460,ENSG00000200753,snoRNA,27184080,ENSG00000200753,URS000006D2A0,RNA-RNA interaction,RNA-RNA,GO:0034660,9606
1100515,MI0019145; MI0019145,miRNA; miRNA,23622248; 23622248,ENSG00000283146,URS000075B121,RNA-RNA interaction,RNA-RNA,GO:0003723,9606
1100515,MI0019145; MI0019145,miRNA; miRNA,23622248; 23622248,ENSG00000283146,URS000075B121,RNA-RNA interaction,RNA-RNA,GO:0034660,9606

In [134]:
### Drop all rows, which already are annotated

In [135]:
index_list_coocurrence_nc = np.in1d(np.array(npinterv4_ncid_go_terms["ncID_ensembl_code"]), list(set(npinterv4_ncid_go_terms["ncID_ensembl_code"]) & set(np.unique(gaf[1])))).nonzero()[0]
index_list_coocurrence_nc

array([], dtype=int64)

In [136]:
len(index_list_coocurrence_nc)

0

In [137]:
npinterv4_ncid_go_terms.drop(index_list_coocurrence_nc, inplace=True)
npinterv4_ncid_go_terms

,ncID,ncType,reference,ncID_ensembl_code,ncID_rnacentral_code,tag,level,go_terms,taxonomy
3,NONHSAG040596; NONHSAG040596; NONHSAG040596; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,9018369; 22522162; 15201869;15994294;17671421;...,ENSG00000249352,URS00004E902D,regulatory;promoter as action site;regulatory;...,RNA-RNA;RNA-RNA;RNA-Protein;DNA-TF;RNA-Protein...,GO:0010468,9606
3,NONHSAG040596; NONHSAG040596; NONHSAG040596; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,9018369; 22522162; 15201869;15994294;17671421;...,ENSG00000249352,URS00004E902D,regulatory;promoter as action site;regulatory;...,RNA-RNA;RNA-RNA;RNA-Protein;DNA-TF;RNA-Protein...,GO:0040033,9606
3,NONHSAG040596; NONHSAG040596; NONHSAG040596; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,9018369; 22522162; 15201869;15994294;17671421;...,ENSG00000249352,URS00004E902D,regulatory;promoter as action site;regulatory;...,RNA-RNA;RNA-RNA;RNA-Protein;DNA-TF;RNA-Protein...,GO:0003723,9606
3,NONHSAG040596; NONHSAG040596; NONHSAG040596; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,9018369; 22522162; 15201869;15994294;17671421;...,ENSG00000249352,URS00004E902D,regulatory;promoter as action site;regulatory;...,RNA-RNA;RNA-RNA;RNA-Protein;DNA-TF;RNA-Protein...,GO:0034660,9606
3,NONHSAG040596; NONHSAG040596; NONHSAG040596; N...,lncRNA; lncRNA; lncRNA; lncRNA; lncRNA; lncRNA...,9018369; 22522162; 15201869;15994294;17671421;...,ENSG00000249352,URS00004E902D,regulatory;promoter as action site;regulatory;...,RNA-RNA;RNA-RNA;RNA-Protein;DNA-TF;RNA-Protein...,GO:0005515,9606
...,...,...,...,...,...,...,...,...,...
1100456,ENSG00000208892,snoRNA,27184080,ENSG00000208892,URS00006276F4,RNA-RNA interaction,RNA-RNA,GO:0034660,9606
1100460,ENSG00000200753,snoRNA,27184080,ENSG00000200753,URS000006D2A0,RNA-RNA interaction,RNA-RNA,GO:0003723,9606
1100460,ENSG00000200753,snoRNA,27184080,ENSG00000200753,URS000006D2A0,RNA-RNA interaction,RNA-RNA,GO:0034660,9606
1100515,MI0019145; MI0019145,miRNA; miRNA,23622248; 23622248,ENSG00000283146,URS000075B121,RNA-RNA interaction,RNA-RNA,GO:0003723,9606
1100515,MI0019145; MI0019145,miRNA; miRNA,23622248; 23622248,ENSG00000283146,URS000075B121,RNA-RNA interaction,RNA-RNA,GO:0034660,9606

#### Save file

In [138]:
npinterv4_ncid_go_terms_df = pd.DataFrame({
    0: ["NPInter"] * len(npinterv4_ncid_go_terms),
    1: npinterv4_ncid_go_terms["ncID_ensembl_code"],
    2: list(npinterv4_ncid_go_terms.join(ensembl_gene_gene_name.set_index("Gene stable ID"), on="ncID_ensembl_code")["Gene name"].astype("str")),
    3: ["enables"]  * len(npinterv4_ncid_go_terms),
    4: npinterv4_ncid_go_terms["go_terms"],
    5: ["GO_REF:0000001"] * len(npinterv4_ncid_go_terms),
    6: ["EXP"] * len(npinterv4_ncid_go_terms),
    7: ["NPInter"] * len(npinterv4_ncid_go_terms),
    8: ["P" if obodag[go_term].namespace == "biological_process" else "F" if obodag[go_term].namespace == "molecular_function" else "C" for go_term in npinterv4_ncid_go_terms["go_terms"]], 
    9: [obodag[go_term].name for go_term in npinterv4_ncid_go_terms["go_terms"]],
    10: list(npinterv4_ncid_go_terms.join(ensembl_gene_gene_name.set_index("Gene stable ID"), on="ncID_ensembl_code")["Gene name"].astype("str")),
    11: ["ncRNA"] * len(npinterv4_ncid_go_terms),
    12: ["taxon:9606"] * len(npinterv4_ncid_go_terms),
    13: [20220215] * len(npinterv4_ncid_go_terms),
    14: ["NPInter"] * len(npinterv4_ncid_go_terms),
    15: [np.nan] * len(npinterv4_ncid_go_terms),
    16: [np.nan] * len(npinterv4_ncid_go_terms)
})

npinterv4_ncid_go_terms_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
3,NPInter,ENSG00000249352,LINC02198,enables,GO:0010468,GO_REF:0000001,EXP,NPInter,P,regulation of gene expression,LINC02198,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
3,NPInter,ENSG00000249352,LINC02198,enables,GO:0040033,GO_REF:0000001,EXP,NPInter,P,"negative regulation of translation, ncRNA-medi...",LINC02198,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
3,NPInter,ENSG00000249352,LINC02198,enables,GO:0003723,GO_REF:0000001,EXP,NPInter,F,RNA binding,LINC02198,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
3,NPInter,ENSG00000249352,LINC02198,enables,GO:0034660,GO_REF:0000001,EXP,NPInter,P,ncRNA metabolic process,LINC02198,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
3,NPInter,ENSG00000249352,LINC02198,enables,GO:0005515,GO_REF:0000001,EXP,NPInter,F,protein binding,LINC02198,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1100456,NPInter,ENSG00000208892,SNORA49,enables,GO:0034660,GO_REF:0000001,EXP,NPInter,P,ncRNA metabolic process,SNORA49,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
1100460,NPInter,ENSG00000200753,nan,enables,GO:0003723,GO_REF:0000001,EXP,NPInter,F,RNA binding,nan,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
1100460,NPInter,ENSG00000200753,nan,enables,GO:0034660,GO_REF:0000001,EXP,NPInter,P,ncRNA metabolic process,nan,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
1100515,NPInter,ENSG00000283146,MIR548AU,enables,GO:0003723,GO_REF:0000001,EXP,NPInter,F,RNA binding,MIR548AU,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
1100515,NPInter,ENSG00000283146,MIR548AU,enables,GO:0034660,GO_REF:0000001,EXP,NPInter,P,ncRNA metabolic process,MIR548AU,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN

In [139]:
from itertools import islice
with open('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human.gaf', "r") as myfile:
    head = list(islice(myfile, 41))
head

['!gaf-version: 2.2\n',
 '!\n',
 '!generated-by: GOC\n',
 '!\n',
 '!date-generated: 2022-01-14T16:45\n',
 '!\n',
 '!Header from source association file:\n',
 '!=================================\n',
 '!\n',
 '!generated-by: GOC\n',
 '!\n',
 '!date-generated: 2022-01-14T04:41\n',
 '!\n',
 '!Header from goa_human source association file:\n',
 '!=================================\n',
 '!\n',
 '!The set of protein accessions included in this file is based on UniProt reference proteomes, which provide one protein per gene.\n',
 '!They include the protein sequences annotated in Swiss-Prot or the longest TrEMBL transcript if there is no Swiss-Prot record.\n',
 '!If a particular protein accession is not annotated with GO, then it will not appear in this file.\n',
 '!\n',
 '!Note that the annotation set in this file is filtered in order to reduce redundancy; the full, unfiltered set can be found in\n',
 '!ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gz\n',
 '!\n',
 '!date-generated: 2021-11-08 15:48\n',
 '!generated-by: UniProt\n',
 '!go-version: http://purl.obolibrary.org/obo/go/releases/2021-11-06/extensions/go-plus.owl\n',
 '!\n',
 '!=================================\n',
 '!\n',
 '!Header copied from paint_goa_human_valid.gaf\n',
 '!=================================\n',
 '!Created on Sun Jan  2 19:01:56 2022.\n',
 '!generated-by: PANTHER\n',
 '!date-generated: 2022-01-02\n',
 '!PANTHER version: v.15.0.\n',
 '!GO version: 2021-11-16.\n',
 '!\n',
 '!=================================\n',
 '!\n',
 '!Documentation about this header can be found here: https://github.com/geneontology/go-site/blob/master/docs/gaf_validation.md\n',
 '!\n']

In [140]:
# always remember, use files in a with statement
with open('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_npinter_nc_ensembl_gene_mapping.gaf', "w") as f2:
    for item in head:
        f2.write(item)

In [141]:
npinterv4_ncid_go_terms_df.to_csv('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_npinter_nc_ensembl_gene_mapping.gaf', mode="a", sep="\t", header=False, index=False)

### tarID GO Retrievement

In [23]:
npinterv4_tarid = npinterv4.copy()
npinterv4_tarid

,interID,ncName,ncID,ncType,tarName,tarID,tarType,interDescription,experiment,reference,organism,tissueOrCell,tag,class,level,datasource,ncID_rnacentral_code,ncID_ensembl_code
3,ncRI-40000004,7SK,NONHSAG040596,lncRNA,MYC,NM_002467,protein,Electrophoretic mobility shift experiment indi...,EMSA,9018369,Homo sapiens,-,regulatory;promoter as action site,regulatory,RNA-RNA,Literature mining,URS00004E902D,ENSG00000249352
4,ncRI-40000005,7SK,NONHSAG040596,lncRNA,ABO,NM_020469,protein,Promoters pU6 and p7SK proved to express high ...,-,22522162,Homo sapiens,-,regulatory,regulatory,RNA-RNA,Literature mining,URS00004E902D,ENSG00000249352
5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,15201869;15994294;17671421;20675720;20926576;1...,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352
6,ncRI-40000007,7SK,NONHSAG040596,lncRNA,Oct1,P20263,protein,PTF and Oct-1 enhance transcription from the 7...,-,1535687,Homo sapiens,-,ncRNA is regulated,regulatory,DNA-TF,Literature mining,URS00004E902D,ENSG00000249352
7,ncRI-40000008,7SK,NONHSAG040596,lncRNA,Tat,P17735,protein,Tat efficiently replaces HEXIM1 on the 7SK snR...,-,20976203;20471949,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1100531,ncRI-41100533,hsa-miR-151b,MI0003772,miRNA,NUFIP2,ENSG00000108256,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000075C169,ENSG00000265154
1100532,ncRI-41100534,hsa-miR-151b,MI0003772,miRNA,SLC15A4,ENSG00000139370,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000075C169,ENSG00000265154
1100533,ncRI-41100535,hsa-miR-151b,MI0003772,miRNA,TBC1D10B,ENSG00000169221,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000075C169,ENSG00000265154
1100534,ncRI-41100536,hsa-miR-548d-5p,MI0003671,miRNA,HDLBP,ENSG00000115677,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS0000759C79,ENSG00000263690
1100535,ncRI-41100537,hsa-miR-548d-5p,MI0003671,miRNA,ZMYND8,ENSG00000101040,mRNA,RNA-RNA interaction from RISE database,CLASH,23622248,Homo sapiens,HEK293,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS0000759C79,ENSG00000263690

In [24]:
npinterv4_tarid = npinterv4_tarid.join(df_mapping_file_ncRNA_rna_central_ensembl.set_index("tar_ncRNA_code"), on="tarID")
npinterv4_tarid = npinterv4_tarid[~npinterv4_tarid["ensembl_code"].isnull()]
npinterv4_tarid.rename(columns={'rnacentral_idcode':'tarID_rnacentral_code', 'ensembl_code':'tarID_ensembl_code'}, inplace=True)
npinterv4_tarid = npinterv4_tarid.drop_duplicates()
npinterv4_tarid = npinterv4_tarid.reset_index()
npinterv4_tarid

,index,interID,ncName,ncID,ncType,tarName,tarID,tarType,interDescription,experiment,...,organism,tissueOrCell,tag,class,level,datasource,ncID_rnacentral_code,ncID_ensembl_code,tarID_rnacentral_code,tarID_ensembl_code
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834
1,7,ncRI-40000008,7SK,NONHSAG040596,lncRNA,Tat,P17735,protein,Tat efficiently replaces HEXIM1 on the 7SK snR...,-,...,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000198650
2,8,ncRI-40000009,7SK,NONHSAG040596,lncRNA,CDK9,P50750,protein,Northern hybridization was performed to confir...,Northern Blot,...,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000136807
3,9,ncRI-40000010,7SK,NONHSAG040596,lncRNA,PPP1CA,P62136,protein,PP2B and PP1alpha cooperatively disrupt 7SK sn...,-,...,Homo sapiens,-,regulatory,regulatory,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000172531
4,10,ncRI-40000011,7SK,NONHSAG040596,lncRNA,PP2B,P62140,protein,PP2B and PP1alpha cooperatively disrupt 7SK sn...,-,...,Homo sapiens,-,regulatory,regulatory,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000213639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487273,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,Homo sapiens,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6AE6,ENSG00000255717
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,Homo sapiens,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717
487275,1100458,ncRI-41100460,SNORD117,ENSG00000266295,snoRNA,SNORA5C,ENSG00000201772,snoRNA,RNA-RNA interaction from RISE database,LIGRseq,...,Homo sapiens,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS00002F13BD,ENSG00000266295,URS000072157F,ENSG00000201772
487276,1100459,ncRI-41100461,U6,ENSG00000278140,snoRNA,SNORA79,ENSG00000222489,snRNA,RNA-RNA interaction from RISE database,LIGRseq,...,Homo sapiens,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS0000671B81,ENSG00000278140,URS0000704142,ENSG00000222489
487277,1100460,ncRI-41100462,SNORD56,ENSG00000200753,snoRNA,SNORA7B,ENSG00000207088,snoRNA,RNA-RNA interaction from RISE database,LIGRseq,...,Homo sapiens,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000006D2A0,ENSG00000200753,URS00006F6999,ENSG00000207088

In [25]:
len(set(npinterv4_tarid["tarID_ensembl_code"]))

2068

In [26]:
len(set(npinterv4_tarid["ncID_ensembl_code"]) & set(npinterv4_tarid["tarID_ensembl_code"]))

594

#### Tar-ID GO-Terms Mapping

In [27]:
npinterv4_tarid_go_terms = npinterv4_tarid.copy()
npinterv4_tarid_go_terms

,index,interID,ncName,ncID,ncType,tarName,tarID,tarType,interDescription,experiment,...,organism,tissueOrCell,tag,class,level,datasource,ncID_rnacentral_code,ncID_ensembl_code,tarID_rnacentral_code,tarID_ensembl_code
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834
1,7,ncRI-40000008,7SK,NONHSAG040596,lncRNA,Tat,P17735,protein,Tat efficiently replaces HEXIM1 on the 7SK snR...,-,...,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000198650
2,8,ncRI-40000009,7SK,NONHSAG040596,lncRNA,CDK9,P50750,protein,Northern hybridization was performed to confir...,Northern Blot,...,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000136807
3,9,ncRI-40000010,7SK,NONHSAG040596,lncRNA,PPP1CA,P62136,protein,PP2B and PP1alpha cooperatively disrupt 7SK sn...,-,...,Homo sapiens,-,regulatory,regulatory,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000172531
4,10,ncRI-40000011,7SK,NONHSAG040596,lncRNA,PP2B,P62140,protein,PP2B and PP1alpha cooperatively disrupt 7SK sn...,-,...,Homo sapiens,-,regulatory,regulatory,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000213639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487273,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,Homo sapiens,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6AE6,ENSG00000255717
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,Homo sapiens,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717
487275,1100458,ncRI-41100460,SNORD117,ENSG00000266295,snoRNA,SNORA5C,ENSG00000201772,snoRNA,RNA-RNA interaction from RISE database,LIGRseq,...,Homo sapiens,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS00002F13BD,ENSG00000266295,URS000072157F,ENSG00000201772
487276,1100459,ncRI-41100461,U6,ENSG00000278140,snoRNA,SNORA79,ENSG00000222489,snRNA,RNA-RNA interaction from RISE database,LIGRseq,...,Homo sapiens,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS0000671B81,ENSG00000278140,URS0000704142,ENSG00000222489
487277,1100460,ncRI-41100462,SNORD56,ENSG00000200753,snoRNA,SNORA7B,ENSG00000207088,snoRNA,RNA-RNA interaction from RISE database,LIGRseq,...,Homo sapiens,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000006D2A0,ENSG00000200753,URS00006F6999,ENSG00000207088

In [28]:
len(np.unique(npinterv4_tarid_go_terms["tarID_ensembl_code"]))

2068

#### V1 - Target of target is target - VERY SLOW

In [65]:
#V1 Target of target is target
go_terms_npinterv4_tarid_go_terms = {}

for unique_tarid in tqdm(np.unique(npinterv4_tarid_go_terms["tarID_ensembl_code"])):
        
    tarID_ensembl_codes = set()
    tarID_ensembl_codes.add(unique_tarid)
    ncRNA_tar_interactions_old = set([unique_tarid])
    further_ncRNA_tar_interaction = True
    go_terms = set()
    
    print(unique_tarid)

    while further_ncRNA_tar_interaction:
        ncRNA_tar_interactions = set()
        for ncRNA_tar_interaction_old in ncRNA_tar_interactions_old:
            ncRNA_tar_interactions =  ncRNA_tar_interactions | set(np.unique(npinterv4_tarid_go_terms[npinterv4_tarid_go_terms["ncID_ensembl_code"] == ncRNA_tar_interaction_old]["tarID_ensembl_code"]))
        if len(ncRNA_tar_interactions - tarID_ensembl_codes) >= 1:
            print("hjsdghjag")
            ncRNA_tar_interactions_old = ncRNA_tar_interactions 
            tarID_ensembl_codes = tarID_ensembl_codes | set(ncRNA_tar_interactions)
        else:
            further_ncRNA_tar_interaction = False
            
    for tarID_ensembl_code in tarID_ensembl_codes:
        go_terms = go_terms | set(gaf[gaf[1] == tarID_ensembl_code][4])
    if len(go_terms) > 0:
        go_terms_npinterv4_tarid_go_terms[unique_tarid] = list(go_terms)
    else:
        go_terms_npinterv4_tarid_go_terms[unique_tarid] = np.nan

  0%|          | 2/2068 [00:00<02:21, 14.60it/s]

ENSG00000001631
ENSG00000003756
ENSG00000004478
ENSG00000004487

  0%|          | 8/2068 [00:00<02:09, 15.85it/s]

ENSG00000004534
ENSG00000004700
ENSG00000005007
ENSG00000005421
ENSG00000006712

  1%|          | 12/2068 [00:00<02:08, 16.04it/s]

ENSG00000006744
ENSG00000007372
ENSG00000007392
ENSG00000007908

  1%|          | 16/2068 [00:01<02:11, 15.65it/s]

ENSG00000011243
ENSG00000011304
ENSG00000012048
ENSG00000015479
ENSG00000019549

  1%|          | 22/2068 [00:01<02:07, 16.05it/s]

ENSG00000019991
ENSG00000020633
ENSG00000021776
ENSG00000023608
ENSG00000026025

  1%|▏         | 26/2068 [00:01<02:07, 16.08it/s]

ENSG00000028137
ENSG00000029363
ENSG00000029993
ENSG00000030582

  1%|▏         | 30/2068 [00:01<02:07, 16.02it/s]

ENSG00000037474
ENSG00000039123
ENSG00000039650
ENSG00000044574
ENSG00000047346

  2%|▏         | 36/2068 [00:02<02:06, 16.02it/s]

ENSG00000047410
ENSG00000048052
ENSG00000048828
ENSG00000051180
ENSG00000053372

  2%|▏         | 40/2068 [00:02<02:07, 15.85it/s]

ENSG00000054118
ENSG00000055917
ENSG00000056972
ENSG00000058085
ENSG00000058673

  2%|▏         | 46/2068 [00:02<02:04, 16.22it/s]

ENSG00000060138
ENSG00000060339
ENSG00000060688
ENSG00000062822
ENSG00000063244

  2%|▏         | 50/2068 [00:03<02:04, 16.15it/s]

ENSG00000064012
ENSG00000064300
ENSG00000064607
ENSG00000064703
ENSG00000065526

  3%|▎         | 56/2068 [00:03<02:03, 16.34it/s]

ENSG00000065978
ENSG00000066044
ENSG00000066135
ENSG00000067596
ENSG00000067900

  3%|▎         | 60/2068 [00:03<02:04, 16.10it/s]

ENSG00000068394
ENSG00000070756
ENSG00000071082
ENSG00000071243

  3%|▎         | 64/2068 [00:03<02:03, 16.27it/s]

ENSG00000071626
ENSG00000071794
ENSG00000071859
ENSG00000071894
ENSG00000072501

  3%|▎         | 70/2068 [00:04<02:03, 16.18it/s]

ENSG00000073111
ENSG00000073282
ENSG00000073792
ENSG00000074211
ENSG00000074266

  4%|▎         | 74/2068 [00:04<02:02, 16.27it/s]

ENSG00000074356
ENSG00000075292
ENSG00000075618
ENSG00000075856

  4%|▍         | 78/2068 [00:04<02:02, 16.29it/s]

ENSG00000076003
ENSG00000076924
ENSG00000077235
ENSG00000077312
ENSG00000077348

  4%|▍         | 84/2068 [00:05<02:03, 16.09it/s]

ENSG00000079246
ENSG00000079739
ENSG00000079785
ENSG00000080503
ENSG00000082068

  4%|▍         | 88/2068 [00:05<02:01, 16.23it/s]

ENSG00000082153
ENSG00000082516
ENSG00000082898
ENSG00000083312

  4%|▍         | 92/2068 [00:05<02:01, 16.32it/s]

ENSG00000083520
ENSG00000083896
ENSG00000084463
ENSG00000085117
ENSG00000085662

  5%|▍         | 98/2068 [00:06<02:00, 16.35it/s]

ENSG00000085872
ENSG00000086475
ENSG00000086589
ENSG00000087087
ENSG00000087088

  5%|▍         | 102/2068 [00:06<02:01, 16.23it/s]

ENSG00000087152
ENSG00000087245
ENSG00000087302
ENSG00000087365
ENSG00000087470

  5%|▌         | 108/2068 [00:06<01:59, 16.37it/s]

ENSG00000088247
ENSG00000088305
ENSG00000088826
ENSG00000088930
ENSG00000088986

  5%|▌         | 112/2068 [00:06<02:00, 16.22it/s]

ENSG00000089220
ENSG00000089250
ENSG00000089280
ENSG00000089737
ENSG00000090861

  6%|▌         | 118/2068 [00:07<02:00, 16.21it/s]

ENSG00000090889
ENSG00000090905
ENSG00000091831
ENSG00000092199
ENSG00000092201

  6%|▌         | 122/2068 [00:07<01:59, 16.24it/s]

ENSG00000092847
ENSG00000095002
ENSG00000095015
ENSG00000095380

  6%|▌         | 126/2068 [00:07<01:59, 16.32it/s]

ENSG00000095564
ENSG00000095752
ENSG00000096150
ENSG00000096401
ENSG00000096717

  6%|▋         | 132/2068 [00:08<01:58, 16.32it/s]

ENSG00000096746
ENSG00000099622
ENSG00000099783
ENSG00000099995
ENSG00000100109

  7%|▋         | 136/2068 [00:08<01:58, 16.33it/s]

ENSG00000100220
ENSG00000100227
ENSG00000100234
ENSG00000100297
ENSG00000100307

  7%|▋         | 140/2068 [00:08<01:59, 16.15it/s]

ENSG00000100316
ENSG00000100320
ENSG00000100353
ENSG00000100393

  7%|▋         | 146/2068 [00:09<01:58, 16.21it/s]

ENSG00000100403
ENSG00000100603
ENSG00000100644
ENSG00000100722
ENSG00000100813

  7%|▋         | 150/2068 [00:09<02:00, 15.90it/s]

ENSG00000100823
ENSG00000100836
ENSG00000100941
ENSG00000100985
ENSG00000101138

  8%|▊         | 156/2068 [00:09<01:59, 15.98it/s]

ENSG00000101161
ENSG00000101197
ENSG00000101199
ENSG00000101230
ENSG00000101266

  8%|▊         | 160/2068 [00:09<01:58, 16.09it/s]

ENSG00000101343
ENSG00000101367
ENSG00000101412
ENSG00000101413
ENSG00000101444

  8%|▊         | 166/2068 [00:10<01:57, 16.22it/s]

ENSG00000101489
ENSG00000101654
ENSG00000101811
ENSG00000101871
ENSG00000101966

  8%|▊         | 170/2068 [00:10<01:57, 16.21it/s]

ENSG00000102054
ENSG00000102081
ENSG00000102103
ENSG00000102974

  8%|▊         | 174/2068 [00:10<01:57, 16.12it/s]

ENSG00000103034
ENSG00000103275
ENSG00000103549
ENSG00000104321
ENSG00000104356

  9%|▊         | 180/2068 [00:11<01:56, 16.25it/s]

ENSG00000104419
ENSG00000104738
ENSG00000104824
ENSG00000104852
ENSG00000104881

  9%|▉         | 184/2068 [00:11<01:59, 15.71it/s]

ENSG00000104885
ENSG00000104897
ENSG00000105011
ENSG00000105127
ENSG00000105171

  9%|▉         | 190/2068 [00:11<01:58, 15.88it/s]

ENSG00000105202
ENSG00000105221
ENSG00000105323
ENSG00000105327
ENSG00000105447

  9%|▉         | 194/2068 [00:12<01:57, 15.97it/s]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 18%|█▊        | 368/2068 [05:01<9:42:00, 20.54s/it]

ENSG00000130707
ENSG00000130725
ENSG00000130726
ENSG00000130811
ENSG00000130816

 18%|█▊        | 372/2068 [05:01<4:45:24, 10.10s/it]

ENSG00000130826
ENSG00000130985
ENSG00000131013
ENSG00000131023

 18%|█▊        | 376/2068 [05:01<2:20:24,  4.98s/it]

ENSG00000131051
ENSG00000131467
ENSG00000131469
ENSG00000131747
ENSG00000131876

 18%|█▊        | 382/2068 [05:02<49:08,  1.75s/it]

ENSG00000131914
ENSG00000131981
ENSG00000132153
ENSG00000132341
ENSG00000132383

 19%|█▊        | 386/2068 [05:02<24:54,  1.13it/s]

ENSG00000132463
ENSG00000132485
ENSG00000132507
ENSG00000132646

 19%|█▉        | 390/2068 [05:02<13:02,  2.14it/s]

ENSG00000132780
ENSG00000132792
ENSG00000132970
ENSG00000133121
ENSG00000133226

 19%|█▉        | 396/2068 [05:03<05:35,  4.98it/s]

ENSG00000133703
ENSG00000133740
ENSG00000133858
ENSG00000134013
ENSG00000134186

 19%|█▉        | 400/2068 [05:03<03:35,  7.73it/s]

ENSG00000134283
ENSG00000134287
ENSG00000134323
ENSG00000134371
ENSG00000134419

 20%|█▉        | 406/2068 [05:03<02:21, 11.78it/s]

ENSG00000134453
ENSG00000134698
ENSG00000134748
ENSG00000135069
ENSG00000135097

 20%|█▉        | 410/2068 [05:04<02:01, 13.65it/s]

ENSG00000135218
ENSG00000135316
ENSG00000135486
ENSG00000135679
ENSG00000135870

 20%|██        | 416/2068 [05:04<01:47, 15.31it/s]

ENSG00000136231
ENSG00000136270
ENSG00000136450
ENSG00000136527
ENSG00000136542

 20%|██        | 420/2068 [05:04<01:44, 15.78it/s]

ENSG00000136709
ENSG00000136807
ENSG00000136810
ENSG00000136813
ENSG00000136937

 21%|██        | 426/2068 [05:05<01:42, 16.02it/s]

ENSG00000136938
ENSG00000136997
ENSG00000137154
ENSG00000137168
ENSG00000137309

 21%|██        | 430/2068 [05:05<01:41, 16.20it/s]

ENSG00000137393
ENSG00000137449
ENSG00000137497
ENSG00000137656

 21%|██        | 434/2068 [05:05<01:40, 16.30it/s]

ENSG00000137752
ENSG00000137776
ENSG00000138279
ENSG00000138336
ENSG00000138385

 21%|██▏       | 440/2068 [05:05<01:40, 16.20it/s]

ENSG00000138398
ENSG00000138413
ENSG00000138668
ENSG00000138772
ENSG00000138795

 21%|██▏       | 444/2068 [05:06<01:40, 16.18it/s]

ENSG00000139343
ENSG00000139546
ENSG00000139636
ENSG00000139687

 22%|██▏       | 448/2068 [05:06<01:39, 16.29it/s]

ENSG00000139746
ENSG00000139793
ENSG00000139842
ENSG00000140259
ENSG00000140319

 22%|██▏       | 454/2068 [05:06<01:39, 16.23it/s]

ENSG00000140350
ENSG00000140505
ENSG00000140525
ENSG00000140718
ENSG00000141425

 22%|██▏       | 458/2068 [05:06<01:39, 16.20it/s]

ENSG00000141448
ENSG00000141510
ENSG00000141543
ENSG00000141646
ENSG00000142192

 22%|██▏       | 464/2068 [05:07<01:39, 16.20it/s]

ENSG00000142515
ENSG00000142534
ENSG00000142546
ENSG00000142864
ENSG00000142937

 23%|██▎       | 468/2068 [05:07<01:38, 16.27it/s]

ENSG00000143190
ENSG00000143321
ENSG00000143368
ENSG00000143578

 23%|██▎       | 472/2068 [05:07<01:37, 16.31it/s]

ENSG00000143621
ENSG00000143727
ENSG00000143799
ENSG00000143889
ENSG00000143977

 23%|██▎       | 478/2068 [05:08<01:37, 16.23it/s]

ENSG00000144028
ENSG00000144713
ENSG00000144852
ENSG00000145075
ENSG00000145216

 23%|██▎       | 482/2068 [05:08<01:37, 16.24it/s]

ENSG00000145365
ENSG00000145425
ENSG00000145833
ENSG00000146648

 24%|██▎       | 486/2068 [05:08<01:37, 16.19it/s]

ENSG00000146674
ENSG00000146834
ENSG00000146963
ENSG00000147140
ENSG00000147274

 24%|██▍       | 492/2068 [05:09<01:37, 16.17it/s]

ENSG00000147403
ENSG00000147604
ENSG00000147649
ENSG00000147677
ENSG00000147852

 24%|██▍       | 496/2068 [05:09<01:36, 16.26it/s]

ENSG00000147883
ENSG00000148303
ENSG00000148516
ENSG00000148688
ENSG00000148700

 24%|██▍       | 502/2068 [05:09<01:36, 16.29it/s]

ENSG00000148773
ENSG00000149136
ENSG00000149273
ENSG00000149532
ENSG00000149658

 24%|██▍       | 506/2068 [05:09<01:35, 16.28it/s]

ENSG00000149925
ENSG00000149948
ENSG00000150093
ENSG00000150316
ENSG00000150459

 25%|██▍       | 512/2068 [05:10<01:35, 16.26it/s]

ENSG00000150593
ENSG00000150907
ENSG00000151892
ENSG00000151923
ENSG00000152192

 25%|██▍       | 516/2068 [05:10<01:35, 16.21it/s]

ENSG00000152464
ENSG00000152601
ENSG00000152795
ENSG00000153147

 25%|██▌       | 520/2068 [05:10<01:34, 16.30it/s]

ENSG00000153187
ENSG00000153922
ENSG00000154473
ENSG00000154736
ENSG00000155816

 25%|██▌       | 526/2068 [05:11<01:35, 16.19it/s]

ENSG00000155827
ENSG00000155858
ENSG00000156076
ENSG00000156427
ENSG00000156482

 26%|██▌       | 530/2068 [05:11<01:34, 16.32it/s]

ENSG00000156502
ENSG00000157110
ENSG00000157764
ENSG00000157837
ENSG00000158019

 26%|██▌       | 536/2068 [05:11<01:34, 16.24it/s]

ENSG00000158545
ENSG00000158773
ENSG00000158859
ENSG00000159140
ENSG00000159217

 26%|██▌       | 540/2068 [05:12<01:34, 16.16it/s]

ENSG00000159346
ENSG00000160201
ENSG00000160633
ENSG00000160710

 26%|██▋       | 544/2068 [05:12<01:33, 16.23it/s]

ENSG00000160712
ENSG00000160752
ENSG00000160789
ENSG00000160917
ENSG00000161526

 27%|██▋       | 550/2068 [05:12<01:34, 16.10it/s]

ENSG00000161547
ENSG00000161813
ENSG00000161970
ENSG00000162231
ENSG00000162385

 27%|██▋       | 554/2068 [05:12<01:34, 16.07it/s]

ENSG00000162664
ENSG00000162692
ENSG00000162711
ENSG00000162775

 27%|██▋       | 558/2068 [05:13<01:33, 16.15it/s]

ENSG00000162924
ENSG00000163161
ENSG00000163191
ENSG00000163597
hjsdghjag
hjsdghjag
hjsdghjag

 27%|██▋       | 558/2068 [05:33<01:33, 16.15it/s]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 27%|██▋       | 563/2068 [09:26<8:25:17, 20.14s/it]

ENSG00000163655
ENSG00000163694
ENSG00000163714
ENSG00000163877
ENSG00000163931

 27%|██▋       | 567/2068 [09:26<3:58:09,  9.52s/it]

ENSG00000163938
ENSG00000163950
ENSG00000163993
ENSG00000164047

 28%|██▊       | 571/2068 [09:27<1:55:01,  4.61s/it]

ENSG00000164091
ENSG00000164104
ENSG00000164109
ENSG00000164111
ENSG00000164167

 28%|██▊       | 577/2068 [09:27<39:51,  1.60s/it]

ENSG00000164252
ENSG00000164305
ENSG00000164362
ENSG00000164548
ENSG00000164587

 28%|██▊       | 581/2068 [09:27<20:12,  1.23it/s]

ENSG00000164690
ENSG00000164778
ENSG00000164867
ENSG00000164902
ENSG00000164924

 28%|██▊       | 587/2068 [09:28<07:53,  3.13it/s]

ENSG00000164938
ENSG00000164944
ENSG00000165119
ENSG00000165732
ENSG00000165795

 29%|██▊       | 591/2068 [09:28<04:37,  5.33it/s]

ENSG00000165819
ENSG00000165934
ENSG00000166197
ENSG00000166508

 29%|██▉       | 595/2068 [09:28<03:01,  8.10it/s]

ENSG00000166949
ENSG00000167005
ENSG00000167081
ENSG00000167088
ENSG00000167323

 29%|██▉       | 601/2068 [09:28<02:01, 12.08it/s]

ENSG00000167721
ENSG00000167920
ENSG00000167978
ENSG00000167986
ENSG00000168002

 29%|██▉       | 605/2068 [09:29<01:45, 13.83it/s]

ENSG00000168036
ENSG00000168066
ENSG00000168267
ENSG00000168394
ENSG00000168438

 30%|██▉       | 611/2068 [09:29<01:34, 15.42it/s]

ENSG00000168496
ENSG00000168564
ENSG00000168610
ENSG00000168743
ENSG00000168769

 30%|██▉       | 615/2068 [09:29<01:32, 15.79it/s]

ENSG00000168883
ENSG00000168906
ENSG00000169035
ENSG00000169045

 30%|██▉       | 619/2068 [09:30<01:30, 16.06it/s]

ENSG00000169083
ENSG00000169554
ENSG00000169564
ENSG00000169567
ENSG00000169813

 30%|███       | 625/2068 [09:30<01:30, 16.01it/s]

ENSG00000169908
ENSG00000170027
ENSG00000170144
ENSG00000170312
ENSG00000170345

 30%|███       | 629/2068 [09:30<01:28, 16.20it/s]

ENSG00000170515
ENSG00000170606
ENSG00000171056
ENSG00000171314
ENSG00000171566

 31%|███       | 635/2068 [09:31<01:28, 16.18it/s]

ENSG00000171791
ENSG00000171862
ENSG00000171863
ENSG00000171960
ENSG00000172009

 31%|███       | 639/2068 [09:31<01:28, 16.20it/s]

ENSG00000172062
ENSG00000172179
ENSG00000172336
ENSG00000172531

 31%|███       | 643/2068 [09:31<01:28, 16.12it/s]

ENSG00000172757
ENSG00000172977
ENSG00000173039
ENSG00000173545
ENSG00000173702

 31%|███▏      | 649/2068 [09:31<01:27, 16.20it/s]

ENSG00000173812
ENSG00000173846
ENSG00000173933
ENSG00000174231
ENSG00000174243

 31%|███▏      | 651/2068 [09:32<01:27, 16.23it/s]

ENSG00000174325
ENSG00000174365
hjsdghjag
hjsdghjag
hjsdghjag

 31%|███▏      | 651/2068 [09:43<01:27, 16.23it/s]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 32%|███▏      | 656/2068 [12:28<5:29:45, 14.01s/it]

ENSG00000174444
ENSG00000174720
ENSG00000175029
ENSG00000175197
ENSG00000175390

 32%|███▏      | 658/2068 [12:28<3:45:36,  9.60s/it]

ENSG00000175467
ENSG00000176102
ENSG00000176124
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 32%|███▏      | 658/2068 [12:43<3:45:36,  9.60s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 32%|███▏      | 660/2068 [17:16<20:07:02, 51.44s/it]

ENSG00000176593
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 32%|███▏      | 665/2068 [20:18<12:57:27, 33.25s/it]

ENSG00000176697
ENSG00000176884
ENSG00000176890
ENSG00000176912
ENSG00000177000

 32%|███▏      | 669/2068 [20:18<6:03:16, 15.58s/it]

ENSG00000177150
ENSG00000177192
ENSG00000177613
ENSG00000177733
ENSG00000177822
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 32%|███▏      | 669/2068 [20:34<6:03:16, 15.58s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 33%|███▎      | 675/2068 [24:40<9:33:55, 24.72s/it]

ENSG00000177885
ENSG00000178585
ENSG00000178691
ENSG00000178718
ENSG00000178950

 33%|███▎      | 679/2068 [24:40<4:39:03, 12.05s/it]

ENSG00000179051
ENSG00000180198
ENSG00000180233
ENSG00000180543
ENSG00000181163

 33%|███▎      | 685/2068 [24:40<1:35:47,  4.16s/it]

ENSG00000181555
ENSG00000182004
ENSG00000182352
ENSG00000182718
ENSG00000182774

 33%|███▎      | 689/2068 [24:41<47:28,  2.07s/it]

ENSG00000182809
ENSG00000182872
ENSG00000182944
ENSG00000183154
ENSG00000183207

 34%|███▎      | 695/2068 [24:41<17:07,  1.34it/s]

ENSG00000183258
ENSG00000183431
ENSG00000183784
ENSG00000183808
ENSG00000184634

 34%|███▍      | 699/2068 [24:41<09:04,  2.51it/s]

ENSG00000184937
ENSG00000185245
ENSG00000185591
ENSG00000186416
ENSG00000186566

 34%|███▍      | 705/2068 [24:42<04:01,  5.65it/s]

ENSG00000186834
ENSG00000187098
ENSG00000187555
ENSG00000187605
ENSG00000187621
hjsdghjag
hjsdghjag

 34%|███▍      | 709/2068 [24:43<06:31,  3.47it/s]

ENSG00000187735
ENSG00000187772
ENSG00000188004
ENSG00000188342

 34%|███▍      | 713/2068 [24:44<03:54,  5.78it/s]

ENSG00000188529
ENSG00000189091
ENSG00000189403
ENSG00000194717
ENSG00000196154

 35%|███▍      | 719/2068 [24:44<02:14, 10.06it/s]

ENSG00000196235
ENSG00000196361
ENSG00000196363
ENSG00000196419
ENSG00000196591

 35%|███▍      | 723/2068 [24:44<01:47, 12.46it/s]

ENSG00000196712
ENSG00000197043
ENSG00000197111
ENSG00000197157
ENSG00000197182
hjsdghjag
hjsdghjag

 35%|███▌      | 725/2068 [24:46<05:17,  4.23it/s]

ENSG00000197568
ENSG00000197934
hjsdghjag

 35%|███▌      | 727/2068 [24:46<05:06,  4.38it/s]

ENSG00000197989
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 35%|███▌      | 732/2068 [27:26<4:45:30, 12.82s/it]

ENSG00000198034
ENSG00000198231
ENSG00000198242
ENSG00000198382
ENSG00000198492
ENSG00000198496
hjsdghjag

 35%|███▌      | 734/2068 [27:27<3:17:28,  8.88s/it]

ENSG00000198563
ENSG00000198590
hjsdghjag

 36%|███▌      | 740/2068 [27:28<1:06:55,  3.02s/it]

ENSG00000198650
ENSG00000198730
ENSG00000198755
ENSG00000198793
ENSG00000198805

 36%|███▌      | 742/2068 [27:28<46:57,  2.12s/it]

ENSG00000198900
ENSG00000198972
hjsdghjag

 36%|███▌      | 744/2068 [27:28<33:55,  1.54s/it]

ENSG00000198973
hjsdghjag
ENSG00000198974
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 36%|███▌      | 744/2068 [27:45<33:55,  1.54s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 36%|███▌      | 746/2068 [32:19<15:29:58, 42.21s/it]

ENSG00000198975
hjsdghjag
ENSG00000198976
ENSG00000198983
hjsdghjag

 36%|███▌      | 748/2068 [32:19<9:49:27, 26.79s/it]

hjsdghjag
ENSG00000198995
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 36%|███▋      | 750/2068 [36:58<22:21:23, 61.06s/it]

ENSG00000198997
hjsdghjag
ENSG00000199001
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 36%|███▋      | 751/2068 [41:42<42:23:55, 115.90s/it]

ENSG00000199005
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 36%|███▋      | 752/2068 [46:22<57:58:45, 158.61s/it]

ENSG00000199012
ENSG00000199015
hjsdghjag
hjsdghjag

 37%|███▋      | 755/2068 [46:23<25:30:00, 69.92s/it]

ENSG00000199017
hjsdghjag
ENSG00000199020
hjsdghjag
hjsdghjag
hjsdghjag

 37%|███▋      | 756/2068 [46:25<19:13:04, 52.73s/it]

ENSG00000199023
hjsdghjag

 37%|███▋      | 757/2068 [46:25<14:10:40, 38.93s/it]

ENSG00000199024
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 37%|███▋      | 759/2068 [50:52<26:30:49, 72.92s/it]

ENSG00000199025
hjsdghjag
ENSG00000199030
hjsdghjag

 37%|███▋      | 760/2068 [50:52<18:55:17, 52.08s/it]

ENSG00000199031
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 37%|███▋      | 762/2068 [55:18<29:15:36, 80.66s/it]

ENSG00000199032
hjsdghjag
ENSG00000199036
ENSG00000199038
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 37%|███▋      | 764/2068 [1:00:00<39:12:28, 108.24s/it]

ENSG00000199043
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 37%|███▋      | 766/2068 [1:04:55<41:15:26, 114.08s/it]

ENSG00000199047
hjsdghjag
ENSG00000199051
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 37%|███▋      | 767/2068 [1:09:42<58:05:29, 160.75s/it]

ENSG00000199053
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 37%|███▋      | 768/2068 [1:12:41<59:55:47, 165.96s/it]

ENSG00000199059
hjsdghjag

 37%|███▋      | 769/2068 [1:12:42<42:51:05, 118.76s/it]

ENSG00000199069
ENSG00000199072
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 37%|███▋      | 771/2068 [1:17:29<46:49:42, 129.98s/it]

ENSG00000199075
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 37%|███▋      | 772/2068 [1:22:24<61:11:16, 169.97s/it]

ENSG00000199077
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 37%|███▋      | 774/2068 [1:27:19<53:07:58, 147.82s/it]

ENSG00000199080
hjsdghjag
ENSG00000199082
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 37%|███▋      | 775/2068 [1:31:59<66:14:23, 184.43s/it]

ENSG00000199085
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 38%|███▊      | 776/2068 [1:36:41<76:07:55, 212.13s/it]

ENSG00000199088
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 38%|███▊      | 779/2068 [1:41:34<46:13:20, 129.09s/it]

ENSG00000199090
ENSG00000199092
hjsdghjag
ENSG00000199095
hjsdghjag
hjsdghjag

 38%|███▊      | 780/2068 [1:41:34<34:58:25, 97.75s/it]

ENSG00000199104
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 38%|███▊      | 783/2068 [1:45:57<28:49:03, 80.73s/it]

ENSG00000199107
ENSG00000199109
ENSG00000199121
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 38%|███▊      | 784/2068 [1:50:54<46:43:08, 130.99s/it]

ENSG00000199122
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 38%|███▊      | 785/2068 [1:55:32<59:50:12, 167.90s/it]

ENSG00000199127
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 38%|███▊      | 786/2068 [1:59:58<68:58:09, 193.67s/it]

ENSG00000199130
hjsdghjag
hjsdghjag
hjsdghjag

 38%|███▊      | 788/2068 [1:59:59<36:04:29, 101.46s/it]

ENSG00000199132
hjsdghjag
ENSG00000199133
hjsdghjag

 38%|███▊      | 789/2068 [1:59:59<25:44:44, 72.47s/it]

ENSG00000199135
hjsdghjag

 38%|███▊      | 791/2068 [2:00:00<12:57:10, 36.52s/it]

ENSG00000199143
hjsdghjag
ENSG00000199145
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 38%|███▊      | 792/2068 [2:04:21<36:25:57, 102.79s/it]

ENSG00000199150
hjsdghjag

 38%|███▊      | 793/2068 [2:04:21<25:38:04, 72.38s/it]

ENSG00000199151
ENSG00000199153
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 38%|███▊      | 795/2068 [2:09:15<37:38:58, 106.47s/it]

ENSG00000199156
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 39%|███▊      | 797/2068 [2:13:55<38:59:43, 110.45s/it]

ENSG00000199157
hjsdghjag
ENSG00000199158
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 39%|███▊      | 798/2068 [2:18:47<56:21:51, 159.77s/it]

ENSG00000199161
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 39%|███▊      | 799/2068 [2:23:35<68:54:42, 195.49s/it]

ENSG00000199165
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 39%|███▊      | 800/2068 [2:28:42<80:03:47, 227.31s/it]

ENSG00000199168
hjsdghjag

 39%|███▊      | 801/2068 [2:28:42<56:51:53, 161.57s/it]

ENSG00000199169
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 39%|███▉      | 803/2068 [2:33:36<49:36:12, 141.16s/it]

ENSG00000199172
hjsdghjag
ENSG00000199177
hjsdghjag

 39%|███▉      | 804/2068 [2:33:36<34:55:03, 99.45s/it]

ENSG00000199179
hjsdghjag
hjsdghjag

 39%|███▉      | 805/2068 [2:33:37<24:35:03, 70.07s/it]

ENSG00000199293
ENSG00000199347
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 39%|███▉      | 809/2068 [2:36:36<16:42:37, 47.78s/it]

ENSG00000199436
ENSG00000199666
ENSG00000199673
ENSG00000200087
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 39%|███▉      | 812/2068 [2:39:30<17:10:30, 49.23s/it]

ENSG00000200156
hjsdghjag
ENSG00000200463
hjsdghjag

 40%|███▉      | 817/2068 [2:39:30<5:09:29, 14.84s/it]

ENSG00000200785
ENSG00000200792
ENSG00000200795
ENSG00000201003
ENSG00000201302
hjsdghjag

 40%|███▉      | 819/2068 [2:39:31<3:25:00,  9.85s/it]

ENSG00000201465
hjsdghjag
ENSG00000201542
ENSG00000201663

 40%|███▉      | 823/2068 [2:39:31<1:34:32,  4.56s/it]

ENSG00000201772
ENSG00000202059
ENSG00000202111
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 40%|███▉      | 823/2068 [2:39:48<1:34:32,  4.56s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 40%|███▉      | 824/2068 [2:44:16<19:31:02, 56.48s/it]

ENSG00000202183
ENSG00000202198
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 40%|███▉      | 826/2068 [2:46:49<21:53:23, 63.45s/it]

ENSG00000202515
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 40%|████      | 829/2068 [2:51:34<23:34:21, 68.49s/it]

ENSG00000202538
ENSG00000202560
ENSG00000202566
hjsdghjag
ENSG00000202569
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 40%|████      | 829/2068 [2:51:49<23:34:21, 68.49s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 40%|████      | 833/2068 [2:55:57<20:46:35, 60.56s/it]

ENSG00000202601
ENSG00000202609
hjsdghjag
ENSG00000203867
ENSG00000203993
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 40%|████      | 833/2068 [2:56:09<20:46:35, 60.56s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 40%|████      | 835/2068 [3:01:03<30:49:25, 90.00s/it]

ENSG00000204054
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 41%|████      | 840/2068 [3:05:49<18:51:58, 55.31s/it]

ENSG00000204217
ENSG00000204371
ENSG00000204387
ENSG00000204388
ENSG00000204560

 41%|████      | 844/2068 [3:05:50<8:45:54, 25.78s/it]

ENSG00000204569
ENSG00000204628
ENSG00000204842
ENSG00000204977

 41%|████      | 848/2068 [3:05:50<4:11:22, 12.36s/it]

ENSG00000205323
ENSG00000205571
ENSG00000205937
ENSG00000206297

 41%|████      | 852/2068 [3:05:50<2:01:59,  6.02s/it]

ENSG00000206344
ENSG00000206376
ENSG00000206394
ENSG00000206486

 41%|████▏     | 854/2068 [3:05:50<1:25:21,  4.22s/it]

ENSG00000206489
ENSG00000206585
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 41%|████▏     | 854/2068 [3:06:00<1:25:21,  4.22s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 42%|████▏     | 859/2068 [3:08:48<5:16:40, 15.72s/it]

ENSG00000206760
ENSG00000206941
ENSG00000207027
ENSG00000207088
ENSG00000207110
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 42%|████▏     | 859/2068 [3:09:01<5:16:40, 15.72s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 42%|████▏     | 860/2068 [3:11:47<15:34:16, 46.40s/it]

ENSG00000207181
ENSG00000207205
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 42%|████▏     | 862/2068 [3:15:13<22:10:52, 66.21s/it]

ENSG00000207340
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 42%|████▏     | 863/2068 [3:18:05<29:16:53, 87.48s/it]

ENSG00000207349
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 42%|████▏     | 864/2068 [3:21:13<36:40:52, 109.68s/it]

ENSG00000207392
ENSG00000207546
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 42%|████▏     | 866/2068 [3:26:01<41:04:19, 123.01s/it]

ENSG00000207547
hjsdghjag

 42%|████▏     | 867/2068 [3:26:01<32:08:45, 96.36s/it]

ENSG00000207548
hjsdghjag
ENSG00000207550
hjsdghjag

 42%|████▏     | 871/2068 [3:26:02<12:47:58, 38.50s/it]

ENSG00000207551
ENSG00000207554
ENSG00000207559
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 42%|████▏     | 871/2068 [3:26:13<12:47:58, 38.50s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 42%|████▏     | 872/2068 [3:30:24<27:48:40, 83.71s/it]

ENSG00000207562
hjsdghjag
hjsdghjag

 42%|████▏     | 873/2068 [3:30:25<21:36:38, 65.10s/it]

ENSG00000207563
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 42%|████▏     | 874/2068 [3:34:52<37:46:54, 113.92s/it]

ENSG00000207568
hjsdghjag

 42%|████▏     | 875/2068 [3:34:52<28:04:48, 84.73s/it]

ENSG00000207569
ENSG00000207571
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 42%|████▏     | 877/2068 [3:39:46<36:44:46, 111.07s/it]

ENSG00000207574
ENSG00000207575
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 43%|████▎     | 879/2068 [3:44:40<41:10:21, 124.66s/it]

ENSG00000207580
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 43%|████▎     | 880/2068 [3:49:30<52:43:46, 159.79s/it]

ENSG00000207581
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 43%|████▎     | 881/2068 [3:53:56<60:46:39, 184.33s/it]

ENSG00000207582
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 43%|████▎     | 884/2068 [3:58:47<40:32:55, 123.29s/it]

ENSG00000207585
ENSG00000207586
hjsdghjag
ENSG00000207587
hjsdghjag

 43%|████▎     | 885/2068 [3:58:48<31:14:48, 95.09s/it]

ENSG00000207588
ENSG00000207589
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 43%|████▎     | 889/2068 [4:03:10<22:54:00, 69.92s/it]

ENSG00000207590
ENSG00000207594
hjsdghjag
ENSG00000207595
hjsdghjag

 43%|████▎     | 890/2068 [4:03:10<18:11:51, 55.61s/it]

ENSG00000207597
ENSG00000207598
hjsdghjag
hjsdghjag

 43%|████▎     | 894/2068 [4:03:11<7:31:32, 23.08s/it]

ENSG00000207599
ENSG00000207600
hjsdghjag
ENSG00000207604
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 43%|████▎     | 897/2068 [4:08:00<15:42:33, 48.30s/it]

ENSG00000207605
ENSG00000207606
ENSG00000207607
hjsdghjag

 43%|████▎     | 898/2068 [4:08:00<12:29:20, 38.43s/it]

ENSG00000207608
ENSG00000207609
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 44%|████▎     | 900/2068 [4:12:38<24:33:02, 75.67s/it]

ENSG00000207611
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 44%|████▎     | 901/2068 [4:17:16<38:13:17, 117.91s/it]

ENSG00000207613
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 44%|████▎     | 902/2068 [4:21:42<49:11:03, 151.86s/it]

ENSG00000207614
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 44%|████▍     | 905/2068 [4:26:33<35:17:05, 109.22s/it]

ENSG00000207615
ENSG00000207616
ENSG00000207617
ENSG00000207622
hjsdghjag

 44%|████▍     | 907/2068 [4:26:33<22:08:52, 68.68s/it]

ENSG00000207624
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 44%|████▍     | 907/2068 [4:26:49<22:08:52, 68.68s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 44%|████▍     | 909/2068 [4:31:12<27:54:31, 86.69s/it]

ENSG00000207627
hjsdghjag
ENSG00000207629
ENSG00000207631
hjsdghjag

 44%|████▍     | 913/2068 [4:31:12<10:43:11, 33.41s/it]

ENSG00000207633
ENSG00000207635
hjsdghjag
ENSG00000207638

 44%|████▍     | 914/2068 [4:31:12<8:31:07, 26.57s/it]

hjsdghjag
ENSG00000207639
hjsdghjag

 44%|████▍     | 915/2068 [4:31:13<6:35:36, 20.59s/it]

ENSG00000207645
hjsdghjag
hjsdghjag

 44%|████▍     | 917/2068 [4:31:13<3:43:40, 11.66s/it]

ENSG00000207646
hjsdghjag
ENSG00000207647
ENSG00000207649
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 44%|████▍     | 919/2068 [4:36:06<21:59:35, 68.91s/it]

ENSG00000207651
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 44%|████▍     | 920/2068 [4:40:52<38:09:31, 119.66s/it]

ENSG00000207653
ENSG00000207654
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 45%|████▍     | 923/2068 [4:45:38<31:54:40, 100.33s/it]

ENSG00000207656
hjsdghjag
ENSG00000207688
ENSG00000207689

 45%|████▍     | 927/2068 [4:45:39<12:31:34, 39.52s/it]

ENSG00000207695
ENSG00000207696
ENSG00000207698
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 45%|████▍     | 927/2068 [4:45:51<12:31:34, 39.52s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 45%|████▍     | 930/2068 [4:50:29<18:06:03, 57.26s/it]

ENSG00000207701
ENSG00000207702
ENSG00000207703
ENSG00000207705
hjsdghjag

 45%|████▌     | 932/2068 [4:50:29<11:52:29, 37.63s/it]

ENSG00000207706
ENSG00000207708
hjsdghjag

 45%|████▌     | 935/2068 [4:50:30<6:26:52, 20.49s/it]

ENSG00000207711
hjsdghjag
ENSG00000207713
hjsdghjag

 45%|████▌     | 938/2068 [4:50:30<3:09:51, 10.08s/it]

ENSG00000207714
ENSG00000207717
ENSG00000207721
hjsdghjag

 45%|████▌     | 939/2068 [4:50:31<2:30:13,  7.98s/it]

ENSG00000207722
ENSG00000207725
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 46%|████▌     | 941/2068 [4:54:56<17:18:04, 55.27s/it]

ENSG00000207726
hjsdghjag

 46%|████▌     | 942/2068 [4:54:57<13:37:24, 43.56s/it]

ENSG00000207728
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 46%|████▌     | 944/2068 [4:59:41<23:20:07, 74.74s/it]

ENSG00000207730
hjsdghjag
ENSG00000207731
hjsdghjag

 46%|████▌     | 945/2068 [4:59:41<17:11:29, 55.11s/it]

ENSG00000207732
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 46%|████▌     | 946/2068 [5:04:27<36:50:06, 118.19s/it]

ENSG00000207735
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 46%|████▌     | 948/2068 [5:08:55<35:37:06, 114.49s/it]

ENSG00000207738
hjsdghjag
ENSG00000207739
ENSG00000207741
hjsdghjag

 46%|████▌     | 950/2068 [5:08:56<19:34:37, 63.04s/it]

ENSG00000207742
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 46%|████▌     | 951/2068 [5:13:24<35:04:47, 113.06s/it]

ENSG00000207743
ENSG00000207744
hjsdghjag
hjsdghjag

 46%|████▋     | 957/2068 [5:13:25<8:31:54, 27.65s/it]

ENSG00000207749
ENSG00000207750
ENSG00000207752
ENSG00000207754
ENSG00000207757
hjsdghjag

 46%|████▋     | 959/2068 [5:13:26<5:43:41, 18.59s/it]

ENSG00000207758
hjsdghjag
ENSG00000207759
hjsdghjag

 46%|████▋     | 960/2068 [5:13:26<4:38:27, 15.08s/it]

ENSG00000207761
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 46%|████▋     | 961/2068 [5:17:52<21:11:19, 68.91s/it]

ENSG00000207768
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 47%|████▋     | 964/2068 [5:20:48<17:15:36, 56.28s/it]

ENSG00000207769
ENSG00000207773
hjsdghjag
ENSG00000207775
ENSG00000207776

 47%|████▋     | 966/2068 [5:20:48<10:57:35, 35.80s/it]

ENSG00000207778
ENSG00000207779
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 47%|████▋     | 966/2068 [5:21:04<10:57:35, 35.80s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 47%|████▋     | 968/2068 [5:25:09<20:50:35, 68.21s/it]

ENSG00000207781
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 47%|████▋     | 969/2068 [5:29:47<33:23:25, 109.38s/it]

ENSG00000207782
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 47%|████▋     | 970/2068 [5:34:27<44:45:42, 146.76s/it]

ENSG00000207784
hjsdghjag
hjsdghjag

 47%|████▋     | 973/2068 [5:34:28<20:16:02, 66.63s/it]

ENSG00000207785
ENSG00000207789
hjsdghjag
ENSG00000207797
ENSG00000207798
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 47%|████▋     | 975/2068 [5:38:56<27:45:31, 91.43s/it]

ENSG00000207803
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 47%|████▋     | 978/2068 [5:43:40<24:58:04, 82.46s/it]

ENSG00000207804
ENSG00000207805
hjsdghjag
ENSG00000207808
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 47%|████▋     | 981/2068 [5:48:04<22:44:44, 75.33s/it]

ENSG00000207810
ENSG00000207811
hjsdghjag
ENSG00000207813
hjsdghjag
hjsdghjag
hjsdghjag

 47%|████▋     | 982/2068 [5:48:04<17:57:45, 59.54s/it]

ENSG00000207820
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 48%|████▊     | 983/2068 [5:52:32<32:26:57, 107.67s/it]

ENSG00000207827
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 48%|████▊     | 985/2068 [5:57:24<34:07:38, 113.44s/it]

ENSG00000207839
hjsdghjag
ENSG00000207863
ENSG00000207864
hjsdghjag

 48%|████▊     | 987/2068 [5:57:25<19:29:50, 64.93s/it]

ENSG00000207868
ENSG00000207870
hjsdghjag

 48%|████▊     | 991/2068 [5:57:25<7:50:06, 26.19s/it]

ENSG00000207871
ENSG00000207873
hjsdghjag
ENSG00000207923
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 48%|████▊     | 992/2068 [6:02:15<23:36:36, 78.99s/it]

ENSG00000207924
hjsdghjag
hjsdghjag

 48%|████▊     | 995/2068 [6:02:15<11:12:19, 37.59s/it]

ENSG00000207926
ENSG00000207927
hjsdghjag
ENSG00000207931
ENSG00000207932
hjsdghjag

 48%|████▊     | 998/2068 [6:02:16<5:44:54, 19.34s/it]

ENSG00000207933
hjsdghjag
ENSG00000207934
ENSG00000207935
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 48%|████▊     | 1000/2068 [6:06:58<19:01:21, 64.12s/it]

ENSG00000207938
hjsdghjag
hjsdghjag
hjsdghjag

 48%|████▊     | 1001/2068 [6:07:00<15:09:47, 51.16s/it]

ENSG00000207942
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 48%|████▊     | 1002/2068 [6:11:46<31:03:38, 104.90s/it]

ENSG00000207943
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 49%|████▊     | 1003/2068 [6:14:41<36:11:08, 122.32s/it]

ENSG00000207944
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 49%|████▊     | 1004/2068 [6:19:19<48:07:44, 162.84s/it]

ENSG00000207947
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 49%|████▊     | 1005/2068 [6:23:58<57:20:37, 194.20s/it]

ENSG00000207948
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 49%|████▊     | 1007/2068 [6:28:17<44:46:42, 151.93s/it]

ENSG00000207951
hjsdghjag
ENSG00000207952
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 49%|████▊     | 1008/2068 [6:31:14<46:51:15, 159.13s/it]

ENSG00000207954
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 49%|████▉     | 1009/2068 [6:35:31<55:12:14, 187.66s/it]

ENSG00000207961
ENSG00000207962
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 49%|████▉     | 1013/2068 [6:40:30<30:15:40, 103.26s/it]

ENSG00000207963
ENSG00000207965
hjsdghjag
ENSG00000207970
ENSG00000207971

 49%|████▉     | 1015/2068 [6:40:31<19:20:16, 66.11s/it]

hjsdghjag
ENSG00000207973
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 49%|████▉     | 1016/2068 [6:45:26<32:59:48, 112.92s/it]

ENSG00000207974
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 49%|████▉     | 1018/2068 [6:50:19<33:52:37, 116.15s/it]

ENSG00000207975
hjsdghjag
ENSG00000207978
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 49%|████▉     | 1019/2068 [6:54:46<45:15:55, 155.34s/it]

ENSG00000207979
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 49%|████▉     | 1020/2068 [6:59:32<55:30:05, 190.65s/it]

ENSG00000207980
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 49%|████▉     | 1021/2068 [7:04:35<64:29:13, 221.73s/it]

ENSG00000207981
ENSG00000207982
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 49%|████▉     | 1023/2068 [7:09:25<54:32:29, 187.89s/it]

ENSG00000207983
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 50%|████▉     | 1026/2068 [7:14:15<36:25:15, 125.83s/it]

ENSG00000207988
ENSG00000207989
ENSG00000207990
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 50%|████▉     | 1027/2068 [7:19:11<47:30:08, 164.27s/it]

ENSG00000207993
ENSG00000207994
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 50%|████▉     | 1029/2068 [7:24:04<45:24:23, 157.33s/it]

ENSG00000207995
ENSG00000207996
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 50%|████▉     | 1033/2068 [7:28:44<28:43:27, 99.91s/it]

ENSG00000208001
ENSG00000208003
ENSG00000208005
ENSG00000208006
hjsdghjag
hjsdghjag
hjsdghjag

 50%|█████     | 1035/2068 [7:28:46<19:24:38, 67.65s/it]

ENSG00000208008
hjsdghjag

 50%|█████     | 1036/2068 [7:28:47<15:45:13, 54.96s/it]

ENSG00000208009
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 50%|█████     | 1038/2068 [7:33:29<22:40:03, 79.23s/it]

ENSG00000208013
hjsdghjag
ENSG00000208015
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 50%|█████     | 1039/2068 [7:37:55<35:57:21, 125.79s/it]

ENSG00000208017
hjsdghjag

 50%|█████     | 1040/2068 [7:37:55<26:29:44, 92.79s/it]

ENSG00000208023
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 50%|█████     | 1041/2068 [7:42:46<41:55:57, 146.99s/it]

ENSG00000208027
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 50%|█████     | 1042/2068 [7:47:38<53:26:58, 187.54s/it]

ENSG00000208032
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 50%|█████     | 1043/2068 [7:52:28<61:44:30, 216.85s/it]

ENSG00000208036
hjsdghjag

 51%|█████     | 1046/2068 [7:52:28<23:54:35, 84.22s/it]

ENSG00000208772
ENSG00000208797
ENSG00000210741
hjsdghjag
hjsdghjag

 51%|█████     | 1047/2068 [7:52:28<18:03:40, 63.68s/it]

ENSG00000211137
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 51%|█████     | 1048/2068 [7:57:15<34:25:27, 121.50s/it]

ENSG00000211514
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 51%|█████     | 1049/2068 [8:02:00<46:52:10, 165.58s/it]

ENSG00000211520
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 51%|█████     | 1051/2068 [8:06:45<40:12:11, 142.31s/it]

ENSG00000211538
hjsdghjag
ENSG00000211563
hjsdghjag

 51%|█████     | 1052/2068 [8:06:45<28:34:19, 101.24s/it]

ENSG00000211568
ENSG00000211574
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 51%|█████     | 1054/2068 [8:11:09<32:25:22, 115.11s/it]

ENSG00000211575
ENSG00000211578
hjsdghjag
hjsdghjag

 51%|█████     | 1056/2068 [8:11:10<19:41:55, 70.07s/it]

ENSG00000211579
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 51%|█████     | 1057/2068 [8:16:03<33:25:17, 119.01s/it]

ENSG00000211581
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 51%|█████▏    | 1060/2068 [8:19:00<22:05:51, 78.92s/it]

ENSG00000211582
ENSG00000211583
hjsdghjag
ENSG00000211590
ENSG00000211591

 51%|█████▏    | 1063/2068 [8:19:00<11:04:20, 39.66s/it]

ENSG00000211997
hjsdghjag
ENSG00000212013
ENSG00000212017
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 51%|█████▏    | 1065/2068 [8:23:25<20:42:21, 74.32s/it]

ENSG00000212024
ENSG00000212027
hjsdghjag

 52%|█████▏    | 1067/2068 [8:23:26<13:30:22, 48.57s/it]

ENSG00000212040
ENSG00000212102
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 52%|█████▏    | 1073/2068 [8:28:06<10:09:31, 36.76s/it]

ENSG00000212283
ENSG00000212440
ENSG00000212493
ENSG00000212610
ENSG00000212719
hjsdghjag
hjsdghjag
hjsdghjag

 52%|█████▏    | 1073/2068 [8:28:23<10:09:31, 36.76s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 52%|█████▏    | 1078/2068 [8:33:01<10:09:59, 36.97s/it]

ENSG00000212866
ENSG00000213551
ENSG00000213599
ENSG00000213639
ENSG00000213719

 52%|█████▏    | 1080/2068 [8:33:01<6:54:14, 25.16s/it]

ENSG00000213782
ENSG00000213853
ENSG00000213981
hjsdghjag

 52%|█████▏    | 1084/2068 [8:33:01<3:16:39, 11.99s/it]

ENSG00000214248
ENSG00000214274
ENSG00000214353
hjsdghjag

 53%|█████▎    | 1088/2068 [8:33:05<1:40:15,  6.14s/it]

ENSG00000214753
ENSG00000215301
ENSG00000215425
ENSG00000215930
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 53%|█████▎    | 1088/2068 [8:33:23<1:40:15,  6.14s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 53%|█████▎    | 1089/2068 [8:37:34<14:27:36, 53.17s/it]

ENSG00000215938
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 53%|█████▎    | 1090/2068 [8:42:21<27:21:34, 100.71s/it]

ENSG00000215939
hjsdghjag
hjsdghjag
hjsdghjag

 53%|█████▎    | 1091/2068 [8:42:23<21:19:43, 78.59s/it]

ENSG00000215957
hjsdghjag
hjsdghjag
hjsdghjag

 53%|█████▎    | 1094/2068 [8:42:25<9:32:54, 35.29s/it]

ENSG00000215961
ENSG00000215966
hjsdghjag
ENSG00000215973
ENSG00000215991

 53%|█████▎    | 1096/2068 [8:42:25<6:01:04, 22.29s/it]

hjsdghjag
ENSG00000216005
hjsdghjag
hjsdghjag
hjsdghjag

 53%|█████▎    | 1097/2068 [8:42:26<4:47:13, 17.75s/it]

ENSG00000216009
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 53%|█████▎    | 1098/2068 [8:46:44<19:40:39, 73.03s/it]

ENSG00000216031
hjsdghjag
hjsdghjag

 53%|█████▎    | 1099/2068 [8:46:45<14:50:50, 55.16s/it]

ENSG00000216069
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 53%|█████▎    | 1102/2068 [8:51:11<16:56:33, 63.14s/it]

ENSG00000216077
ENSG00000216098
ENSG00000216101
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 53%|█████▎    | 1105/2068 [8:56:03<18:42:06, 69.91s/it]

ENSG00000216135
ENSG00000216171
ENSG00000216179
ENSG00000216192
hjsdghjag

 54%|█████▎    | 1107/2068 [8:56:03<11:52:50, 44.51s/it]

ENSG00000221017
hjsdghjag
hjsdghjag
ENSG00000221028

 54%|█████▎    | 1109/2068 [8:56:03<7:48:42, 29.33s/it]

ENSG00000221033
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 54%|█████▎    | 1110/2068 [9:00:40<20:45:15, 77.99s/it]

ENSG00000221052
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 54%|█████▎    | 1111/2068 [9:05:02<31:26:46, 118.29s/it]

ENSG00000221120
ENSG00000221176
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 54%|█████▍    | 1117/2068 [9:09:42<14:20:09, 54.27s/it]

ENSG00000221200
ENSG00000221214
ENSG00000221227
ENSG00000221230
ENSG00000221238

 54%|█████▍    | 1119/2068 [9:09:43<9:40:04, 36.68s/it]

ENSG00000221263
ENSG00000221265
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 54%|█████▍    | 1119/2068 [9:09:57<9:40:04, 36.68s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 54%|█████▍    | 1122/2068 [9:14:25<14:10:23, 53.94s/it]

ENSG00000221273
ENSG00000221296
ENSG00000221355
ENSG00000221365
hjsdghjag

 54%|█████▍    | 1124/2068 [9:14:25<9:26:31, 36.01s/it]

ENSG00000221369
hjsdghjag
ENSG00000221371
hjsdghjag
hjsdghjag

 54%|█████▍    | 1126/2068 [9:14:26<6:25:00, 24.52s/it]

ENSG00000221394
ENSG00000221400
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 55%|█████▍    | 1128/2068 [9:17:24<11:41:52, 44.80s/it]

ENSG00000221410
ENSG00000221421
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 55%|█████▍    | 1130/2068 [9:21:51<18:51:23, 72.37s/it]

ENSG00000221456
ENSG00000221463
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 55%|█████▍    | 1132/2068 [9:26:18<23:41:33, 91.13s/it]

ENSG00000221464
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 55%|█████▍    | 1135/2068 [9:31:04<21:36:07, 83.35s/it]

ENSG00000221479
ENSG00000221502
ENSG00000221520
ENSG00000221525
hjsdghjag

 55%|█████▍    | 1137/2068 [9:31:04<14:31:26, 56.16s/it]

ENSG00000221537
hjsdghjag
hjsdghjag
hjsdghjag

 55%|█████▍    | 1137/2068 [9:31:19<14:31:26, 56.16s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 55%|█████▌    | 1138/2068 [9:35:52<25:51:30, 100.10s/it]

ENSG00000221545
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 55%|█████▌    | 1139/2068 [9:40:36<35:54:32, 139.15s/it]

ENSG00000221552
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 55%|█████▌    | 1141/2068 [9:45:03<32:39:21, 126.82s/it]

ENSG00000221585
hjsdghjag
ENSG00000221586
hjsdghjag

 55%|█████▌    | 1142/2068 [9:45:03<24:02:56, 93.50s/it]

ENSG00000221594
hjsdghjag

 55%|█████▌    | 1145/2068 [9:45:04<9:48:41, 38.27s/it]

ENSG00000221598
ENSG00000221614
ENSG00000221616
ENSG00000221638

 55%|█████▌    | 1147/2068 [9:45:04<6:01:35, 23.56s/it]

ENSG00000221641
ENSG00000221650
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 55%|█████▌    | 1147/2068 [9:45:20<6:01:35, 23.56s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 56%|█████▌    | 1151/2068 [9:49:57<11:21:01, 44.56s/it]

ENSG00000221656
ENSG00000221669
hjsdghjag
ENSG00000221676
ENSG00000221680

 56%|█████▌    | 1155/2068 [9:49:57<5:13:34, 20.61s/it]

ENSG00000221697
hjsdghjag
ENSG00000221703
ENSG00000221710

 56%|█████▌    | 1157/2068 [9:49:57<3:35:43, 14.21s/it]

ENSG00000221745
ENSG00000221754
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 56%|█████▌    | 1157/2068 [9:50:11<3:35:43, 14.21s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 56%|█████▌    | 1160/2068 [9:54:19<9:50:29, 39.02s/it]

ENSG00000221763
ENSG00000221771
ENSG00000221783
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 56%|█████▌    | 1160/2068 [9:54:31<9:50:29, 39.02s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 56%|█████▌    | 1161/2068 [9:58:46<21:06:57, 83.81s/it]

ENSG00000221788
ENSG00000221817
hjsdghjag
hjsdghjag

 56%|█████▌    | 1163/2068 [9:58:50<13:40:44, 54.41s/it]

ENSG00000222071
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 56%|█████▋    | 1164/2068 [10:03:12<24:16:38, 96.68s/it]

ENSG00000222246
ENSG00000222321
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 56%|█████▋    | 1168/2068 [10:07:38<18:02:21, 72.16s/it]

ENSG00000222489
ENSG00000222715
ENSG00000222958
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 56%|█████▋    | 1168/2068 [10:07:52<18:02:21, 72.16s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 57%|█████▋    | 1173/2068 [10:10:37<9:47:07, 39.36s/it]

ENSG00000223367
ENSG00000223639
ENSG00000223776
ENSG00000223949
ENSG00000223960
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 57%|█████▋    | 1173/2068 [10:10:53<9:47:07, 39.36s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 57%|█████▋    | 1174/2068 [10:15:34<22:16:10, 89.68s/it]

ENSG00000224086
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 57%|█████▋    | 1175/2068 [10:20:32<33:31:05, 135.12s/it]

ENSG00000224165
hjsdghjag
hjsdghjag
hjsdghjag

 57%|█████▋    | 1176/2068 [10:20:35<25:43:24, 103.82s/it]

ENSG00000224212
ENSG00000224424
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 57%|█████▋    | 1180/2068 [10:25:19<18:37:37, 75.52s/it]

ENSG00000224501
ENSG00000224515
ENSG00000224699
hjsdghjag

 57%|█████▋    | 1182/2068 [10:25:27<12:32:01, 50.93s/it]

ENSG00000224746
ENSG00000224794
hjsdghjag
hjsdghjag

 57%|█████▋    | 1183/2068 [10:25:29<10:10:24, 41.38s/it]

ENSG00000225073
ENSG00000225335
hjsdghjag
hjsdghjag

 57%|█████▋    | 1185/2068 [10:25:31<6:35:24, 26.87s/it]

ENSG00000225342
hjsdghjag

 57%|█████▋    | 1186/2068 [10:25:32<5:15:35, 21.47s/it]

ENSG00000225572
ENSG00000225725
hjsdghjag

 57%|█████▋    | 1188/2068 [10:25:32<3:20:20, 13.66s/it]

ENSG00000225859
ENSG00000226026
hjsdghjag

 58%|█████▊    | 1194/2068 [10:25:38<1:05:39,  4.51s/it]

ENSG00000226171
ENSG00000226173
ENSG00000226225
ENSG00000226248
ENSG00000226417
ENSG00000226419
hjsdghjag
hjsdghjag

 58%|█████▊    | 1196/2068 [10:25:43<57:27,  3.95s/it]

ENSG00000226651
ENSG00000226746
hjsdghjag
hjsdghjag

 58%|█████▊    | 1198/2068 [10:25:45<43:37,  3.01s/it]

ENSG00000226891
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 58%|█████▊    | 1199/2068 [10:30:06<11:59:49, 49.70s/it]

ENSG00000226950
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 58%|█████▊    | 1200/2068 [10:34:18<22:03:06, 91.46s/it]

ENSG00000227061
hjsdghjag

 58%|█████▊    | 1201/2068 [10:34:19<17:02:56, 70.79s/it]

ENSG00000227195
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 58%|█████▊    | 1202/2068 [10:36:51<21:47:24, 90.58s/it]

ENSG00000227214
hjsdghjag

 58%|█████▊    | 1205/2068 [10:36:51<9:15:43, 38.64s/it]

ENSG00000227333
ENSG00000227398
ENSG00000227769
hjsdghjag

 58%|█████▊    | 1209/2068 [10:36:52<3:19:41, 13.95s/it]

ENSG00000227804
ENSG00000227816
ENSG00000227896
hjsdghjag
ENSG00000227953
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 59%|█████▊    | 1210/2068 [10:41:43<19:15:10, 80.78s/it]

ENSG00000228630
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 59%|█████▊    | 1211/2068 [10:46:36<32:08:53, 135.05s/it]

ENSG00000228794
hjsdghjag
hjsdghjag

 59%|█████▊    | 1212/2068 [10:46:40<23:45:53, 99.95s/it]

ENSG00000228809
hjsdghjag

 59%|█████▊    | 1213/2068 [10:46:43<17:20:20, 73.01s/it]

ENSG00000228812
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 59%|█████▊    | 1214/2068 [10:51:24<31:21:09, 132.17s/it]

ENSG00000228925
hjsdghjag
hjsdghjag

 59%|█████▉    | 1217/2068 [10:51:31<12:27:04, 52.67s/it]

ENSG00000229496
ENSG00000229619
ENSG00000230427
hjsdghjag

 59%|█████▉    | 1218/2068 [10:51:32<9:26:55, 40.02s/it]

ENSG00000230500
hjsdghjag

 59%|█████▉    | 1221/2068 [10:51:33<4:02:39, 17.19s/it]

ENSG00000230624
ENSG00000230685
ENSG00000230705
ENSG00000230937
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 59%|█████▉    | 1223/2068 [10:56:18<15:10:51, 64.68s/it]

ENSG00000230995
ENSG00000231064
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 59%|█████▉    | 1225/2068 [11:00:37<20:26:54, 87.32s/it]

ENSG00000231154
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 59%|█████▉    | 1226/2068 [11:03:48<25:17:31, 108.14s/it]

ENSG00000231290
hjsdghjag

 59%|█████▉    | 1229/2068 [11:03:50<12:01:15, 51.58s/it]

ENSG00000231377
ENSG00000231500
ENSG00000231555
ENSG00000231638
hjsdghjag
hjsdghjag

 60%|█████▉    | 1231/2068 [11:03:50<7:44:39, 33.31s/it]

ENSG00000231737
ENSG00000231889
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 60%|█████▉    | 1233/2068 [11:08:36<16:18:38, 70.32s/it]

ENSG00000232045
ENSG00000232057
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 60%|█████▉    | 1235/2068 [11:13:14<21:25:34, 92.60s/it]

ENSG00000232367
ENSG00000232564
hjsdghjag

 60%|█████▉    | 1237/2068 [11:13:15<14:38:48, 63.45s/it]

ENSG00000232715
ENSG00000232756
hjsdghjag
hjsdghjag

 60%|█████▉    | 1239/2068 [11:13:16<10:05:40, 43.84s/it]

ENSG00000232804
ENSG00000232807
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 60%|██████    | 1241/2068 [11:17:58<16:56:58, 73.78s/it]

ENSG00000232913
hjsdghjag

 60%|██████    | 1242/2068 [11:17:59<13:53:39, 60.56s/it]

ENSG00000233002
hjsdghjag

 60%|██████    | 1243/2068 [11:17:59<11:03:22, 48.25s/it]

ENSG00000233049
ENSG00000233144
hjsdghjag

 60%|██████    | 1245/2068 [11:18:02<7:03:09, 30.85s/it]

ENSG00000233223
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 60%|██████    | 1246/2068 [11:22:48<19:12:33, 84.13s/it]

ENSG00000233360
hjsdghjag

 60%|██████    | 1247/2068 [11:22:52<15:01:23, 65.87s/it]

ENSG00000233418
ENSG00000233452
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 60%|██████    | 1249/2068 [11:27:39<21:57:01, 96.49s/it]

ENSG00000233485
hjsdghjag

 60%|██████    | 1250/2068 [11:27:39<17:06:42, 75.31s/it]

ENSG00000233561
ENSG00000233581
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 61%|██████    | 1254/2068 [11:30:36<11:42:51, 51.81s/it]

ENSG00000233695
ENSG00000233871
hjsdghjag
ENSG00000234222
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 61%|██████    | 1255/2068 [11:35:19<22:16:52, 98.66s/it]

ENSG00000234377
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 61%|██████    | 1256/2068 [11:40:03<31:37:12, 140.19s/it]

ENSG00000234741
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 61%|██████    | 1257/2068 [11:44:45<39:21:31, 174.71s/it]

ENSG00000234771
ENSG00000234883
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 61%|██████    | 1259/2068 [11:49:29<36:16:15, 161.40s/it]

ENSG00000234899
hjsdghjag

 61%|██████    | 1260/2068 [11:49:35<28:19:18, 126.19s/it]

ENSG00000235291
ENSG00000235437
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 61%|██████    | 1262/2068 [11:54:22<29:44:35, 132.85s/it]

ENSG00000235439
ENSG00000235513
hjsdghjag

 61%|██████    | 1264/2068 [11:54:24<19:06:58, 85.60s/it]

ENSG00000235650
ENSG00000235706
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 61%|██████    | 1266/2068 [11:59:20<23:46:44, 106.74s/it]

ENSG00000235724
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 61%|██████▏   | 1267/2068 [12:04:08<31:35:33, 141.99s/it]

ENSG00000235726
hjsdghjag

 61%|██████▏   | 1268/2068 [12:04:09<24:43:58, 111.30s/it]

ENSG00000235749
hjsdghjag

 61%|██████▏   | 1269/2068 [12:04:09<18:51:47, 84.99s/it]

ENSG00000235865
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 61%|██████▏   | 1270/2068 [12:08:11<27:39:55, 124.81s/it]

ENSG00000236064
ENSG00000236088
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 62%|██████▏   | 1274/2068 [12:12:26<17:21:45, 78.72s/it]

ENSG00000236548
ENSG00000236759
ENSG00000236882
hjsdghjag
hjsdghjag

 62%|██████▏   | 1275/2068 [12:12:27<13:42:02, 62.20s/it]

ENSG00000237017
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 62%|██████▏   | 1277/2068 [12:17:22<19:09:39, 87.21s/it]

ENSG00000237070
hjsdghjag
ENSG00000237187
hjsdghjag

 62%|██████▏   | 1279/2068 [12:17:27<10:30:12, 47.92s/it]

ENSG00000237479
hjsdghjag
ENSG00000237945
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 62%|██████▏   | 1280/2068 [12:21:44<23:17:41, 106.42s/it]

ENSG00000238020
hjsdghjag

 62%|██████▏   | 1281/2068 [12:21:45<16:39:08, 76.17s/it]

ENSG00000238104
ENSG00000238133
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 62%|██████▏   | 1283/2068 [12:26:38<23:31:14, 107.87s/it]

ENSG00000238134
ENSG00000238140
hjsdghjag

 62%|██████▏   | 1285/2068 [12:26:38<14:18:07, 65.76s/it]

ENSG00000238279
hjsdghjag

 62%|██████▏   | 1288/2068 [12:26:40<6:54:06, 31.85s/it]

ENSG00000238423
ENSG00000238517
ENSG00000238531
hjsdghjag

 62%|██████▏   | 1291/2068 [12:26:40<3:21:01, 15.52s/it]

ENSG00000238645
ENSG00000238705
ENSG00000238728
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 62%|██████▏   | 1292/2068 [12:31:01<14:40:12, 68.06s/it]

ENSG00000238795
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 63%|██████▎   | 1295/2068 [12:35:48<15:21:05, 71.50s/it]

ENSG00000238825
ENSG00000238917
hjsdghjag
hjsdghjag
ENSG00000239002
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 63%|██████▎   | 1296/2068 [12:40:09<24:22:40, 113.68s/it]

ENSG00000239057
ENSG00000239118
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 63%|██████▎   | 1300/2068 [12:44:30<16:29:07, 77.28s/it]

ENSG00000239306
ENSG00000239865
ENSG00000239927
ENSG00000241345
hjsdghjag

 63%|██████▎   | 1306/2068 [12:44:31<5:00:16, 23.64s/it]

ENSG00000241370
ENSG00000241779
ENSG00000241863
ENSG00000242726
ENSG00000243009
ENSG00000243766
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 63%|██████▎   | 1306/2068 [12:44:48<5:00:16, 23.64s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 63%|██████▎   | 1308/2068 [12:49:12<12:41:53, 60.15s/it]

ENSG00000244040
hjsdghjag

 63%|██████▎   | 1309/2068 [12:49:14<10:27:04, 49.57s/it]

ENSG00000244161
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 63%|██████▎   | 1310/2068 [12:53:56<20:31:27, 97.48s/it]

ENSG00000244383
hjsdghjag

 63%|██████▎   | 1311/2068 [12:53:56<15:51:43, 75.43s/it]

ENSG00000244462
ENSG00000244513
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 63%|██████▎   | 1313/2068 [12:58:43<21:24:39, 102.09s/it]

ENSG00000244879
hjsdghjag
hjsdghjag

 64%|██████▎   | 1314/2068 [12:58:50<17:00:54, 81.24s/it]

ENSG00000245552
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 64%|██████▎   | 1315/2068 [13:01:52<22:01:28, 105.30s/it]

ENSG00000245910
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 64%|██████▎   | 1316/2068 [13:06:06<29:54:28, 143.18s/it]

ENSG00000245928
hjsdghjag

 64%|██████▎   | 1317/2068 [13:06:08<22:02:50, 105.69s/it]

ENSG00000246273
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 64%|██████▎   | 1318/2068 [13:10:54<32:20:18, 155.23s/it]

ENSG00000246731
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 64%|██████▍   | 1319/2068 [13:15:16<38:35:04, 185.45s/it]

ENSG00000246740
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 64%|██████▍   | 1320/2068 [13:20:02<44:32:38, 214.38s/it]

ENSG00000246889
hjsdghjag
hjsdghjag

 64%|██████▍   | 1321/2068 [13:20:08<31:53:42, 153.71s/it]

ENSG00000247092
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 64%|██████▍   | 1322/2068 [13:25:11<40:56:39, 197.59s/it]

ENSG00000247271
hjsdghjag
hjsdghjag

 64%|██████▍   | 1323/2068 [13:25:11<28:48:56, 139.24s/it]

ENSG00000247324
hjsdghjag

 64%|██████▍   | 1324/2068 [13:25:12<20:16:34, 98.11s/it]

ENSG00000247416
hjsdghjag

 64%|██████▍   | 1325/2068 [13:25:13<14:15:31, 69.09s/it]

ENSG00000247556
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 64%|██████▍   | 1326/2068 [13:28:05<20:36:32, 99.99s/it]

ENSG00000247735
hjsdghjag
hjsdghjag

 64%|██████▍   | 1327/2068 [13:28:06<14:27:43, 70.26s/it]

ENSG00000247809
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 64%|██████▍   | 1328/2068 [13:32:50<27:36:08, 134.28s/it]

ENSG00000248333
ENSG00000248801
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 64%|██████▍   | 1330/2068 [13:35:27<22:15:31, 108.58s/it]

ENSG00000248925
ENSG00000249635
hjsdghjag

 64%|██████▍   | 1332/2068 [13:35:28<13:24:35, 65.59s/it]

ENSG00000249695
hjsdghjag

 65%|██████▍   | 1335/2068 [13:35:28<6:24:12, 31.45s/it]

ENSG00000249915
ENSG00000250007
ENSG00000250012
hjsdghjag

 65%|██████▍   | 1336/2068 [13:35:29<5:02:29, 24.79s/it]

ENSG00000250091
hjsdghjag
hjsdghjag

 65%|██████▍   | 1337/2068 [13:35:30<3:53:48, 19.19s/it]

ENSG00000250131
hjsdghjag

 65%|██████▍   | 1338/2068 [13:35:31<2:56:02, 14.47s/it]

ENSG00000250410
hjsdghjag

 65%|██████▍   | 1339/2068 [13:35:34<2:18:46, 11.42s/it]

ENSG00000250988
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 65%|██████▍   | 1340/2068 [13:40:24<17:48:25, 88.06s/it]

ENSG00000251002
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 65%|██████▍   | 1341/2068 [13:45:14<29:16:05, 144.93s/it]

ENSG00000251562
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 65%|██████▍   | 1342/2068 [13:50:02<37:30:15, 185.97s/it]

ENSG00000251733
ENSG00000251856
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 65%|██████▌   | 1348/2068 [13:54:28<12:38:58, 63.25s/it]

ENSG00000251862
ENSG00000252010
ENSG00000252153
ENSG00000252219
ENSG00000252466
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 65%|██████▌   | 1349/2068 [13:59:06<21:22:30, 107.02s/it]

ENSG00000252481
ENSG00000252824
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 66%|██████▌   | 1355/2068 [14:04:13<10:48:07, 54.54s/it]

ENSG00000252874
ENSG00000252947
ENSG00000253008
ENSG00000253027
ENSG00000253123
ENSG00000253563
hjsdghjag

 66%|██████▌   | 1357/2068 [14:04:14<7:20:11, 37.15s/it]

ENSG00000253636
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 66%|██████▌   | 1357/2068 [14:04:26<7:20:11, 37.15s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 66%|██████▌   | 1358/2068 [14:08:37<15:39:19, 79.38s/it]

ENSG00000253706
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 66%|██████▌   | 1359/2068 [14:13:35<24:40:11, 125.26s/it]

ENSG00000253729
ENSG00000254324
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 66%|██████▌   | 1361/2068 [14:18:02<25:10:55, 128.23s/it]

ENSG00000254635
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 66%|██████▌   | 1362/2068 [14:22:57<32:05:05, 163.61s/it]

ENSG00000254911
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 66%|██████▌   | 1363/2068 [14:27:22<36:39:11, 187.17s/it]

ENSG00000255240
hjsdghjag

 66%|██████▌   | 1364/2068 [14:27:23<27:32:34, 140.84s/it]

ENSG00000255389
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 66%|██████▌   | 1366/2068 [14:32:08<25:18:54, 129.82s/it]

ENSG00000255394
hjsdghjag
ENSG00000255399
hjsdghjag

 66%|██████▌   | 1368/2068 [14:32:08<13:00:06, 66.87s/it]

ENSG00000255559
hjsdghjag
ENSG00000255717
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 66%|██████▌   | 1369/2068 [14:37:13<26:24:07, 135.98s/it]

ENSG00000256925
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 66%|██████▌   | 1370/2068 [14:41:35<33:28:25, 172.64s/it]

ENSG00000257176
hjsdghjag
hjsdghjag

 66%|██████▋   | 1371/2068 [14:41:36<23:38:36, 122.12s/it]

ENSG00000257279
ENSG00000257337
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 66%|██████▋   | 1374/2068 [14:45:41<17:45:58, 92.16s/it]

ENSG00000257381
hjsdghjag
ENSG00000257557
ENSG00000257681
hjsdghjag

 67%|██████▋   | 1378/2068 [14:45:43<6:34:07, 34.27s/it]

ENSG00000258643
ENSG00000258657
hjsdghjag
ENSG00000258891
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 67%|██████▋   | 1379/2068 [14:50:35<16:53:51, 88.29s/it]

ENSG00000259073
hjsdghjag

 67%|██████▋   | 1380/2068 [14:50:36<13:03:56, 68.37s/it]

ENSG00000259163
hjsdghjag

 67%|██████▋   | 1381/2068 [14:50:38<9:52:41, 51.76s/it]

ENSG00000259602
hjsdghjag

 67%|██████▋   | 1382/2068 [14:50:38<7:18:48, 38.38s/it]

ENSG00000259642
ENSG00000259663
hjsdghjag
hjsdghjag

 67%|██████▋   | 1384/2068 [14:50:39<4:11:41, 22.08s/it]

ENSG00000259709
hjsdghjag

 67%|██████▋   | 1385/2068 [14:50:40<3:16:29, 17.26s/it]

ENSG00000260005
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 67%|██████▋   | 1386/2068 [14:55:32<16:17:55, 86.03s/it]

ENSG00000260027
ENSG00000260034
hjsdghjag

 67%|██████▋   | 1388/2068 [14:55:34<9:32:52, 50.55s/it]

ENSG00000260213
hjsdghjag
hjsdghjag

 67%|██████▋   | 1389/2068 [14:55:39<7:33:44, 40.09s/it]

ENSG00000260495
hjsdghjag
hjsdghjag

 67%|██████▋   | 1390/2068 [14:55:40<5:43:22, 30.39s/it]

ENSG00000260565
hjsdghjag
hjsdghjag

 67%|██████▋   | 1391/2068 [14:55:41<4:15:24, 22.64s/it]

ENSG00000260577
ENSG00000260719
hjsdghjag

 67%|██████▋   | 1393/2068 [14:55:41<2:27:13, 13.09s/it]

ENSG00000260855
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 67%|██████▋   | 1394/2068 [15:00:35<14:45:11, 78.80s/it]

ENSG00000260969
hjsdghjag

 67%|██████▋   | 1395/2068 [15:00:36<11:05:21, 59.32s/it]

ENSG00000261441
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 68%|██████▊   | 1396/2068 [15:04:40<20:08:44, 107.92s/it]

ENSG00000261659
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 68%|██████▊   | 1397/2068 [15:09:19<28:50:41, 154.76s/it]

ENSG00000261668
hjsdghjag

 68%|██████▊   | 1398/2068 [15:09:20<20:45:24, 111.53s/it]

ENSG00000261693
hjsdghjag
hjsdghjag

 68%|██████▊   | 1399/2068 [15:09:21<14:48:37, 79.70s/it]

ENSG00000261762
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 68%|██████▊   | 1400/2068 [15:14:04<25:44:05, 138.69s/it]

ENSG00000261822
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 68%|██████▊   | 1401/2068 [15:18:55<33:58:39, 183.39s/it]

ENSG00000262732
hjsdghjag

 68%|██████▊   | 1402/2068 [15:18:56<24:00:36, 129.78s/it]

ENSG00000262833
hjsdghjag

 68%|██████▊   | 1403/2068 [15:18:58<16:57:39, 91.82s/it]

ENSG00000263001
ENSG00000263345
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 68%|██████▊   | 1409/2068 [15:23:22<7:46:58, 42.52s/it]

ENSG00000263354
ENSG00000263361
ENSG00000263381
ENSG00000263389
ENSG00000263399
ENSG00000263409

 68%|██████▊   | 1411/2068 [15:23:22<5:07:18, 28.07s/it]

ENSG00000263413
ENSG00000263414
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 68%|██████▊   | 1411/2068 [15:23:34<5:07:18, 28.07s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 68%|██████▊   | 1415/2068 [15:27:43<7:36:33, 41.95s/it]

ENSG00000263439
ENSG00000263456
ENSG00000263476
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 68%|██████▊   | 1415/2068 [15:27:54<7:36:33, 41.95s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 69%|██████▊   | 1420/2068 [15:32:09<6:34:27, 36.52s/it]

ENSG00000263510
ENSG00000263512
ENSG00000263515
ENSG00000263526
ENSG00000263527
ENSG00000263528

 69%|██████▉   | 1426/2068 [15:32:09<2:05:59, 11.78s/it]

ENSG00000263533
ENSG00000263540
ENSG00000263561
ENSG00000263573
ENSG00000263586
hjsdghjag

 69%|██████▉   | 1430/2068 [15:32:10<1:01:41,  5.80s/it]

ENSG00000263602
ENSG00000263615
ENSG00000263628
ENSG00000263629
ENSG00000263631

 69%|██████▉   | 1436/2068 [15:32:10<21:10,  2.01s/it]

ENSG00000263634
ENSG00000263642
ENSG00000263649
ENSG00000263681
ENSG00000263693

 70%|██████▉   | 1440/2068 [15:32:11<10:36,  1.01s/it]

ENSG00000263705
ENSG00000263712
ENSG00000263730
ENSG00000263734
ENSG00000263741

 70%|██████▉   | 1446/2068 [15:32:11<04:01,  2.58it/s]

ENSG00000263744
ENSG00000263763
ENSG00000263783
ENSG00000263790
ENSG00000263800
ENSG00000263811

 70%|███████   | 1448/2068 [15:32:11<02:59,  3.45it/s]

ENSG00000263813
ENSG00000263823
hjsdghjag

 70%|███████   | 1454/2068 [15:32:17<05:12,  1.96it/s]

ENSG00000263831
ENSG00000263838
ENSG00000263857
ENSG00000263858
ENSG00000263861
ENSG00000263881

 71%|███████   | 1458/2068 [15:32:17<02:51,  3.56it/s]

ENSG00000263892
ENSG00000263894
ENSG00000263897
ENSG00000263908
hjsdghjag
hjsdghjag
hjsdghjag

 71%|███████   | 1458/2068 [15:32:35<02:51,  3.56it/s]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 71%|███████   | 1464/2068 [15:37:06<3:35:13, 21.38s/it]

ENSG00000263909
ENSG00000263932
ENSG00000263945
ENSG00000263964
ENSG00000263972

 71%|███████   | 1468/2068 [15:37:06<1:45:04, 10.51s/it]

ENSG00000263973
ENSG00000263979
ENSG00000263987
ENSG00000264004
ENSG00000264010

 71%|███████▏  | 1474/2068 [15:37:07<36:04,  3.64s/it]

ENSG00000264024
ENSG00000264032
ENSG00000264069
ENSG00000264073
ENSG00000264084
ENSG00000264089

 72%|███████▏  | 1480/2068 [15:37:07<12:38,  1.29s/it]

ENSG00000264090
ENSG00000264101
ENSG00000264102
ENSG00000264139
ENSG00000264157

 72%|███████▏  | 1484/2068 [15:37:07<06:27,  1.51it/s]

ENSG00000264200
ENSG00000264201
ENSG00000264210
ENSG00000264229
hjsdghjag

 72%|███████▏  | 1488/2068 [15:37:08<03:30,  2.75it/s]

ENSG00000264268
ENSG00000264274
ENSG00000264279
ENSG00000264295
ENSG00000264314

 72%|███████▏  | 1494/2068 [15:37:08<01:34,  6.05it/s]

ENSG00000264319
ENSG00000264330
ENSG00000264342
ENSG00000264377
ENSG00000264387
ENSG00000264405

 72%|███████▏  | 1498/2068 [15:37:08<01:09,  8.19it/s]

ENSG00000264419
hjsdghjag
ENSG00000264425
ENSG00000264468
ENSG00000264477

 73%|███████▎  | 1504/2068 [15:37:09<00:46, 12.15it/s]

ENSG00000264480
ENSG00000264482
ENSG00000264483
ENSG00000264494
ENSG00000264511
ENSG00000264513
hjsdghjag

 73%|███████▎  | 1508/2068 [15:37:10<01:08,  8.18it/s]

ENSG00000264525
ENSG00000264534
ENSG00000264539
ENSG00000264559
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 73%|███████▎  | 1508/2068 [15:37:25<01:08,  8.18it/s]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 73%|███████▎  | 1512/2068 [15:41:47<4:30:56, 29.24s/it]

ENSG00000264563
ENSG00000264566
ENSG00000264589
hjsdghjag

 73%|███████▎  | 1514/2068 [15:41:49<3:10:52, 20.67s/it]

ENSG00000264603
ENSG00000264607
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 73%|███████▎  | 1514/2068 [15:42:06<3:10:52, 20.67s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 73%|███████▎  | 1517/2068 [15:46:40<6:57:31, 45.47s/it]

ENSG00000264610
ENSG00000264614
ENSG00000264616
ENSG00000264633
hjsdghjag

 74%|███████▎  | 1521/2068 [15:46:40<3:12:00, 21.06s/it]

ENSG00000264638
ENSG00000264661
ENSG00000264712
ENSG00000264725
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 74%|███████▎  | 1521/2068 [15:46:56<3:12:00, 21.06s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 74%|███████▎  | 1523/2068 [15:51:07<8:29:32, 56.10s/it]

ENSG00000264737
ENSG00000264739
hjsdghjag

 74%|███████▎  | 1525/2068 [15:51:08<5:52:16, 38.93s/it]

ENSG00000264741
ENSG00000264763
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 74%|███████▍  | 1529/2068 [15:55:46<7:14:26, 48.36s/it]

ENSG00000264764
ENSG00000264772
ENSG00000264773
ENSG00000264788
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 74%|███████▍  | 1529/2068 [15:55:57<7:14:26, 48.36s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 74%|███████▍  | 1535/2068 [16:00:07<5:17:17, 35.72s/it]

ENSG00000264792
ENSG00000264796
ENSG00000264802
ENSG00000264803
ENSG00000264823
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 74%|███████▍  | 1535/2068 [16:00:18<5:17:17, 35.72s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 74%|███████▍  | 1538/2068 [16:04:44<7:40:55, 52.18s/it]

ENSG00000264824
ENSG00000264850
ENSG00000264864
hjsdghjag
ENSG00000264901

 75%|███████▍  | 1542/2068 [16:04:45<3:31:34, 24.13s/it]

ENSG00000264906
ENSG00000264922
ENSG00000264926
ENSG00000264940
hjsdghjag

 75%|███████▍  | 1548/2068 [16:04:50<1:13:04,  8.43s/it]

ENSG00000264961
ENSG00000264974
ENSG00000264979
ENSG00000264986
ENSG00000265005
hjsdghjag
hjsdghjag
hjsdghjag

 75%|███████▍  | 1548/2068 [16:05:08<1:13:04,  8.43s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 75%|███████▌  | 1553/2068 [16:09:38<3:44:00, 26.10s/it]

ENSG00000265014
ENSG00000265056
ENSG00000265064
ENSG00000265098
ENSG00000265102
ENSG00000265110

 75%|███████▌  | 1557/2068 [16:09:39<1:44:35, 12.28s/it]

ENSG00000265112
ENSG00000265134
ENSG00000265137
hjsdghjag
ENSG00000265144

 76%|███████▌  | 1563/2068 [16:09:39<34:54,  4.15s/it]

ENSG00000265154
ENSG00000265160
ENSG00000265164
ENSG00000265172
ENSG00000265176
ENSG00000265178

 76%|███████▌  | 1565/2068 [16:09:39<24:23,  2.91s/it]

ENSG00000265181
ENSG00000265194
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 76%|███████▌  | 1565/2068 [16:09:59<24:23,  2.91s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 76%|███████▌  | 1567/2068 [16:13:59<5:44:30, 41.26s/it]

ENSG00000265201
ENSG00000265215
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 76%|███████▌  | 1569/2068 [16:18:38<9:48:57, 70.82s/it]

ENSG00000265227
ENSG00000265237
hjsdghjag
hjsdghjag

 76%|███████▌  | 1575/2068 [16:18:39<3:19:40, 24.30s/it]

ENSG00000265241
ENSG00000265251
ENSG00000265253
ENSG00000265258
ENSG00000265284

 76%|███████▋  | 1579/2068 [16:18:39<1:37:18, 11.94s/it]

ENSG00000265328
ENSG00000265331
ENSG00000265333
hjsdghjag
ENSG00000265376
ENSG00000265392

 77%|███████▋  | 1585/2068 [16:18:39<33:16,  4.13s/it]

ENSG00000265395
ENSG00000265407
ENSG00000265420
ENSG00000265422
ENSG00000265423

 77%|███████▋  | 1589/2068 [16:18:40<16:29,  2.07s/it]

ENSG00000265429
ENSG00000265435
hjsdghjag
ENSG00000265442
ENSG00000265452

 77%|███████▋  | 1593/2068 [16:18:40<08:15,  1.04s/it]

ENSG00000265456
ENSG00000265465
ENSG00000265470
ENSG00000265527
ENSG00000265537
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 77%|███████▋  | 1593/2068 [16:19:00<08:15,  1.04s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 77%|███████▋  | 1599/2068 [16:23:18<2:42:35, 20.80s/it]

ENSG00000265538
ENSG00000265539
ENSG00000265558
ENSG00000265561
ENSG00000265565

 78%|███████▊  | 1605/2068 [16:23:18<55:21,  7.17s/it]

ENSG00000265584
ENSG00000265599
ENSG00000265606
ENSG00000265623
ENSG00000265653
ENSG00000265658
ENSG00000265673

 78%|███████▊  | 1609/2068 [16:23:18<27:08,  3.55s/it]

ENSG00000265681
ENSG00000265694
ENSG00000265725
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 78%|███████▊  | 1609/2068 [16:23:30<27:08,  3.55s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 78%|███████▊  | 1614/2068 [16:28:04<3:01:38, 24.01s/it]

ENSG00000265734
ENSG00000265768
ENSG00000265822
ENSG00000265859
ENSG00000265873
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 78%|███████▊  | 1614/2068 [16:28:21<3:01:38, 24.01s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 78%|███████▊  | 1619/2068 [16:32:30<3:45:22, 30.12s/it]

ENSG00000265878
ENSG00000265902
ENSG00000265917
ENSG00000265929
ENSG00000265932
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 78%|███████▊  | 1619/2068 [16:32:41<3:45:22, 30.12s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 79%|███████▊  | 1624/2068 [16:37:13<4:09:52, 33.77s/it]

ENSG00000265954
ENSG00000265956
ENSG00000265957
ENSG00000265976
ENSG00000265986

 79%|███████▉  | 1630/2068 [16:37:13<1:18:39, 10.78s/it]

ENSG00000266006
ENSG00000266016
ENSG00000266017
ENSG00000266019
ENSG00000266038
ENSG00000266039

 79%|███████▉  | 1634/2068 [16:37:13<37:41,  5.21s/it]

ENSG00000266041
ENSG00000266052
ENSG00000266071
ENSG00000266099
ENSG00000266140

 79%|███████▉  | 1640/2068 [16:37:14<12:53,  1.81s/it]

ENSG00000266144
ENSG00000266146
ENSG00000266150
ENSG00000266151
ENSG00000266168

 79%|███████▉  | 1642/2068 [16:37:14<09:05,  1.28s/it]

ENSG00000266174
ENSG00000266192
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 79%|███████▉  | 1642/2068 [16:37:32<09:05,  1.28s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 80%|███████▉  | 1647/2068 [16:41:36<2:29:26, 21.30s/it]

ENSG00000266194
ENSG00000266203
ENSG00000266204
ENSG00000266206
ENSG00000266215
hjsdghjag

 80%|███████▉  | 1651/2068 [16:41:36<1:09:55, 10.06s/it]

ENSG00000266226
ENSG00000266235
ENSG00000266245
ENSG00000266262

 80%|███████▉  | 1653/2068 [16:41:36<48:17,  6.98s/it]

ENSG00000266276
ENSG00000266291
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 80%|███████▉  | 1653/2068 [16:41:52<48:17,  6.98s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 80%|████████  | 1655/2068 [16:46:15<5:06:42, 44.56s/it]

ENSG00000266297
hjsdghjag
ENSG00000266299
ENSG00000266305

 80%|████████  | 1661/2068 [16:46:16<1:23:54, 12.37s/it]

ENSG00000266307
ENSG00000266315
ENSG00000266318
ENSG00000266320
ENSG00000266325

 81%|████████  | 1665/2068 [16:46:16<38:56,  5.80s/it]

ENSG00000266327
ENSG00000266329
ENSG00000266354
ENSG00000266383
ENSG00000266396
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 81%|████████  | 1665/2068 [16:46:33<38:56,  5.80s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 81%|████████  | 1667/2068 [16:51:13<5:34:41, 50.08s/it]

ENSG00000266407
ENSG00000266423
hjsdghjag
hjsdghjag
hjsdghjag

 81%|████████  | 1671/2068 [16:51:14<2:40:20, 24.23s/it]

ENSG00000266437
ENSG00000266454
hjsdghjag
ENSG00000266461
ENSG00000266478

 81%|████████  | 1677/2068 [16:51:14<53:52,  8.27s/it]

ENSG00000266494
ENSG00000266507
ENSG00000266509
ENSG00000266515
ENSG00000266517

 81%|████████▏ | 1681/2068 [16:51:15<26:15,  4.07s/it]

ENSG00000266525
ENSG00000266531
ENSG00000266533
ENSG00000266555
ENSG00000266580

 82%|████████▏ | 1687/2068 [16:51:15<09:06,  1.43s/it]

ENSG00000266589
ENSG00000266593
ENSG00000266594
ENSG00000266611
ENSG00000266617

 82%|████████▏ | 1691/2068 [16:51:15<04:36,  1.36it/s]

ENSG00000266643
ENSG00000266649
ENSG00000266663
ENSG00000266665
ENSG00000266680
hjsdghjag
hjsdghjag

 82%|████████▏ | 1697/2068 [16:51:17<02:32,  2.43it/s]

ENSG00000266698
ENSG00000266704
ENSG00000266719
ENSG00000266740
ENSG00000266745
ENSG00000266756

 82%|████████▏ | 1703/2068 [16:51:18<01:06,  5.50it/s]

ENSG00000266760
ENSG00000266761
ENSG00000266776
ENSG00000266782
ENSG00000266852

 82%|████████▏ | 1705/2068 [16:51:18<00:52,  6.87it/s]

ENSG00000266855
ENSG00000267177
hjsdghjag
ENSG00000267192
hjsdghjag

 83%|████████▎ | 1707/2068 [16:51:18<01:03,  5.73it/s]

ENSG00000267195
hjsdghjag
ENSG00000267200
hjsdghjag

 83%|████████▎ | 1709/2068 [16:51:19<01:06,  5.38it/s]

ENSG00000267322
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 83%|████████▎ | 1710/2068 [16:56:05<5:02:36, 50.72s/it]

ENSG00000267383
hjsdghjag

 83%|████████▎ | 1711/2068 [16:56:08<4:03:43, 40.96s/it]

ENSG00000267532
hjsdghjag

 83%|████████▎ | 1712/2068 [16:56:15<3:18:20, 33.43s/it]

ENSG00000267551
hjsdghjag
hjsdghjag

 83%|████████▎ | 1713/2068 [16:56:16<2:31:45, 25.65s/it]

ENSG00000267560
hjsdghjag

 83%|████████▎ | 1714/2068 [16:56:16<1:53:00, 19.15s/it]

ENSG00000267750
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 83%|████████▎ | 1715/2068 [17:00:16<7:40:45, 78.32s/it]

ENSG00000267751
hjsdghjag

 83%|████████▎ | 1716/2068 [17:00:18<5:35:00, 57.10s/it]

ENSG00000267774
ENSG00000267801
hjsdghjag

 83%|████████▎ | 1718/2068 [17:00:21<3:10:21, 32.63s/it]

ENSG00000268119
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 83%|████████▎ | 1719/2068 [17:04:20<7:58:07, 82.20s/it]

ENSG00000268575
hjsdghjag
hjsdghjag
hjsdghjag

 83%|████████▎ | 1720/2068 [17:04:22<5:57:44, 61.68s/it]

ENSG00000268686
hjsdghjag

 83%|████████▎ | 1721/2068 [17:04:23<4:22:13, 45.34s/it]

ENSG00000269821
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 83%|████████▎ | 1722/2068 [17:08:39<9:57:38, 103.64s/it]

ENSG00000269834
hjsdghjag
hjsdghjag

 83%|████████▎ | 1723/2068 [17:08:40<7:09:07, 74.63s/it]

ENSG00000269858
ENSG00000270049
hjsdghjag

 83%|████████▎ | 1725/2068 [17:08:41<3:56:17, 41.33s/it]

ENSG00000270641
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 83%|████████▎ | 1726/2068 [17:13:02<8:58:42, 94.51s/it]

ENSG00000270647
ENSG00000270722
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 84%|████████▎ | 1728/2068 [17:16:14<8:59:52, 95.27s/it]

ENSG00000271335
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 84%|████████▎ | 1729/2068 [17:21:03<13:05:40, 139.06s/it]

ENSG00000271825
ENSG00000271886
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 84%|████████▍ | 1734/2068 [17:25:17<6:21:15, 68.49s/it]

ENSG00000271899
ENSG00000271933
ENSG00000272036
hjsdghjag
ENSG00000272078

 84%|████████▍ | 1738/2068 [17:25:17<2:36:06, 28.38s/it]

ENSG00000272080
hjsdghjag
ENSG00000272230
ENSG00000272267
ENSG00000272356
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 84%|████████▍ | 1740/2068 [17:25:21<1:47:11, 19.61s/it]

ENSG00000272380
ENSG00000272405
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 84%|████████▍ | 1743/2068 [17:29:43<3:51:10, 42.68s/it]

ENSG00000272458
ENSG00000272543
ENSG00000272702
hjsdghjag
hjsdghjag

 84%|████████▍ | 1747/2068 [17:29:44<1:43:19, 19.31s/it]

ENSG00000272884
ENSG00000273151
ENSG00000273372
ENSG00000273500
ENSG00000273613

 85%|████████▍ | 1753/2068 [17:29:45<33:16,  6.34s/it]

ENSG00000273618
ENSG00000273627
ENSG00000273725
ENSG00000273742
ENSG00000273744
hjsdghjag

 85%|████████▍ | 1757/2068 [17:29:45<16:07,  3.11s/it]

ENSG00000273761
ENSG00000273769
ENSG00000273772
ENSG00000273899

 85%|████████▌ | 1761/2068 [17:29:45<07:54,  1.55s/it]

ENSG00000274056
ENSG00000274066
ENSG00000274210
ENSG00000274417
ENSG00000274442

 85%|████████▌ | 1765/2068 [17:29:46<03:58,  1.27it/s]

ENSG00000274620
ENSG00000274660
ENSG00000274705
hjsdghjag
ENSG00000274769

 86%|████████▌ | 1771/2068 [17:29:46<01:33,  3.19it/s]

ENSG00000274770
ENSG00000275101
ENSG00000275109
ENSG00000275219
ENSG00000275259

 86%|████████▌ | 1775/2068 [17:29:46<00:54,  5.39it/s]

ENSG00000275272
ENSG00000275334
ENSG00000275344
ENSG00000275349
ENSG00000275373

 86%|████████▌ | 1777/2068 [17:29:46<00:43,  6.75it/s]

ENSG00000275453
hjsdghjag
hjsdghjag
ENSG00000275523

 86%|████████▌ | 1779/2068 [17:29:47<00:40,  7.12it/s]

ENSG00000275538
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 86%|████████▌ | 1779/2068 [17:29:57<00:40,  7.12it/s]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 86%|████████▌ | 1781/2068 [17:32:55<2:07:18, 26.61s/it]

ENSG00000275620
hjsdghjag
ENSG00000275726
ENSG00000275808

 86%|████████▋ | 1787/2068 [17:32:55<35:06,  7.50s/it]

ENSG00000275859
ENSG00000275924
ENSG00000276029
ENSG00000276137
ENSG00000276158

 87%|████████▋ | 1791/2068 [17:32:55<16:19,  3.53s/it]

ENSG00000276213
ENSG00000276259
ENSG00000276311
ENSG00000276352
ENSG00000276365
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 87%|████████▋ | 1791/2068 [17:33:07<16:19,  3.53s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 87%|████████▋ | 1794/2068 [17:37:17<2:40:14, 35.09s/it]

ENSG00000276404
hjsdghjag
ENSG00000276479
ENSG00000276568

 87%|████████▋ | 1800/2068 [17:37:17<47:31, 10.64s/it]

ENSG00000276598
ENSG00000276833
ENSG00000276835
ENSG00000276857
ENSG00000276878
ENSG00000276941

 87%|████████▋ | 1804/2068 [17:37:17<22:25,  5.10s/it]

ENSG00000277014
hjsdghjag
ENSG00000277073
ENSG00000277120
ENSG00000277209

 88%|████████▊ | 1810/2068 [17:37:18<07:32,  1.76s/it]

ENSG00000277313
ENSG00000277478
ENSG00000277564
ENSG00000277621
ENSG00000277757
hjsdghjag
hjsdghjag
hjsdghjag

 88%|████████▊ | 1810/2068 [17:37:28<07:32,  1.76s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 88%|████████▊ | 1813/2068 [17:42:03<2:27:05, 34.61s/it]

ENSG00000277759
ENSG00000277773
ENSG00000277846
ENSG00000277918
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 88%|████████▊ | 1813/2068 [17:42:18<2:27:05, 34.61s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 88%|████████▊ | 1815/2068 [17:44:52<3:34:18, 50.82s/it]

ENSG00000278069
ENSG00000278140
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 88%|████████▊ | 1821/2068 [17:49:36<2:36:15, 37.96s/it]

ENSG00000278221
ENSG00000278229
ENSG00000278249
ENSG00000278348
ENSG00000278756
ENSG00000279080
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 88%|████████▊ | 1821/2068 [17:49:49<2:36:15, 37.96s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 88%|████████▊ | 1823/2068 [17:54:33<4:53:27, 71.87s/it]

ENSG00000279085
ENSG00000279110
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 88%|████████▊ | 1825/2068 [17:57:31<5:12:03, 77.05s/it]

ENSG00000279159
hjsdghjag
hjsdghjag

 88%|████████▊ | 1828/2068 [17:57:32<2:48:15, 42.06s/it]

ENSG00000279182
ENSG00000279249
ENSG00000279317
hjsdghjag
ENSG00000279467
hjsdghjag
hjsdghjag

 89%|████████▊ | 1832/2068 [17:57:36<1:17:48, 19.78s/it]

ENSG00000280011
ENSG00000280548
ENSG00000280607
hjsdghjag
hjsdghjag
hjsdghjag

 89%|████████▊ | 1832/2068 [17:57:50<1:17:48, 19.78s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 89%|████████▊ | 1833/2068 [18:02:23<4:30:36, 69.09s/it]

ENSG00000280734
hjsdghjag

 89%|████████▉ | 1836/2068 [18:02:23<2:12:37, 34.30s/it]

ENSG00000280858
ENSG00000280948
ENSG00000281103
hjsdghjag
hjsdghjag
hjsdghjag

 89%|████████▉ | 1836/2068 [18:02:40<2:12:37, 34.30s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 89%|████████▉ | 1837/2068 [18:07:41<6:02:06, 94.06s/it]

ENSG00000281388
ENSG00000281398
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 89%|████████▉ | 1839/2068 [18:12:36<7:15:35, 114.13s/it]

ENSG00000281403
ENSG00000281516
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 89%|████████▉ | 1841/2068 [18:17:18<7:47:13, 123.50s/it]

ENSG00000281540
ENSG00000281696
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 89%|████████▉ | 1843/2068 [18:22:12<8:12:46, 131.41s/it]

ENSG00000282221
ENSG00000282685
hjsdghjag

 89%|████████▉ | 1849/2068 [18:22:14<2:33:55, 42.17s/it]

ENSG00000282900
ENSG00000282947
ENSG00000282958
ENSG00000283146
ENSG00000283152
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 89%|████████▉ | 1849/2068 [18:22:32<2:33:55, 42.17s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 90%|████████▉ | 1852/2068 [18:26:58<3:24:13, 56.73s/it]

ENSG00000283159
ENSG00000283165
ENSG00000283170
hjsdghjag
ENSG00000283193

 90%|████████▉ | 1854/2068 [18:26:58<2:16:05, 38.16s/it]

ENSG00000283200
hjsdghjag
hjsdghjag

 90%|████████▉ | 1858/2068 [18:26:59<1:02:47, 17.94s/it]

ENSG00000283206
ENSG00000283212
ENSG00000283222
ENSG00000283237
ENSG00000283238

 90%|█████████ | 1862/2068 [18:26:59<29:38,  8.63s/it]

ENSG00000283242
ENSG00000283279
ENSG00000283289
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 90%|█████████ | 1862/2068 [18:27:13<29:38,  8.63s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 90%|█████████ | 1867/2068 [18:31:25<1:21:39, 24.37s/it]

ENSG00000283296
ENSG00000283301
ENSG00000283330
ENSG00000283335
ENSG00000283344
hjsdghjag
hjsdghjag
hjsdghjag

 90%|█████████ | 1867/2068 [18:31:43<1:21:39, 24.37s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 91%|█████████ | 1872/2068 [18:36:13<1:44:53, 32.11s/it]

ENSG00000283364
ENSG00000283385
ENSG00000283386
ENSG00000283409
ENSG00000283429
hjsdghjag
hjsdghjag

 91%|█████████ | 1872/2068 [18:36:24<1:44:53, 32.11s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 91%|█████████ | 1873/2068 [18:41:01<4:24:42, 81.45s/it]

ENSG00000283475
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 91%|█████████ | 1876/2068 [18:45:50<4:09:56, 78.10s/it]

ENSG00000283484
ENSG00000283490
hjsdghjag
ENSG00000283492
ENSG00000283498
hjsdghjag
hjsdghjag
hjsdghjag

 91%|█████████ | 1876/2068 [18:46:05<4:09:56, 78.10s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 91%|█████████ | 1878/2068 [18:50:38<5:20:58, 101.36s/it]

ENSG00000283519
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 91%|█████████ | 1881/2068 [18:55:21<4:32:46, 87.52s/it]

ENSG00000283534
ENSG00000283540
ENSG00000283550
hjsdghjag
hjsdghjag
hjsdghjag
ENSG00000283556
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 91%|█████████ | 1881/2068 [18:55:36<4:32:46, 87.52s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 91%|█████████ | 1883/2068 [18:59:47<5:18:13, 103.21s/it]

ENSG00000283588
hjsdghjag
hjsdghjag

 91%|█████████ | 1886/2068 [18:59:48<2:41:22, 53.20s/it]

ENSG00000283591
ENSG00000283604
hjsdghjag
ENSG00000283609
ENSG00000283645

 91%|█████████▏| 1890/2068 [18:59:48<1:10:18, 23.70s/it]

ENSG00000283682
ENSG00000283685
ENSG00000283688
ENSG00000283705
hjsdghjag

 92%|█████████▏| 1894/2068 [18:59:49<32:24, 11.18s/it]

ENSG00000283721
ENSG00000283726
ENSG00000283733
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 92%|█████████▏| 1894/2068 [19:00:06<32:24, 11.18s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 92%|█████████▏| 1896/2068 [19:04:16<2:11:43, 45.95s/it]

ENSG00000283736
hjsdghjag
ENSG00000283745
hjsdghjag

 92%|█████████▏| 1899/2068 [19:04:17<1:04:30, 22.90s/it]

ENSG00000283749
ENSG00000283751
hjsdghjag
ENSG00000283762
hjsdghjag
hjsdghjag

 92%|█████████▏| 1901/2068 [19:04:18<37:28, 13.47s/it]

ENSG00000283768
hjsdghjag
ENSG00000283774
hjsdghjag

 92%|█████████▏| 1902/2068 [19:04:18<27:36,  9.98s/it]

ENSG00000283785
hjsdghjag
hjsdghjag
hjsdghjag

 92%|█████████▏| 1905/2068 [19:04:20<12:00,  4.42s/it]

ENSG00000283791
ENSG00000283792
ENSG00000283796
ENSG00000283797
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 92%|█████████▏| 1909/2068 [19:08:41<1:30:21, 34.10s/it]

ENSG00000283798
ENSG00000283799
hjsdghjag
ENSG00000283803
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 92%|█████████▏| 1910/2068 [19:13:24<3:42:25, 84.47s/it]

ENSG00000283815
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 92%|█████████▏| 1911/2068 [19:17:45<5:24:31, 124.02s/it]

ENSG00000283819
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 92%|█████████▏| 1912/2068 [19:22:06<6:48:37, 157.16s/it]

ENSG00000283822
ENSG00000283824
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 93%|█████████▎| 1914/2068 [19:26:27<6:15:36, 146.34s/it]

ENSG00000283829
ENSG00000283844
hjsdghjag

 93%|█████████▎| 1916/2068 [19:26:28<3:54:06, 92.41s/it]

ENSG00000283853
ENSG00000283857
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 93%|█████████▎| 1918/2068 [19:31:14<4:34:50, 109.94s/it]

ENSG00000283863
ENSG00000283871
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 93%|█████████▎| 1922/2068 [19:35:54<3:18:09, 81.43s/it]

ENSG00000283874
ENSG00000283881
ENSG00000283891
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 93%|█████████▎| 1922/2068 [19:36:09<3:18:09, 81.43s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 93%|█████████▎| 1923/2068 [19:40:22<4:40:53, 116.23s/it]

ENSG00000283899
ENSG00000283904
hjsdghjag
hjsdghjag

 93%|█████████▎| 1927/2068 [19:40:23<1:59:18, 50.77s/it]

ENSG00000283912
ENSG00000283923
ENSG00000283926
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 93%|█████████▎| 1927/2068 [19:40:40<1:59:18, 50.77s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 93%|█████████▎| 1928/2068 [19:45:04<3:41:41, 95.01s/it]

ENSG00000283928
ENSG00000283931
hjsdghjag
hjsdghjag
hjsdghjag

 93%|█████████▎| 1930/2068 [19:45:05<2:21:30, 61.53s/it]

ENSG00000283935
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 93%|█████████▎| 1932/2068 [19:49:44<3:05:20, 81.77s/it]

ENSG00000283936
hjsdghjag
ENSG00000283938
ENSG00000283958
hjsdghjag

 94%|█████████▎| 1938/2068 [19:49:44<46:03, 21.25s/it]

ENSG00000283969
ENSG00000283978
ENSG00000284000
ENSG00000284008
ENSG00000284010
hjsdghjag

 94%|█████████▍| 1940/2068 [19:49:44<30:38, 14.36s/it]

ENSG00000284020
ENSG00000284027
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 94%|█████████▍| 1940/2068 [19:50:01<30:38, 14.36s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 94%|█████████▍| 1943/2068 [19:54:13<1:24:23, 40.50s/it]

ENSG00000284028
ENSG00000284031
ENSG00000284032
hjsdghjag

 94%|█████████▍| 1945/2068 [19:54:13<55:30, 27.07s/it]

ENSG00000284034
ENSG00000284035
ENSG00000284038
hjsdghjag

 94%|█████████▍| 1947/2068 [19:54:14<37:06, 18.40s/it]

ENSG00000284040
hjsdghjag

 94%|█████████▍| 1948/2068 [19:54:14<30:00, 15.00s/it]

ENSG00000284043
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 94%|█████████▍| 1951/2068 [19:58:39<1:22:30, 42.31s/it]

ENSG00000284074
ENSG00000284079
ENSG00000284107
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 94%|█████████▍| 1952/2068 [20:03:33<3:04:48, 95.59s/it]

ENSG00000284112
hjsdghjag
hjsdghjag
hjsdghjag

 95%|█████████▍| 1955/2068 [20:03:35<1:23:42, 44.45s/it]

ENSG00000284118
ENSG00000284122
ENSG00000284125
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 95%|█████████▍| 1960/2068 [20:08:13<1:08:15, 37.92s/it]

ENSG00000284139
ENSG00000284140
ENSG00000284143
ENSG00000284144
ENSG00000284146
ENSG00000284149

 95%|█████████▍| 1964/2068 [20:08:14<29:27, 17.00s/it]

ENSG00000284154
ENSG00000284155
hjsdghjag
ENSG00000284157
hjsdghjag

 95%|█████████▌| 1966/2068 [20:08:14<19:47, 11.64s/it]

ENSG00000284163
hjsdghjag
ENSG00000284175
ENSG00000284179
hjsdghjag

 95%|█████████▌| 1968/2068 [20:08:14<13:24,  8.05s/it]

ENSG00000284180
ENSG00000284182
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 95%|█████████▌| 1968/2068 [20:08:33<13:24,  8.05s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 95%|█████████▌| 1970/2068 [20:12:57<1:20:21, 49.20s/it]

ENSG00000284184
ENSG00000284190
hjsdghjag

 95%|█████████▌| 1973/2068 [20:12:58<44:35, 28.17s/it]

ENSG00000284191
hjsdghjag
ENSG00000284197
ENSG00000284202

 96%|█████████▌| 1975/2068 [20:12:58<28:56, 18.67s/it]

hjsdghjag
ENSG00000284203
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 96%|█████████▌| 1976/2068 [20:17:22<1:41:37, 66.28s/it]

ENSG00000284204
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 96%|█████████▌| 1978/2068 [20:22:03<2:09:33, 86.37s/it]

ENSG00000284214
hjsdghjag
ENSG00000284216

 96%|█████████▌| 1980/2068 [20:22:04<1:15:32, 51.51s/it]

ENSG00000284219
ENSG00000284224
ENSG00000284231
hjsdghjag
hjsdghjag
hjsdghjag

 96%|█████████▌| 1986/2068 [20:22:06<19:55, 14.58s/it]

ENSG00000284239
ENSG00000284246
ENSG00000284251
ENSG00000284254
ENSG00000284256

 96%|█████████▌| 1990/2068 [20:22:06<08:54,  6.85s/it]

ENSG00000284266
ENSG00000284305
hjsdghjag
ENSG00000284310
ENSG00000284321
hjsdghjag
ENSG00000284324

 96%|█████████▋| 1994/2068 [20:22:07<04:07,  3.35s/it]

hjsdghjag
ENSG00000284331
ENSG00000284334
ENSG00000284353
hjsdghjag
hjsdghjag
hjsdghjag

 96%|█████████▋| 1994/2068 [20:22:24<04:07,  3.35s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 96%|█████████▋| 1995/2068 [20:26:55<1:06:23, 54.56s/it]

ENSG00000284357
hjsdghjag
hjsdghjag

 97%|█████████▋| 1996/2068 [20:26:56<52:13, 43.52s/it]

ENSG00000284361
ENSG00000284363
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 97%|█████████▋| 1998/2068 [20:29:51<1:09:51, 59.87s/it]

ENSG00000284370
ENSG00000284375
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 97%|█████████▋| 2000/2068 [20:34:33<1:39:25, 87.73s/it]

ENSG00000284378
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 97%|█████████▋| 2003/2068 [20:39:21<1:28:11, 81.40s/it]

ENSG00000284386
ENSG00000284388
ENSG00000284399
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 97%|█████████▋| 2003/2068 [20:39:36<1:28:11, 81.40s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 97%|█████████▋| 2006/2068 [20:43:59<1:19:19, 76.76s/it]

ENSG00000284407
ENSG00000284411
ENSG00000284412
ENSG00000284419
hjsdghjag

 97%|█████████▋| 2010/2068 [20:43:59<32:34, 33.69s/it]

ENSG00000284424
ENSG00000284427
ENSG00000284433
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 97%|█████████▋| 2010/2068 [20:44:16<32:34, 33.69s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 97%|█████████▋| 2011/2068 [20:46:54<57:33, 60.59s/it]

ENSG00000284435
ENSG00000284440
hjsdghjag

 97%|█████████▋| 2013/2068 [20:46:54<35:59, 39.26s/it]

ENSG00000284443
hjsdghjag
ENSG00000284446

 97%|█████████▋| 2015/2068 [20:46:54<23:05, 26.14s/it]

ENSG00000284450
ENSG00000284453
hjsdghjag
hjsdghjag

 97%|█████████▋| 2015/2068 [20:47:07<23:05, 26.14s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 98%|█████████▊| 2017/2068 [20:51:43<54:46, 64.45s/it]

ENSG00000284458
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 98%|█████████▊| 2018/2068 [20:56:22<1:27:13, 104.68s/it]

ENSG00000284459
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 98%|█████████▊| 2019/2068 [21:01:08<1:56:52, 143.10s/it]

ENSG00000284463
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 98%|█████████▊| 2021/2068 [21:05:29<1:40:18, 128.06s/it]

ENSG00000284464
hjsdghjag
ENSG00000284469
ENSG00000284485

 98%|█████████▊| 2023/2068 [21:05:30<56:09, 74.88s/it]

hjsdghjag
ENSG00000284499
ENSG00000284503

 98%|█████████▊| 2025/2068 [21:05:30<33:42, 47.02s/it]

hjsdghjag
ENSG00000284518
ENSG00000284520
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 98%|█████████▊| 2029/2068 [21:10:16<34:53, 53.68s/it]

ENSG00000284525
ENSG00000284532
ENSG00000284536
hjsdghjag
hjsdghjag

 98%|█████████▊| 2029/2068 [21:10:29<34:53, 53.68s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 98%|█████████▊| 2030/2068 [21:15:03<1:02:24, 98.54s/it]

ENSG00000284538
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 98%|█████████▊| 2035/2068 [21:19:43<30:20, 55.16s/it]

ENSG00000284541
ENSG00000284542
ENSG00000284544
ENSG00000284547
ENSG00000284564
hjsdghjag
ENSG00000284565
hjsdghjag

 99%|█████████▊| 2037/2068 [21:19:43<18:59, 36.76s/it]

ENSG00000284567
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 99%|█████████▊| 2037/2068 [21:20:00<18:59, 36.76s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 99%|█████████▊| 2040/2068 [21:24:26<25:21, 54.35s/it]

ENSG00000284568
ENSG00000284575
ENSG00000284585
ENSG00000284586
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 99%|█████████▊| 2040/2068 [21:24:41<25:21, 54.35s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

 99%|█████████▉| 2046/2068 [21:29:04<14:00, 38.22s/it]

ENSG00000284587
ENSG00000284596
ENSG00000284880
ENSG00000284918
ENSG00000284998

 99%|█████████▉| 2050/2068 [21:29:04<05:28, 18.26s/it]

ENSG00000285033
ENSG00000285049
ENSG00000285056
hjsdghjag
ENSG00000285083
ENSG00000285161
hjsdghjag

 99%|█████████▉| 2056/2068 [21:29:05<01:14,  6.21s/it]

ENSG00000285207
ENSG00000285270
ENSG00000285317
ENSG00000285406
ENSG00000285438

100%|█████████▉| 2060/2068 [21:29:05<00:24,  3.06s/it]

ENSG00000288121
ENSG00000288130
ENSG00000288145
ENSG00000288183
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

100%|█████████▉| 2060/2068 [21:29:21<00:24,  3.06s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

100%|█████████▉| 2061/2068 [21:33:26<05:40, 48.69s/it]

ENSG00000288210
ENSG00000288237
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

100%|█████████▉| 2065/2068 [21:38:04<02:40, 53.46s/it]

ENSG00000288329
ENSG00000288358
ENSG00000288367
hjsdghjag
ENSG00000288397
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

100%|█████████▉| 2065/2068 [21:38:22<02:40, 53.46s/it]

hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

100%|█████████▉| 2067/2068 [21:42:31<01:18, 78.69s/it]

ENSG00000288462
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag
hjsdghjag

100%|██████████| 2068/2068 [21:47:27<00:00, 37.93s/it]

import pickle

with open('/home/arnoldtl/go_terms_npinterv4_tarid_go_terms_safety_copy.pickle', 'wb') as handle:
    pickle.dump(go_terms_npinterv4_tarid_go_terms, handle, protocol=pickle.DEFAULT_PROTOCOL)

In [70]:
go_terms_npinterv4_tarid_go_terms

{'ENSG00000001631': ['GO:0005856',
  'GO:0050790',
  'GO:0005911',
  'GO:0005546',
  'GO:0005737',
  'GO:0008017',
  'GO:0005515',
  'GO:0045454',
  'GO:0005615',
  'GO:0005886',
  'GO:0030695',
  'GO:0001525',
  'GO:2000352',
  'GO:0016525',
  'GO:2000114',
  'GO:0007264',
  'GO:0001937',
  'GO:0010596',
  'GO:0033622'],
 'ENSG00000003756': ['GO:0006396',
  'GO:0000398',
  'GO:0005654',
  'GO:0003723',
  'GO:0005634',
  'GO:0046872',
  'GO:0003729',
  'GO:0003677',
  'GO:0005681',
  'GO:0043065',
  'GO:0005515',
  'GO:0006915',
  'GO:0000381',
  'GO:0000245',
  'GO:0008285'],
 'ENSG00000004478': ['GO:0005739',
  'GO:0070062',
  'GO:0061077',
  'GO:0048156',
  'GO:0031111',
  'GO:0003723',
  'GO:0031503',
  'GO:0006457',
  'GO:0005525',
  'GO:0032991',
  'GO:0031115',
  'GO:0005737',
  'GO:0005515',
  'GO:0030850',
  'GO:0005528',
  'GO:0003755',
  'GO:0007566',
  'GO:0044295',
  'GO:0035259',
  'GO:0010977',
  'GO:0032767',
  'GO:0005524',
  'GO:0043025',
  'GO:0005654',
  'GO:0006825',
  'GO:0005829',
  'GO:0005874',
  'GO:0030521',
  'GO:0051219',
  'GO:0000413',
  'GO:0031072',
  'GO:0046661',
  'GO:0030674',
  'GO:0006463',
  'GO:0048471'],
 'ENSG00000004487': ['GO:0043426',
  'GO:0035563',
  'GO:0045793',
  'GO:2000648',
  'GO:0002052',
  'GO:0000781',
  'GO:0032880',
  'GO:0005515',
  'GO:0006325',
  'GO:0051573',
  'GO:0010569',
  'GO:0016491',
  'GO:0032454',
  'GO:0002039',
  'GO:0034720',
  'GO:1990391',
  'GO:0006482',
  'GO:0071480',
  'GO:0043392',
  'GO:0032451',
  'GO:0061752',
  'GO:0019899',
  'GO:0140682',
  'GO:0051091',
  'GO:0043518',
  'GO:0005667',
  'GO:0000122',
  'GO:2000179',
  'GO:0055001',
  'GO:0050660',
  'GO:0005634',
  'GO:0050681',
  'GO:0061629',
  'GO:0043433',
  'GO:0046098',
  'GO:0032091',
  'GO:0006357',
  'GO:0090308',
  'GO:0120162',
  'GO:0010976',
  'GO:0000785',
  'GO:1990841',
  'GO:0032991',
  'GO:0045892',
  'GO:0003682',
  'GO:0034644',
  'GO:0060992',
  'GO:0042162',
  'GO:0042551',
  'GO:0060765',
  'GO:0000380',
  'GO:0005654',
  'GO:0033184',
  'GO:0045944',
  'GO:0021987',
  'GO:0051572',
  'GO:1902166',
  'GO:0032453',
  'GO:0032452',
  'GO:0033169',
  'GO:0030374',
  'GO:0008134',
  'GO:0071320',
  'GO:0140297'],
 'ENSG00000004534': ['GO:0006396',
  'GO:0000398',
  'GO:0005515',
  'GO:0003723',
  'GO:0005634',
  'GO:0003677'],
 'ENSG00000004700': ['GO:0005524',
  'GO:0003678',
  'GO:0032508',
  'GO:0005654',
  'GO:0043138',
  'GO:0006281',
  'GO:0005737',
  'GO:0000724',
  'GO:0005694',
  'GO:0005515',
  'GO:0016887',
  'GO:1990814',
  'GO:0006268',
  'GO:0016020',
  'GO:0005634',
  'GO:0009378',
  'GO:0006310'],
 'ENSG00000005007': ['GO:0000785',
  'GO:0003723',
  'GO:0000184',
  'GO:0006449',
  'GO:0036121',
  'GO:0000781',
  'GO:0005737',
  'GO:0071044',
  'GO:0005515',
  'GO:0061158',
  'GO:0003682',
  'GO:0016887',
  'GO:0044530',
  'GO:0042162',
  'GO:0032201',
  'GO:0008270',
  'GO:0000932',
  'GO:0004386',
  'GO:0006406',
  'GO:0071222',
  'GO:0005524',
  'GO:0032508',
  'GO:0000294',
  'GO:0005654',
  'GO:0006281',
  'GO:0005829',
  'GO:0009048',
  'GO:0035145',
  'GO:0000956',
  'GO:0003724',
  'GO:0006260',
  'GO:0032204',
  'GO:0071347',
  'GO:0061014',
  'GO:0005634',
  'GO:0044770',
  'GO:0044877'],
 'ENSG00000005421': ['GO:0070062',
  'GO:0032411',
  'GO:0046395',
  'GO:0046434',
  'GO:0004064',
  'GO:0016311',
  'GO:0005576',
  'GO:0005509',
  'GO:0102007',
  'GO:0070542',
  'GO:0005615',
  'GO:0034364',
  'GO:0034445',
  'GO:0008203',
  'GO:1902617',
  'GO:0005543',
  'GO:0072562',
  'GO:0034366',
  'GO:0042803',
  'GO:0019439',
  'GO:0043231',
  'GO:0046470',
  'GO:0031667',
  'GO:0004063',
  'GO:0009636',
  'GO:0010875',
  'GO:0051099'],
 'ENSG00000006712': ['GO:0001711',
  'GO:0010390',
  'GO:0034504',
  'GO:0071222',
  'GO:0005654',
  'GO:0030054',
  'GO:0016055',
  'GO:0031442',
  'GO:0005737',
  'GO:0000791',
  'GO:0005515',
  'GO:0003682',
  'GO:0000122',
  'GO:0031062',
  'GO:0033523',
  'GO:0016584',
  'GO:0006368',
  'GO:0045638',
  'GO:0016020',
  'GO:0016593',
  'GO:1902808',
  'GO:0000993',
  'GO:0019827',
  'GO:0006378'],
 'ENSG00000006744': ['GO:0005739',
  'GO:0004549',
  'GO:0005654',
  'GO:0005829',
  'GO:0003723',
  'GO:0042780',
  'GO:0005634',
  'GO:0046872',
  'GO:0042781',
  'GO:0016078',
  'GO:0004521',
  'GO:0005759',
  'GO:0072684',
  'GO:0090646',
  'GO:0042645'],
 'ENSG00000007372': ['GO:0071837',
  'GO:0002052',
  'GO:2000178',
  'GO:0007435',
  'GO:0009950',
  'GO:0001764',
  'GO:0005737',
  'GO:0007601',
  'GO:0005515',
  'GO:0007417',
  'GO:0009887',
  'GO:0001654',
  'GO:0061303',
  'GO:0035035',
  'GO:0009786',
  'GO:0000981',
  'GO:0042462',
  'GO:0048856',
  'GO:0010467',
  'GO:0019901',
  'GO:0009611',
  'GO:0021905',
  'GO:0032808',
  'GO:0033365',
  'GO:0021517',
  'GO:0000122',
  'GO:0021986',
  'GO:0003309',
  'GO:0030334',
  'GO:0048708',
  'GO:0005634',
  'GO:1990830',
  'GO:0007224',
  'GO:0001568',
  'GO:0048596',
  'GO:1990837',
  'GO:0006357',
  'GO:0000979',
  'GO:0001709',
  'GO:0000785',
  'GO:0021798',
  'GO:0003723',
  'GO:0030858',
  'GO:0001933',
  'GO:0000976',
  'GO:0003682',
  'GO:0001221',
  'GO:0003700',
  'GO:0000132',
  'GO:1904798',
  'GO:0060041',
  'GO:0003322',
  'GO:0070410',
  'GO:0061072',
  'GO:0048505',
  'GO:0002088',
  'GO:0045665',
  'GO:0070412',
  'GO:0010628',
  'GO:0021983',
  'GO:0050680',
  'GO:0000978',
  'GO:0001228',
  'GO:0005654',
  'GO:0005829',
  'GO:0045944',
  'GO:0030216',
  'GO:0021902',
  'GO:0001227',
  'GO:0042593',
  'GO:0007411',
  'GO:0023019',
  'GO:0048663',
  'GO:0003677',
  'GO:0031625',
  'GO:0021796',
  'GO:0045893',
  'GO:0050768',
  'GO:0021778'],
 'ENSG00000007392': ['GO:0006376',
  'GO:0042802',
  'GO:0050733',
  'GO:0003729',
  'GO:0005515',
  'GO:0071004',
  'GO:0045843',
  'GO:0005685'],
 'ENSG00000007908': ['GO:0004888',
  'GO:0030029',
  'GO:0002092',
  'GO:0050727',
  'GO:0033691',
  'GO:0034612',
  'GO:0005905',
  'GO:0005515',
  'GO:0005615',
  'GO:0043274',
  'GO:0009897',
  'GO:0070492',
  'GO:0050901',
  'GO:1903238',
  'GO:0005901',
  'GO:0007159',
  'GO:0005886',
  'GO:0045121',
  'GO:0007157',
  'GO:0030863',
  'GO:0046872',
  'GO:0005887',
  'GO:0007202',
  'GO:0002523',
  'GO:0032496',
  'GO:0019722',
  'GO:0034097',
  'GO:0070555',
  'GO:0006954',
  'GO:0048471'],
 'ENSG00000011243': ['GO:0005521',
  'GO:0000785',
  'GO:0006397',
  'GO:0007076',
  'GO:0003723',
  'GO:0045944',
  'GO:1990904',
  'GO:0005737',
  'GO:0005515',
  'GO:0031065',
  'GO:0051081',
  'GO:0044839',
  'GO:0016363',
  'GO:0008380',
  'GO:0017151',
  'GO:0005634',
  'GO:0046872',
  'GO:0003677',
  'GO:0042826',
  'GO:0034237',
  'GO:0016607',
  'GO:0016605',
  'GO:0010793',
  'GO:0033127'],
 'ENSG00000011304': ['GO:0070062',
  'GO:0075522',
  'GO:0006397',
  'GO:0005654',
  'GO:0003723',
  'GO:0003729',
  'GO:0043484',
  'GO:0005515',
  'GO:0008187',
  'GO:0000381',
  'GO:0005730',
  'GO:0048025',
  'GO:0008380',
  'GO:0033119',
  'GO:0070886',
  'GO:0016020',
  'GO:0005634',
  'GO:0051148',
  'GO:0045595',
  'GO:0035307',
  'GO:0036002'],
 'ENSG00000012048': ['GO:0003684',
  'GO:1990904',
  'GO:0005737',
  'GO:0005515',
  'GO:0051571',
  'GO:0051574',
  'GO:0000931',
  'GO:0035066',
  'GO:0051573',
  'GO:0000800',
  'GO:0005886',
  'GO:0004842',
  'GO:0070063',
  'GO:0071356',
  'GO:1990391',
  'GO:0016567',
  'GO:0071479',
  'GO:0000151',
  'GO:0070532',
  'GO:2000620',
  'GO:0006633',
  'GO:0045766',
  'GO:0044030',
  'GO:0019899',
  'GO:0033147',
  'GO:0043627',
  'GO:0045739',
  'GO:0006302',
  'GO:0070512',
  'GO:0005634',
  'GO:0006349',
  'GO:0070533',
  'GO:0015631',
  'GO:0031398',
  'GO:0046600',
  'GO:0006357',
  'GO:0010212',
  'GO:0000209',
  'GO:0051726',
  'GO:0003713',
  'GO:0008630',
  'GO:0003723',
  'GO:0085020',
  'GO:0000976',
  'GO:0032991',
  'GO:0016604',
  'GO:0010575',
  'GO:0045892',
  'GO:0005694',
  'GO:0043009',
  'GO:0006301',
  'GO:0008270',
  'GO:0051865',
  'GO:0010628',
  'GO:0045717',
  'GO:1902042',
  'GO:0007095',
  'GO:0005654',
  'GO:2000378',
  'GO:0000152',
  'GO:0045944',
  'GO:0009048',
  'GO:0000724',
  'GO:0070531',
  'GO:0071681',
  'GO:0007098',
  'GO:0051572',
  'GO:2000617',
  'GO:0035067',
  'GO:0007059',
  'GO:0003677',
  'GO:0031436',
  'GO:0031625',
  'GO:0045893'],
 'ENSG00000015479': ['GO:0016363',
  'GO:0042802',
  'GO:0045087',
  'GO:0016020',
  'GO:0035198',
  'GO:0003723',
  'GO:0005634',
  'GO:0010608',
  'GO:0002218',
  'GO:0005198',
  'GO:0003170',
  'GO:0005515',
  'GO:0008270',
  'GO:0003281',
  'GO:0005637'],
 'ENSG00000019549': ['GO:0014032',
  'GO:0033629',
  'GO:2000811',
  'GO:0000785',
  'GO:0005737',
  'GO:0050872',
  'GO:0005515',
  'GO:0035921',
  'GO:0003682',
  'GO:0035066',
  'GO:2000647',
  'GO:0070888',
  'GO:0032331',
  'GO:1902230',
  'GO:0006933',
  'GO:0090090',
  'GO:0032642',
  'GO:0000981',
  'GO:0000977',
  'GO:0043565',
  'GO:0071479',
  'GO:0010957',
  'GO:0010839',
  'GO:0007219',
  'GO:0045600',
  'GO:0071364',
  'GO:0000978',
  'GO:0005654',
  'GO:0043473',
  'GO:0060429',
  'GO:0045667',
  'GO:0003273',
  'GO:0003198',
  'GO:0060536',
  'GO:0070563',
  'GO:0043518',
  'GO:2001240',
  'GO:0000122',
  'GO:0001227',
  'GO:0006355',
  'GO:0060693',
  'GO:0060021',
  'GO:0001837',
  'GO:0003180',
  'GO:0005634',
  'GO:0046872',
  'GO:0061314',
  'GO:2000810',
  'GO:0001649',
  'GO:0030335',
  'GO:1990837',
  'GO:0007605'],
 'ENSG00000019991': ['GO:2000573',
  'GO:0042802',
  'GO:0005102',
  'GO:0043154',
  'GO:0044877',
  'GO:0060326',
  'GO:0043066',
  'GO:1900744',
  'GO:0060665',
  'GO:0005515',
  'GO:0031093',
  'GO:0005615',
  'GO:0042056',
  'GO:0045669',
  'GO:0016020',
  'GO:0050673',
  'GO:0004175',
  'GO:0043410',
  'GO:0032715',
  'GO:1901299',
  'GO:0014068',
  'GO:0004252',
  'GO:1902947',
  'GO:0006508',
  'GO:0090201',
  'GO:1902042',
  'GO:0005576',
  'GO:0031100',
  'GO:0045766',
  'GO:0001934',
  'GO:0008083',
  'GO:0050731',
  'GO:0070572',
  'GO:0045944',
  'GO:0033137',
  'GO:0010507',
  'GO:0048012',
  'GO:0050728',
  'GO:0001837',
  'GO:0000902',
  'GO:0031643',
  'GO:0050918',
  'GO:0001889',
  'GO:0030335',
  'GO:0032733',
  'GO:0051450',
  'GO:0035729',
  'GO:0000278'],
 'ENSG00000020633': ['GO:0000785',
  'GO:0071559',
  'GO:0005737',
  'GO:0005515',
  'GO:0002062',
  'GO:0001503',
  'GO:0003700',
  'GO:0043231',
  'GO:0000981',
  'GO:0045595',
  'GO:0000977',
  'GO:0030097',
  'GO:0050680',
  'GO:0005524',
  'GO:0043371',
  'GO:0000978',
  'GO:0048935',
  'GO:0005654',
  'GO:0005829',
  'GO:0045786',
  'GO:0006355',
  'GO:0000122',
  'GO:0001222',
  'GO:0030182',
  'GO:0006468',
  'GO:0005730',
  'GO:0043378',
  'GO:0005634',
  'GO:0016513',
  'GO:0045893',
  'GO:1990837',
  'GO:0006357'],
 'ENSG00000021776': ['GO:0016887',
  'GO:0005524',
  'GO:0034458',
  'GO:0000398',
  'GO:0071013',
  'GO:0003727',
  'GO:0005654',
  'GO:0016020',
  'GO:0003723',
  'GO:0005634',
  'GO:0003729',
  'GO:0005515',
  'GO:0071007'],
 'ENSG00000023608': ['GO:0000995',
  'GO:0042796',
  'GO:0042795',
  'GO:0005654',
  'GO:0016251',
  'GO:0043565',
  'GO:0005515',
  'GO:0005730',
  'GO:0019185'],
 'ENSG00000026025': ['GO:0070062',
  'GO:0005856',
  'GO:0042802',
  'GO:0060395',
  'GO:0043005',
  'GO:0005200',
  'GO:1990904',
  'GO:0005737',
  'GO:0014002',
  'GO:0005844',
  'GO:0005515',
  'GO:0060020',
  'GO:0005886',
  'GO:0019904',
  'GO:0005925',
  'GO:0016363',
  'GO:0030424',
  'GO:0071346',
  'GO:0005882',
  'GO:0010977',
  'GO:0005212',
  'GO:0032967',
  'GO:0045727',
  'GO:0005777',
  'GO:0045109',
  'GO:0097110',
  'GO:0071222',
  'GO:0005829',
  'GO:0043488',
  'GO:0045111',
  'GO:0045335',
  'GO:0070307',
  'GO:0071225',
  'GO:1990254',
  'GO:0031252',
  'GO:0005815',
  'GO:0003725'],
 'ENSG00000028137': ['GO:0005031',
  'GO:0008630',
  'GO:0097191',
  'GO:0003176',
  'GO:0035579',
  'GO:1902339',
  'GO:0003332',
  'GO:0005515',
  'GO:0002724',
  'GO:0150077',
  'GO:0005886',
  'GO:0045121',
  'GO:0016020',
  'GO:0043120',
  'GO:0051044',
  'GO:0033209',
  'GO:1901215',
  'GO:0071222',
  'GO:0016021',
  'GO:0006955',
  'GO:0007568',
  'GO:0043025',
  'GO:0005576',
  'GO:0050779',
  'GO:0010614',
  'GO:0150098',
  'GO:0060548',
  'GO:0006954',
  'GO:2001141',
  'GO:0071363',
  'GO:0042129',
  'GO:0150079',
  'GO:0005634',
  'GO:0048714',
  'GO:0031643',
  'GO:0031625',
  'GO:0043196',
  'GO:0048471',
  'GO:0002947',
  'GO:0002718',
  'GO:0003177',
  'GO:0031641'],
 'ENSG00000029363': ['GO:2001022',
  'GO:0005654',
  'GO:0003723',
  'GO:0043620',
  'GO:2000144',
  'GO:0045944',
  'GO:0005737',
  'GO:0045892',
  'GO:0005515',
  'GO:0006915',
  'GO:0016592',
  'GO:0003712',
  'GO:1990830',
  'GO:0005634',
  'GO:0003677',
  'GO:2001244',
  'GO:0043065',
  'GO:0016607'],
 'ENSG00000029993': ['GO:0045578',
  'GO:0003690',
  'GO:0045087',
  'GO:0045638',
  'GO:0003723',
  'GO:0005634',
  'GO:0000400',
  'GO:0032392',
  'GO:0005737',
  'GO:0005694',
  'GO:0005515',
  'GO:0006310',
  'GO:0008301',
  'GO:0006357'],
 'ENSG00000030582': ['GO:0070062',
  'GO:1903334',
  'GO:0003723',
  'GO:1903979',
  'GO:0005515',
  'GO:0005615',
  'GO:0050679',
  'GO:0005886',
  'GO:0016020',
  'GO:1905673',
  'GO:0051087',
  'GO:0007040',
  'GO:0050821',
  'GO:1905247',
  'GO:0005765',
  'GO:0007165',
  'GO:0010595',
  'GO:0005770',
  'GO:0005125',
  'GO:0005576',
  'GO:0002265',
  'GO:0045766',
  'GO:0005764',
  'GO:0008083',
  'GO:0007041',
  'GO:0005794',
  'GO:0050727',
  'GO:0002282',
  'GO:0005802',
  'GO:0048680',
  'GO:1902564',
  'GO:0005783',
  'GO:0043525',
  'GO:0035578',
  'GO:0106016',
  'GO:0060266',
  'GO:1900426',
  'GO:0005768',
  'GO:0043524',
  'GO:0030335',
  'GO:0007042'],
 'ENSG00000037474': ['GO:0005739',
  'GO:0070062',
  'GO:0048820',
  'GO:0062152',
  'GO:0005654',
  'GO:0003723',
  'GO:0006400',
  'GO:0008168',
  'GO:0036416',
  'GO:0005737',
  'GO:2000736',
  'GO:0080009',
  'GO:0005730',
  'GO:0016428',
  'GO:0001510',
  'GO:0005819',
  'GO:0030488',
  'GO:0033391',
  'GO:0005634',
  'GO:0000049',
  'GO:0001701',
  'GO:0007286',
  'GO:0033313',
  'GO:0010793',
  'GO:0051301'],
 'ENSG00000039123': ['GO:0005524',
  'GO:0005654',
  'GO:0003723',
  'GO:0000460',
  'GO:0016076',
  'GO:0005515',
  'GO:0003724',
  'GO:0005730',
  'GO:0016887',
  'GO:0006364',
  'GO:0006974',
  'GO:0000398',
  'GO:0071013',
  'GO:0005634',
  'GO:0016607',
  'GO:0031499',
  'GO:0006401'],
 'ENSG00000039650': ['GO:0005739',
  'GO:0051973',
  'GO:0003690',
  'GO:0051103',
  'GO:0005524',
  'GO:2001034',
  'GO:0000718',
  'GO:0005654',
  'GO:0006281',
  'GO:0003684',
  'GO:0006287',
  'GO:0004519',
  'GO:0006303',
  'GO:0005515',
  'GO:0009314',
  'GO:0005730',
  'GO:0046403',
  'GO:0090305',
  'GO:0006979',
  'GO:1904355',
  'GO:0046404',
  'GO:0016020',
  'GO:0005634',
  'GO:0010836',
  'GO:0035861',
  'GO:0017076',
  'GO:0006261',
  'GO:0046939',
  'GO:0032212',
  'GO:0098506'],
 'ENSG00000044574': ['GO:0042470',
  'GO:0005790',
  'GO:0005737',
  'GO:0005515',
  'GO:0021680',
  'GO:0031333',
  'GO:1901998',
  'GO:0030496',
  'GO:0016887',
  'GO:0005886',
  'GO:0019904',
  'GO:1903894',
  'GO:0051082',
  'GO:0051087',
  'GO:0043231',
  'GO:0045296',
  'GO:0051787',
  'GO:0051402',
  'GO:0071480',
  'GO:0030968',
  'GO:0005509',
  'GO:0005793',
  'GO:0005788',
  'GO:0031204',
  'GO:0019899',
  'GO:0034620',
  'GO:0006983',
  'GO:1903891',
  'GO:0021762',
  'GO:0071236',
  'GO:1904313',
  'GO:0042026',
  'GO:0005634',
  'GO:0060904',
  'GO:0043022',
  'GO:0031398',
  'GO:0051085',
  'GO:0005739',
  'GO:0030433',
  'GO:0010976',
  'GO:0030512',
  'GO:0001554',
  'GO:0035437',
  'GO:0070062',
  'GO:0021589',
  'GO:1903897',
  'GO:0043066',
  'GO:0034663',
  'GO:0071277',
  'GO:0032991',
  'GO:0005925',
  'GO:0030176',
  'GO:0016020',
  'GO:1990440',
  'GO:0005789',
  'GO:0071466',
  'GO:0005524',
  'GO:0005829',
  'GO:0071287',
  'GO:0009986',
  'GO:0071353',
  'GO:0030182',
  'GO:0034975',
  'GO:0005783',
  'GO:0042220',
  'GO:1903895',
  'GO:0031072',
  'GO:0097501',
  'GO:0071320',
  'GO:0031625',
  'GO:0030335',
  'GO:0042149',
  'GO:0044183',
  'GO:1990090'],
 'ENSG00000047346': ['GO:0005515'],
 'ENSG00000047410': ['GO:0034605',
  'GO:0005643',
  'GO:0031453',
  'GO:0010965',
  'GO:0003723',
  'GO:0031990',
  'GO:0003729',
  'GO:0032880',
  'GO:0005737',
  'GO:0006404',
  'GO:0005515',
  'GO:0090316',
  'GO:0042405',
  'GO:0003682',
  'GO:0005868',
  'GO:0043495',
  'GO:0035457',
  'GO:0051292',
  'GO:0044615',
  'GO:0051019',
  'GO:0031965',
  'GO:0006405',
  'GO:0046825',
  'GO:0072686',
  'GO:0042306',
  'GO:1901673',
  'GO:0007094',
  'GO:0010793',
  'GO:0046832',
  'GO:0070840',
  'GO:0006406',
  'GO:0070849',
  'GO:0005635',
  'GO:0005654',
  'GO:0006999',
  'GO:0043578',
  'GO:0046827',
  'GO:0090267',
  'GO:0006611',
  'GO:0006606',
  'GO:0000122',
  'GO:0031647',
  'GO:0034399',
  'GO:0017056',
  'GO:0031072',
  'GO:0019898',
  'GO:0045947',
  'GO:0042307',
  'GO:0042803',
  'GO:0005634',
  'GO:0000776',
  'GO:0015631',
  'GO:0051301'],
 'ENSG00000048052': ['GO:0007507',
  'GO:0016575',
  'GO:0005737',
  'GO:0045892',
  'GO:0005515',
  'GO:0032041',
  'GO:0006325',
  'GO:0000118',
  'GO:0048742',
  'GO:0042113',
  'GO:0035097',
  'GO:0051005',
  'GO:1990678',
  'GO:0051153',
  'GO:0003714',
  'GO:0005654',
  'GO:0032869',
  'GO:0042632',
  'GO:0005667',
  'GO:0030183',
  'GO:0000122',
  'GO:0070932',
  'GO:0070933',
  'GO:0034739',
  'GO:0008134',
  'GO:0090050',
  'GO:0034983',
  'GO:0033558',
  'GO:0001818',
  'GO:0005080',
  'GO:0005634',
  'GO:0046872',
  'GO:0042826',
  'GO:0061629',
  'GO:0004407',
  'GO:0140297',
  'GO:0006954'],
 'ENSG00000048828': ['GO:0005886',
  'GO:0016020',
  'GO:0005829',
  'GO:0003723',
  'GO:0005634'],
 'ENSG00000051180': ['GO:0005739',
  'GO:0000793',
  'GO:0003690',
  'GO:0010165',
  'GO:0000785',
  'GO:0042802',
  'GO:0051321',
  'GO:0000781',
  'GO:0032991',
  'GO:0005737',
  'GO:0000722',
  'GO:0005515',
  'GO:0005759',
  'GO:0003682',
  'GO:0006312',
  'GO:0010569',
  'GO:0000800',
  'GO:0006268',
  'GO:1990426',
  'GO:0036297',
  'GO:0007131',
  'GO:1990414',
  'GO:0072719',
  'GO:0070192',
  'GO:0000730',
  'GO:0072711',
  'GO:0008094',
  'GO:0006310',
  'GO:0009636',
  'GO:0017116',
  'GO:0071479',
  'GO:0072757',
  'GO:0003697',
  'GO:0071480',
  'GO:0016605',
  'GO:0005524',
  'GO:0001932',
  'GO:0031297',
  'GO:0005654',
  'GO:0006281',
  'GO:0000152',
  'GO:0009410',
  'GO:0000150',
  'GO:0019899',
  'GO:0000724',
  'GO:1904631',
  'GO:0006974',
  'GO:0070182',
  'GO:0000794',
  'GO:0005634',
  'GO:0000228',
  'GO:0035861',
  'GO:0042148',
  'GO:0005815',
  'GO:0010833',
  'GO:0051106',
  'GO:0008022',
  'GO:0048471'],
 'ENSG00000053372': ['GO:0006364',
  'GO:0000027',
  'GO:0003723',
  'GO:0005737',
  'GO:0000956',
  'GO:0030687',
  'GO:0005515',
  'GO:0042273',
  'GO:0005730'],
 'ENSG00000054118': ['GO:0070062',
  'GO:0000978',
  'GO:0005524',
  'GO:0003713',
  'GO:0042753',
  'GO:0006397',
  'GO:0048026',
  'GO:0003723',
  'GO:0005654',
  'GO:0046966',
  'GO:0045944',
  'GO:0007623',
  'GO:0000956',
  'GO:0005515',
  'GO:0051219',
  'GO:0000381',
  'GO:0016592',
  'GO:0003712',
  'GO:0030374',
  'GO:0008380',
  'GO:0005634',
  'GO:0003677',
  'GO:0016607',
  'GO:0045893',
  'GO:0048255',
  'GO:0042809'],
 'ENSG00000055917': ['GO:0035198',
  'GO:0005829',
  'GO:0003723',
  'GO:0006417',
  'GO:0043488',
  'GO:0003729',
  'GO:0005737',
  'GO:0034063',
  'GO:0005515',
  'GO:1900246',
  'GO:0010494',
  'GO:0060964',
  'GO:0003730',
  'GO:0035196',
  'GO:0010608',
  'GO:0031965',
  'GO:0051983',
  'GO:2000637',
  'GO:0048471'],
 'ENSG00000056972': ['GO:0061630',
  'GO:0005102',
  'GO:0007507',
  'GO:0110012',
  'GO:0001783',
  'GO:0005515',
  'GO:0042092',
  'GO:0002269',
  'GO:0001782',
  'GO:0002447',
  'GO:0048536',
  'GO:0002334',
  'GO:0070254',
  'GO:0042119',
  'GO:0006959',
  'GO:0001768',
  'GO:0070534',
  'GO:0033209',
  'GO:0038173',
  'GO:1990959',
  'GO:0023035',
  'GO:0009410',
  'GO:0005575',
  'GO:0048535',
  'GO:0031410',
  'GO:0006606',
  'GO:0097400',
  'GO:0002230',
  'GO:0001822',
  'GO:0035556',

In [75]:
go_terms_npinterv4_tarid_go_terms_df = pd.DataFrame({"ensg_npintertar": list(go_terms_npinterv4_tarid_go_terms.keys()), "go_terms": list(go_terms_npinterv4_tarid_go_terms.values())})
go_terms_npinterv4_tarid_go_terms_df

      ensg_npintertar                                           go_terms
0     ENSG00000001631  [GO:0005856, GO:0050790, GO:0005911, GO:000554...
1     ENSG00000003756  [GO:0006396, GO:0000398, GO:0005654, GO:000372...
2     ENSG00000004478  [GO:0005739, GO:0070062, GO:0061077, GO:004815...
3     ENSG00000004487  [GO:0043426, GO:0035563, GO:0045793, GO:200064...
4     ENSG00000004534  [GO:0006396, GO:0000398, GO:0005515, GO:000372...
...               ...                                                ...
2063  ENSG00000288329                                                NaN
2064  ENSG00000288358                                                NaN
2065  ENSG00000288367  [GO:0030154, GO:0000785, GO:0038183, GO:004589...
2066  ENSG00000288397  [GO:0061630, GO:0043398, GO:0048333, GO:014007...
2067  ENSG00000288462  [GO:0061630, GO:0043398, GO:0048333, GO:014007...

[2068 rows x 2 columns]

In [76]:
npinterv4_tarid_go_terms = npinterv4_tarid_go_terms.join(go_terms_npinterv4_tarid_go_terms_df.set_index("ensg_npintertar"), on="tarID_ensembl_code")
npinterv4_tarid_go_terms = npinterv4_tarid_go_terms[~npinterv4_tarid_go_terms["go_terms"].isnull()]
npinterv4_tarid_go_terms

,index,interID,ncName,ncID,ncType,tarName,tarID,tarType,interDescription,experiment,...,tissueOrCell,tag,class,level,datasource,ncID_rnacentral_code,ncID_ensembl_code,tarID_rnacentral_code,tarID_ensembl_code,go_terms
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,"[GO:0106140, GO:1901798, GO:0004860, GO:004280..."
1,7,ncRI-40000008,7SK,NONHSAG040596,lncRNA,Tat,P17735,protein,Tat efficiently replaces HEXIM1 on the 7SK snR...,-,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000198650,"[GO:0005739, GO:0006559, GO:0042802, GO:000582..."
2,8,ncRI-40000009,7SK,NONHSAG040596,lncRNA,CDK9,P50750,protein,Northern hybridization was performed to confir...,Northern Blot,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000136807,"[GO:0004712, GO:0051726, GO:0004672, GO:190365..."
3,9,ncRI-40000010,7SK,NONHSAG040596,lncRNA,PPP1CA,P62136,protein,PP2B and PP1alpha cooperatively disrupt 7SK sn...,-,...,-,regulatory,regulatory,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000172531,"[GO:0070062, GO:0032922, GO:0004721, GO:009864..."
4,10,ncRI-40000011,7SK,NONHSAG040596,lncRNA,PP2B,P62140,protein,PP2B and PP1alpha cooperatively disrupt 7SK sn...,-,...,-,regulatory,regulatory,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000213639,"[GO:0070062, GO:0032922, GO:0019901, GO:000565..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487270,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF3F1E,ENSG00000255717,"[GO:0061630, GO:0043398, GO:0048333, GO:014007..."
487271,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF4F8E,ENSG00000255717,"[GO:0061630, GO:0043398, GO:0048333, GO:014007..."
487272,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF5E17,ENSG00000255717,"[GO:0061630, GO:0043398, GO:0048333, GO:014007..."
487273,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6AE6,ENSG00000255717,"[GO:0061630, GO:0043398, GO:0048333, GO:014007..."
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,"[GO:0061630, GO:0043398, GO:0048333, GO:014007..."

In [77]:
npinterv4_tarid_go_terms = npinterv4_tarid_go_terms.explode('go_terms')
npinterv4_tarid_go_terms

,index,interID,ncName,ncID,ncType,tarName,tarID,tarType,interDescription,experiment,...,tissueOrCell,tag,class,level,datasource,ncID_rnacentral_code,ncID_ensembl_code,tarID_rnacentral_code,tarID_ensembl_code,go_terms
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0106140
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:1901798
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0004860
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0042802
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0007507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,GO:0035522
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,GO:0035455
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,GO:0006995
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,GO:0005852
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,GO:0070315

In [81]:
npinterv4_tarid_go_terms = npinterv4_tarid_go_terms[npinterv4_tarid_go_terms["go_terms"] != 'GO:0120259']
npinterv4_tarid_go_terms

,index,interID,ncName,ncID,ncType,tarName,tarID,tarType,interDescription,experiment,...,tissueOrCell,tag,class,level,datasource,ncID_rnacentral_code,ncID_ensembl_code,tarID_rnacentral_code,tarID_ensembl_code,go_terms
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0106140
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:1901798
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0004860
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0042802
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0007507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,GO:0035522
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,GO:0035455
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,GO:0006995
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,GO:0005852
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,GO:0070315

In [ ]:
for go_term in np.unique(npinterv4_tarid_go_terms["go_terms"]):
    try:
        obodag[go_term]
    except KeyError:
        print(go_term)

In [ ]:
print("ksdhkg")

##### Save file

In [ ]:
npinterv4_tarid_go_terms_df = pd.DataFrame({
    0: ["NPInter"] * len(npinterv4_tarid_go_terms),
    1: npinterv4_tarid_go_terms["tarID_ensembl_code"],
    2: list(npinterv4_tarid_go_terms.join(ensembl_gene_gene_name.set_index("Gene stable ID"), on="tarID_ensembl_code")["Gene name"].astype("str")),
    3: ["enables"]  * len(npinterv4_tarid_go_terms),
    4: npinterv4_tarid_go_terms["go_terms"],
    5: ["NPInter"] * len(npinterv4_tarid_go_terms),
    6: ["EXP"] * len(npinterv4_tarid_go_terms),
    7: ["NPInter"] * len(npinterv4_tarid_go_terms),
    8: [np.nan if go_term not in list(obodag.keys()) else "P" if obodag[go_term].namespace == "biological_process" else "F" if obodag[go_term].namespace == "molecular_function" else "C" for go_term in npinterv4_tarid_go_terms_v2["go_terms"]], 
    9: [np.nan if go_term not in list(obodag.keys()) else obodag[go_term].name for go_term in npinterv4_tarid_go_terms["go_terms"]],
    10: list(npinterv4_tarid_go_terms.join(ensembl_gene_gene_name.set_index("Gene stable ID"), on="tarID_ensembl_code")["Gene name"].astype("str")),
    11: ["ncRNA"] * len(npinterv4_tarid_go_terms),
    12: ["taxon:9606"] * len(npinterv4_tarid_go_terms),
    13: ["NPInter"] * len(npinterv4_tarid_go_terms),
    14: ["NPInter"] * len(npinterv4_tarid_go_terms),
    15: [np.nan] * len(npinterv4_tarid_go_terms),
    16: [np.nan] * len(npinterv4_tarid_go_terms)
})

npinterv4_tarid_go_terms_df

In [ ]:
npinterv4_tarid_go_terms_df = npinterv4_tarid_go_terms_df[~npinterv4_tarid_go_terms_df[8].isnull()]
npinterv4_tarid_go_terms_df

In [ ]:
from itertools import islice
with open('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human.gaf', "r") as myfile:
    head = list(islice(myfile, 41))
head

In [ ]:
# always remember, use files in a with statement
with open('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_npinter_tar_ensembl_gene_mapping.gaf', "w") as f2:
    for item in head:
        f2.write(item)

In [ ]:
npinterv4_tarid_go_terms_df.to_csv('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_npinter_tar_ensembl_gene_mapping.gaf', mode="a", sep="\t", header=False, index=False)

#### V2 - Only direct target

In [96]:
npinterv4_tarid_go_terms_v2 = npinterv4_tarid.copy()
npinterv4_tarid_go_terms_v2

,index,interID,ncName,ncID,ncType,tarName,tarID,tarType,interDescription,experiment,...,organism,tissueOrCell,tag,class,level,datasource,ncID_rnacentral_code,ncID_ensembl_code,tarID_rnacentral_code,tarID_ensembl_code
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834
1,7,ncRI-40000008,7SK,NONHSAG040596,lncRNA,Tat,P17735,protein,Tat efficiently replaces HEXIM1 on the 7SK snR...,-,...,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000198650
2,8,ncRI-40000009,7SK,NONHSAG040596,lncRNA,CDK9,P50750,protein,Northern hybridization was performed to confir...,Northern Blot,...,Homo sapiens,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000136807
3,9,ncRI-40000010,7SK,NONHSAG040596,lncRNA,PPP1CA,P62136,protein,PP2B and PP1alpha cooperatively disrupt 7SK sn...,-,...,Homo sapiens,-,regulatory,regulatory,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000172531
4,10,ncRI-40000011,7SK,NONHSAG040596,lncRNA,PP2B,P62140,protein,PP2B and PP1alpha cooperatively disrupt 7SK sn...,-,...,Homo sapiens,-,regulatory,regulatory,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000213639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487273,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,Homo sapiens,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6AE6,ENSG00000255717
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,Homo sapiens,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717
487275,1100458,ncRI-41100460,SNORD117,ENSG00000266295,snoRNA,SNORA5C,ENSG00000201772,snoRNA,RNA-RNA interaction from RISE database,LIGRseq,...,Homo sapiens,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS00002F13BD,ENSG00000266295,URS000072157F,ENSG00000201772
487276,1100459,ncRI-41100461,U6,ENSG00000278140,snoRNA,SNORA79,ENSG00000222489,snRNA,RNA-RNA interaction from RISE database,LIGRseq,...,Homo sapiens,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS0000671B81,ENSG00000278140,URS0000704142,ENSG00000222489
487277,1100460,ncRI-41100462,SNORD56,ENSG00000200753,snoRNA,SNORA7B,ENSG00000207088,snoRNA,RNA-RNA interaction from RISE database,LIGRseq,...,Homo sapiens,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000006D2A0,ENSG00000200753,URS00006F6999,ENSG00000207088

In [93]:
go_terms_npinterv4_tarid_go_terms_v2 = {}

for unique_tarid in tqdm(np.unique(npinterv4_tarid_go_terms["tarID_ensembl_code"])):
        
    tarID_ensembl_codes = set()
    tarID_ensembl_codes.add(unique_tarid)
    #go_terms = set()
    
    print(unique_tarid)

    #tarID_ensembl_codes = set(np.unique(npinterv4_tarid_go_terms[npinterv4_tarid_go_terms["ncID_ensembl_code"] == unique_tarid]["tarID_ensembl_code"]))
    #break
    #for tarID_ensembl_code in tarID_ensembl_codes:
    go_terms = set(gaf[gaf[1] == unique_tarid][4])
    
    if len(go_terms) > 0:
        go_terms_npinterv4_tarid_go_terms_v2[unique_tarid] = list(go_terms)
    else:
        go_terms_npinterv4_tarid_go_terms_v2[unique_tarid] = np.nan

  0%|          | 6/1375 [00:00<00:49, 27.52it/s]

ENSG00000001631
ENSG00000003756
ENSG00000004478
ENSG00000004487
ENSG00000004534
ENSG00000004700
ENSG00000005007

  1%|          | 12/1375 [00:00<00:49, 27.73it/s]

ENSG00000005421
ENSG00000006712
ENSG00000006744
ENSG00000007372
ENSG00000007392
ENSG00000007908
ENSG00000011243

  1%|▏         | 18/1375 [00:00<00:50, 26.87it/s]

ENSG00000011304
ENSG00000012048
ENSG00000015479
ENSG00000019549
ENSG00000019991
ENSG00000020633
ENSG00000021776

  2%|▏         | 27/1375 [00:00<00:48, 27.56it/s]

ENSG00000023608
ENSG00000026025
ENSG00000028137
ENSG00000029363
ENSG00000029993
ENSG00000030582
ENSG00000037474

  2%|▏         | 33/1375 [00:01<00:48, 27.79it/s]

ENSG00000039123
ENSG00000039650
ENSG00000044574
ENSG00000047346
ENSG00000047410
ENSG00000048052
ENSG00000048828

  3%|▎         | 39/1375 [00:01<00:48, 27.30it/s]

ENSG00000051180
ENSG00000053372
ENSG00000054118
ENSG00000055917
ENSG00000056972
ENSG00000058085
ENSG00000058673

  3%|▎         | 48/1375 [00:01<00:48, 27.58it/s]

ENSG00000060138
ENSG00000060339
ENSG00000060688
ENSG00000062822
ENSG00000063244
ENSG00000064012
ENSG00000064300

  4%|▍         | 54/1375 [00:01<00:49, 26.66it/s]

ENSG00000064607
ENSG00000064703
ENSG00000065526
ENSG00000065978
ENSG00000066044
ENSG00000066135
ENSG00000067596

  4%|▍         | 60/1375 [00:02<00:48, 27.02it/s]

ENSG00000067900
ENSG00000068394
ENSG00000070756
ENSG00000071082
ENSG00000071243
ENSG00000071626
ENSG00000071794

  5%|▌         | 69/1375 [00:02<00:48, 26.86it/s]

ENSG00000071859
ENSG00000071894
ENSG00000072501
ENSG00000073111
ENSG00000073282
ENSG00000073792
ENSG00000074211

  5%|▌         | 75/1375 [00:02<00:47, 27.35it/s]

ENSG00000074266
ENSG00000074356
ENSG00000075292
ENSG00000075618
ENSG00000075856
ENSG00000076003
ENSG00000076924

  6%|▌         | 81/1375 [00:02<00:46, 27.59it/s]

ENSG00000077235
ENSG00000077312
ENSG00000077348
ENSG00000079246
ENSG00000079739
ENSG00000079785

  6%|▋         | 87/1375 [00:03<00:48, 26.45it/s]

ENSG00000080503
ENSG00000082068
ENSG00000082153
ENSG00000082516
ENSG00000082898
ENSG00000083312
ENSG00000083520

  7%|▋         | 96/1375 [00:03<00:46, 27.37it/s]

ENSG00000083896
ENSG00000084463
ENSG00000085117
ENSG00000085662
ENSG00000085872
ENSG00000086475
ENSG00000086589

  7%|▋         | 102/1375 [00:03<00:47, 26.91it/s]

ENSG00000087087
ENSG00000087088
ENSG00000087152
ENSG00000087245
ENSG00000087302
ENSG00000087365
ENSG00000087470

  8%|▊         | 108/1375 [00:03<00:46, 27.37it/s]

ENSG00000088247
ENSG00000088305
ENSG00000088826
ENSG00000088930
ENSG00000088986
ENSG00000089220
ENSG00000089250

  9%|▊         | 117/1375 [00:04<00:46, 26.77it/s]

ENSG00000089280
ENSG00000089737
ENSG00000090861
ENSG00000090889
ENSG00000090905
ENSG00000091831
ENSG00000092199

  9%|▉         | 123/1375 [00:04<00:47, 26.41it/s]

ENSG00000092201
ENSG00000092847
ENSG00000095002
ENSG00000095015
ENSG00000095380
ENSG00000095564
ENSG00000095752

  9%|▉         | 129/1375 [00:04<00:46, 26.81it/s]

ENSG00000096150
ENSG00000096401
ENSG00000096717
ENSG00000096746
ENSG00000099622
ENSG00000099783
ENSG00000099995

 10%|█         | 138/1375 [00:05<00:46, 26.41it/s]

ENSG00000100109
ENSG00000100220
ENSG00000100227
ENSG00000100234
ENSG00000100297
ENSG00000100307
ENSG00000100316

 10%|█         | 144/1375 [00:05<00:45, 26.91it/s]

ENSG00000100320
ENSG00000100353
ENSG00000100393
ENSG00000100403
ENSG00000100603
ENSG00000100644
ENSG00000100722

 11%|█         | 150/1375 [00:05<00:45, 27.19it/s]

ENSG00000100813
ENSG00000100823
ENSG00000100836
ENSG00000100941
ENSG00000100985
ENSG00000101138
ENSG00000101161

 12%|█▏        | 159/1375 [00:05<00:44, 27.22it/s]

ENSG00000101197
ENSG00000101199
ENSG00000101230
ENSG00000101266
ENSG00000101343
ENSG00000101367
ENSG00000101412

 12%|█▏        | 165/1375 [00:06<00:44, 27.47it/s]

ENSG00000101413
ENSG00000101444
ENSG00000101489
ENSG00000101654
ENSG00000101811
ENSG00000101871
ENSG00000101966

 12%|█▏        | 171/1375 [00:06<00:45, 26.59it/s]

ENSG00000102054
ENSG00000102081
ENSG00000102103
ENSG00000102974
ENSG00000103034
ENSG00000103275
ENSG00000103549

 13%|█▎        | 177/1375 [00:06<00:46, 25.61it/s]

ENSG00000104321
ENSG00000104356
ENSG00000104419
ENSG00000104738
ENSG00000104824
ENSG00000104852

 14%|█▎        | 186/1375 [00:06<00:44, 26.85it/s]

ENSG00000104881
ENSG00000104885
ENSG00000104897
ENSG00000105011
ENSG00000105127
ENSG00000105171
ENSG00000105202

 14%|█▍        | 192/1375 [00:07<00:43, 27.22it/s]

ENSG00000105221
ENSG00000105323
ENSG00000105327
ENSG00000105447
ENSG00000105810
ENSG00000105976
ENSG00000106299

 14%|█▍        | 198/1375 [00:07<00:45, 25.99it/s]

ENSG00000106366
ENSG00000106462
ENSG00000106628
ENSG00000106682
ENSG00000106992
ENSG00000107105

 15%|█▍        | 204/1375 [00:07<00:45, 25.83it/s]

ENSG00000107164
ENSG00000107404
ENSG00000107796
ENSG00000107831
ENSG00000107929
ENSG00000107937
ENSG00000107949

 15%|█▌        | 213/1375 [00:07<00:43, 26.95it/s]

ENSG00000107951
ENSG00000107984
ENSG00000108055
ENSG00000108518
ENSG00000108654
ENSG00000108848
ENSG00000108883

 16%|█▌        | 219/1375 [00:08<00:43, 26.38it/s]

ENSG00000108961
ENSG00000109111
ENSG00000109320
ENSG00000109534
ENSG00000109606
ENSG00000109670
ENSG00000110107

 16%|█▋        | 225/1375 [00:08<00:42, 26.97it/s]

ENSG00000110321
ENSG00000110367
ENSG00000110700
ENSG00000111011
ENSG00000111087
ENSG00000111142
ENSG00000111144

 17%|█▋        | 234/1375 [00:08<00:42, 26.76it/s]

ENSG00000111276
ENSG00000111364
ENSG00000111424
ENSG00000111530
ENSG00000111605
ENSG00000111642
ENSG00000111667

 17%|█▋        | 240/1375 [00:08<00:41, 27.20it/s]

ENSG00000111669
ENSG00000111679
ENSG00000111716
ENSG00000111786
ENSG00000111859
ENSG00000112081
ENSG00000112096

 18%|█▊        | 246/1375 [00:09<00:42, 26.58it/s]

ENSG00000112118
ENSG00000112159
ENSG00000112182
ENSG00000112183
ENSG00000112242
ENSG00000112306
ENSG00000112531

 19%|█▊        | 255/1375 [00:09<00:42, 26.58it/s]

ENSG00000112715
ENSG00000112739
ENSG00000113141
ENSG00000113360
ENSG00000113387
ENSG00000113558
ENSG00000113649

 19%|█▉        | 261/1375 [00:09<00:41, 27.04it/s]

ENSG00000113658
ENSG00000114062
ENSG00000114416
ENSG00000114503
ENSG00000114867
ENSG00000115053
ENSG00000115138

 19%|█▉        | 267/1375 [00:09<00:41, 26.45it/s]

ENSG00000115414
ENSG00000115415
ENSG00000115524
ENSG00000115825
ENSG00000115875
ENSG00000116001
ENSG00000116017

 20%|██        | 276/1375 [00:10<00:40, 27.23it/s]

ENSG00000116062
ENSG00000116251
ENSG00000116350
ENSG00000116560
ENSG00000116747
ENSG00000116750
ENSG00000116752

 21%|██        | 282/1375 [00:10<00:40, 26.81it/s]

ENSG00000116754
ENSG00000116833
ENSG00000117360
ENSG00000117569
ENSG00000117592
ENSG00000117748
ENSG00000118058

 21%|██        | 288/1375 [00:10<00:39, 27.22it/s]

ENSG00000118197
ENSG00000118246
ENSG00000118260
ENSG00000118513
ENSG00000118971
ENSG00000119203
ENSG00000119335

 22%|██▏       | 297/1375 [00:11<00:40, 26.91it/s]

ENSG00000119596
ENSG00000119707
ENSG00000119772
ENSG00000119953
ENSG00000120217
ENSG00000120265
ENSG00000120802

 22%|██▏       | 303/1375 [00:11<00:40, 26.60it/s]

ENSG00000120948
ENSG00000121058
ENSG00000121390
ENSG00000121774
ENSG00000121807
ENSG00000121858
ENSG00000121892

 22%|██▏       | 309/1375 [00:11<00:39, 26.97it/s]

ENSG00000122257
ENSG00000122359
ENSG00000122406
ENSG00000122565
ENSG00000122566
ENSG00000122692
ENSG00000122877

 23%|██▎       | 318/1375 [00:11<00:39, 26.92it/s]

ENSG00000123064
ENSG00000123136
ENSG00000123144
ENSG00000123200
ENSG00000123908
ENSG00000124160
ENSG00000124193

 24%|██▎       | 324/1375 [00:12<00:38, 27.19it/s]

ENSG00000124207
ENSG00000124214
ENSG00000124216
ENSG00000124562
ENSG00000124570
ENSG00000124571
ENSG00000124614

 24%|██▍       | 330/1375 [00:12<00:38, 26.96it/s]

ENSG00000124762
ENSG00000124766
ENSG00000124795
ENSG00000125398
ENSG00000125484
ENSG00000125538
ENSG00000125651

 25%|██▍       | 339/1375 [00:12<00:37, 27.38it/s]

ENSG00000125686
ENSG00000125691
ENSG00000125743
ENSG00000125755
ENSG00000125820
ENSG00000125835
ENSG00000125944

 25%|██▌       | 345/1375 [00:12<00:37, 27.14it/s]

ENSG00000126070
ENSG00000126261
ENSG00000126457
ENSG00000126524
ENSG00000126581
ENSG00000126698
ENSG00000126749

 26%|██▌       | 351/1375 [00:13<00:37, 27.04it/s]

ENSG00000126945
ENSG00000127445
ENSG00000127616
ENSG00000128191
ENSG00000128708
ENSG00000128739
ENSG00000129245

 26%|██▌       | 360/1375 [00:13<00:37, 26.85it/s]

ENSG00000129351
ENSG00000129473
ENSG00000129514
ENSG00000130234
ENSG00000130254
ENSG00000130396
ENSG00000130427

 27%|██▋       | 366/1375 [00:13<00:38, 25.89it/s]

ENSG00000130600
ENSG00000130707
ENSG00000130725
ENSG00000130726
ENSG00000130811
ENSG00000130816
ENSG00000130826
ENSG00000130985

 27%|██▋       | 375/1375 [00:13<00:37, 26.58it/s]

ENSG00000131013
ENSG00000131023
ENSG00000131051
ENSG00000131467
ENSG00000131469
ENSG00000131747
ENSG00000131876

 28%|██▊       | 381/1375 [00:14<00:37, 26.62it/s]

ENSG00000131914
ENSG00000131981
ENSG00000132153
ENSG00000132341
ENSG00000132383
ENSG00000132463

 28%|██▊       | 387/1375 [00:14<00:38, 25.88it/s]

ENSG00000132485
ENSG00000132507
ENSG00000132646
ENSG00000132780
ENSG00000132792
ENSG00000132970
ENSG00000133121

 29%|██▊       | 393/1375 [00:14<00:36, 26.72it/s]

ENSG00000133226
ENSG00000133703
ENSG00000133740
ENSG00000133858
ENSG00000134013
ENSG00000134186
ENSG00000134283

 29%|██▉       | 402/1375 [00:14<00:36, 27.01it/s]

ENSG00000134287
ENSG00000134323
ENSG00000134371
ENSG00000134419
ENSG00000134453
ENSG00000134698
ENSG00000134748

 30%|██▉       | 408/1375 [00:15<00:36, 26.59it/s]

ENSG00000135069
ENSG00000135097
ENSG00000135218
ENSG00000135316
ENSG00000135486
ENSG00000135679
ENSG00000135870

 30%|███       | 414/1375 [00:15<00:35, 27.11it/s]

ENSG00000136231
ENSG00000136270
ENSG00000136450
ENSG00000136527
ENSG00000136542
ENSG00000136709
ENSG00000136807

 31%|███       | 423/1375 [00:15<00:35, 26.91it/s]

ENSG00000136810
ENSG00000136813
ENSG00000136937
ENSG00000136938
ENSG00000136997
ENSG00000137154
ENSG00000137168

 31%|███       | 429/1375 [00:15<00:34, 27.25it/s]

ENSG00000137309
ENSG00000137393
ENSG00000137449
ENSG00000137497
ENSG00000137656
ENSG00000137752
ENSG00000137776

 32%|███▏      | 435/1375 [00:16<00:35, 26.84it/s]

ENSG00000138279
ENSG00000138336
ENSG00000138385
ENSG00000138398
ENSG00000138413
ENSG00000138668
ENSG00000138772

 32%|███▏      | 444/1375 [00:16<00:34, 26.64it/s]

ENSG00000138795
ENSG00000139343
ENSG00000139546
ENSG00000139636
ENSG00000139687
ENSG00000139746
ENSG00000139793

 33%|███▎      | 450/1375 [00:16<00:34, 27.12it/s]

ENSG00000139842
ENSG00000140259
ENSG00000140319
ENSG00000140350
ENSG00000140505
ENSG00000140525
ENSG00000140718

 33%|███▎      | 456/1375 [00:16<00:34, 26.64it/s]

ENSG00000141425
ENSG00000141448
ENSG00000141510
ENSG00000141543
ENSG00000141646
ENSG00000142192
ENSG00000142515

 34%|███▍      | 465/1375 [00:17<00:35, 25.73it/s]

ENSG00000142534
ENSG00000142546
ENSG00000142864
ENSG00000142937
ENSG00000143190
ENSG00000143321
ENSG00000143368

 34%|███▍      | 471/1375 [00:17<00:34, 26.58it/s]

ENSG00000143578
ENSG00000143621
ENSG00000143727
ENSG00000143799
ENSG00000143889
ENSG00000143977
ENSG00000144028

 35%|███▍      | 477/1375 [00:17<00:33, 27.06it/s]

ENSG00000144713
ENSG00000144852
ENSG00000145216
ENSG00000145365
ENSG00000145425
ENSG00000145833
ENSG00000146648

 35%|███▌      | 486/1375 [00:18<00:32, 26.96it/s]

ENSG00000146674
ENSG00000146834
ENSG00000146963
ENSG00000147140
ENSG00000147274
ENSG00000147403
ENSG00000147604

 36%|███▌      | 492/1375 [00:18<00:33, 26.63it/s]

ENSG00000147649
ENSG00000147677
ENSG00000147852
ENSG00000147883
ENSG00000148303
ENSG00000148516
ENSG00000148688

 36%|███▌      | 498/1375 [00:18<00:32, 27.08it/s]

ENSG00000148700
ENSG00000148773
ENSG00000149136
ENSG00000149273
ENSG00000149532
ENSG00000149658
ENSG00000149925

 37%|███▋      | 507/1375 [00:18<00:33, 26.01it/s]

ENSG00000149948
ENSG00000150093
ENSG00000150316
ENSG00000150459
ENSG00000150593
ENSG00000150907
ENSG00000151892

 37%|███▋      | 513/1375 [00:19<00:32, 26.53it/s]

ENSG00000151923
ENSG00000152192
ENSG00000152464
ENSG00000152601
ENSG00000152795
ENSG00000153147
ENSG00000153187

 38%|███▊      | 519/1375 [00:19<00:32, 26.47it/s]

ENSG00000153922
ENSG00000154473
ENSG00000154736
ENSG00000155816
ENSG00000155827
ENSG00000155858
ENSG00000156076

 38%|███▊      | 528/1375 [00:19<00:31, 27.03it/s]

ENSG00000156427
ENSG00000156482
ENSG00000156502
ENSG00000157110
ENSG00000157764
ENSG00000157837
ENSG00000158019

 39%|███▉      | 534/1375 [00:19<00:30, 27.20it/s]

ENSG00000158545
ENSG00000158773
ENSG00000158859
ENSG00000159140
ENSG00000159217
ENSG00000159346
ENSG00000160201

 39%|███▉      | 540/1375 [00:20<00:30, 26.99it/s]

ENSG00000160633
ENSG00000160710
ENSG00000160712
ENSG00000160752
ENSG00000160789
ENSG00000160917
ENSG00000161526

 40%|███▉      | 549/1375 [00:20<00:30, 27.42it/s]

ENSG00000161547
ENSG00000161813
ENSG00000161970
ENSG00000162231
ENSG00000162385
ENSG00000162664
ENSG00000162692

 40%|████      | 555/1375 [00:20<00:29, 27.38it/s]

ENSG00000162711
ENSG00000162775
ENSG00000162924
ENSG00000163161
ENSG00000163191
ENSG00000163597
ENSG00000163655

 41%|████      | 561/1375 [00:20<00:29, 27.52it/s]

ENSG00000163694
ENSG00000163714
ENSG00000163877
ENSG00000163931
ENSG00000163938
ENSG00000163950
ENSG00000163993

 41%|████▏     | 570/1375 [00:21<00:29, 26.93it/s]

ENSG00000164047
ENSG00000164091
ENSG00000164104
ENSG00000164109
ENSG00000164111
ENSG00000164167
ENSG00000164252

 42%|████▏     | 576/1375 [00:21<00:29, 27.09it/s]

ENSG00000164305
ENSG00000164362
ENSG00000164548
ENSG00000164587
ENSG00000164690
ENSG00000164778
ENSG00000164867

 42%|████▏     | 582/1375 [00:21<00:29, 27.17it/s]

ENSG00000164902
ENSG00000164924
ENSG00000164938
ENSG00000164944
ENSG00000165119
ENSG00000165732
ENSG00000165795

 43%|████▎     | 588/1375 [00:21<00:29, 27.11it/s]

ENSG00000165819
ENSG00000165934
ENSG00000166197
ENSG00000166508
ENSG00000166949
ENSG00000167005

 43%|████▎     | 597/1375 [00:22<00:29, 26.61it/s]

ENSG00000167081
ENSG00000167088
ENSG00000167323
ENSG00000167721
ENSG00000167978
ENSG00000167986
ENSG00000168002

 44%|████▍     | 603/1375 [00:22<00:28, 27.04it/s]

ENSG00000168036
ENSG00000168066
ENSG00000168267
ENSG00000168394
ENSG00000168438
ENSG00000168496
ENSG00000168564

 44%|████▍     | 609/1375 [00:22<00:28, 27.32it/s]

ENSG00000168610
ENSG00000168743
ENSG00000168769
ENSG00000168883
ENSG00000168906
ENSG00000169035

 45%|████▍     | 615/1375 [00:22<00:28, 26.46it/s]

ENSG00000169045
ENSG00000169083
ENSG00000169554
ENSG00000169564
ENSG00000169567
ENSG00000169813
ENSG00000169908

 45%|████▌     | 624/1375 [00:23<00:27, 27.17it/s]

ENSG00000170027
ENSG00000170144
ENSG00000170312
ENSG00000170345
ENSG00000170515
ENSG00000170606
ENSG00000171056

 46%|████▌     | 630/1375 [00:23<00:27, 27.41it/s]

ENSG00000171314
ENSG00000171566
ENSG00000171791
ENSG00000171862
ENSG00000171863
ENSG00000171960
ENSG00000172009

 46%|████▋     | 636/1375 [00:23<00:27, 26.50it/s]

ENSG00000172062
ENSG00000172179
ENSG00000172336
ENSG00000172531
ENSG00000172757
ENSG00000172977
ENSG00000173039

 47%|████▋     | 645/1375 [00:24<00:26, 27.29it/s]

ENSG00000173545
ENSG00000173702
ENSG00000173812
ENSG00000173846
ENSG00000173933
ENSG00000174231
ENSG00000174243

 47%|████▋     | 651/1375 [00:24<00:26, 27.44it/s]

ENSG00000174365
ENSG00000174444
ENSG00000174720
ENSG00000175029
ENSG00000175197
ENSG00000175390
ENSG00000175467

 48%|████▊     | 657/1375 [00:24<00:27, 26.58it/s]

ENSG00000176102
ENSG00000176124
ENSG00000176593
ENSG00000176697
ENSG00000176884
ENSG00000176890
ENSG00000177000

 48%|████▊     | 666/1375 [00:24<00:25, 27.28it/s]

ENSG00000177150
ENSG00000177192
ENSG00000177613
ENSG00000177733
ENSG00000177822
ENSG00000177885
ENSG00000178585

 49%|████▉     | 672/1375 [00:25<00:25, 27.36it/s]

ENSG00000178691
ENSG00000178718
ENSG00000178950
ENSG00000179051
ENSG00000180198
ENSG00000180233
ENSG00000180543

 49%|████▉     | 678/1375 [00:25<00:26, 26.60it/s]

ENSG00000181163
ENSG00000181555
ENSG00000182004
ENSG00000182718
ENSG00000182774
ENSG00000182809
ENSG00000182872

 50%|████▉     | 687/1375 [00:25<00:25, 27.31it/s]

ENSG00000182944
ENSG00000183207
ENSG00000183258
ENSG00000183431
ENSG00000183808
ENSG00000184634
ENSG00000184937

 50%|█████     | 693/1375 [00:25<00:25, 26.44it/s]

ENSG00000185245
ENSG00000185591
ENSG00000186416
ENSG00000186566
ENSG00000186834
ENSG00000187098
ENSG00000187555

 51%|█████     | 699/1375 [00:26<00:24, 27.05it/s]

ENSG00000187605
ENSG00000187621
ENSG00000187735
ENSG00000187772
ENSG00000188342
ENSG00000188529
ENSG00000189091

 51%|█████▏    | 708/1375 [00:26<00:24, 27.42it/s]

ENSG00000189403
ENSG00000196154
ENSG00000196235
ENSG00000196361
ENSG00000196363
ENSG00000196419
ENSG00000196591

 52%|█████▏    | 714/1375 [00:26<00:24, 26.81it/s]

ENSG00000196712
ENSG00000197043
ENSG00000197111
ENSG00000197157
ENSG00000197182
ENSG00000197934
ENSG00000197989

 52%|█████▏    | 720/1375 [00:26<00:23, 27.31it/s]

ENSG00000198034
ENSG00000198231
ENSG00000198242
ENSG00000198382
ENSG00000198492
ENSG00000198496
ENSG00000198563

 53%|█████▎    | 729/1375 [00:27<00:24, 26.83it/s]

ENSG00000198590
ENSG00000198650
ENSG00000198730
ENSG00000198755
ENSG00000198793
ENSG00000198805
ENSG00000198900
ENSG00000198972

 53%|█████▎    | 735/1375 [00:27<00:23, 27.30it/s]

ENSG00000198973
ENSG00000198974
ENSG00000198975
ENSG00000198983
ENSG00000198995
ENSG00000198997
ENSG00000199001

 54%|█████▍    | 744/1375 [00:27<00:23, 26.65it/s]

ENSG00000199005
ENSG00000199015
ENSG00000199017
ENSG00000199020
ENSG00000199023
ENSG00000199024
ENSG00000199030
ENSG00000199031
ENSG00000199032

 55%|█████▍    | 753/1375 [00:28<00:22, 27.36it/s]

ENSG00000199038
ENSG00000199043
ENSG00000199047
ENSG00000199051
ENSG00000199053
ENSG00000199059
ENSG00000199072
ENSG00000199075
ENSG00000199077

 55%|█████▌    | 762/1375 [00:28<00:22, 27.12it/s]

ENSG00000199080
ENSG00000199082
ENSG00000199085
ENSG00000199088
ENSG00000199095
ENSG00000199104
ENSG00000199121
ENSG00000199122

 56%|█████▌    | 768/1375 [00:28<00:22, 27.46it/s]

ENSG00000199127
ENSG00000199130
ENSG00000199132
ENSG00000199133
ENSG00000199135
ENSG00000199143
ENSG00000199145

 57%|█████▋    | 777/1375 [00:28<00:22, 27.12it/s]

ENSG00000199150
ENSG00000199153
ENSG00000199156
ENSG00000199158
ENSG00000199161
ENSG00000199165
ENSG00000199168
ENSG00000199169
ENSG00000199172

 57%|█████▋    | 786/1375 [00:29<00:21, 26.92it/s]

ENSG00000199177
ENSG00000199179
ENSG00000199347
ENSG00000200087
ENSG00000202111
ENSG00000202198
ENSG00000202515
ENSG00000202566

 58%|█████▊    | 792/1375 [00:29<00:21, 27.27it/s]

ENSG00000202569
ENSG00000202609
ENSG00000203867
ENSG00000203993
ENSG00000204054
ENSG00000204217
ENSG00000204371

 58%|█████▊    | 801/1375 [00:29<00:21, 27.15it/s]

ENSG00000204388
ENSG00000204560
ENSG00000204569
ENSG00000204628
ENSG00000204842
ENSG00000204977
ENSG00000205323

 59%|█████▊    | 807/1375 [00:30<00:20, 27.33it/s]

ENSG00000205571
ENSG00000205937
ENSG00000206297
ENSG00000206376
ENSG00000206394
ENSG00000206486
ENSG00000206489

 59%|█████▉    | 813/1375 [00:30<00:20, 27.32it/s]

ENSG00000206585
ENSG00000207110
ENSG00000207205
ENSG00000207340
ENSG00000207349
ENSG00000207546
ENSG00000207547

 60%|█████▉    | 822/1375 [00:30<00:20, 27.60it/s]

ENSG00000207548
ENSG00000207550
ENSG00000207559
ENSG00000207562
ENSG00000207563
ENSG00000207568
ENSG00000207571

 60%|██████    | 831/1375 [00:30<00:19, 27.62it/s]

ENSG00000207575
ENSG00000207580
ENSG00000207581
ENSG00000207582
ENSG00000207587
ENSG00000207589
ENSG00000207595
ENSG00000207598
ENSG00000207600
ENSG00000207604

 61%|██████    | 837/1375 [00:31<00:19, 27.56it/s]

ENSG00000207607
ENSG00000207609
ENSG00000207611
ENSG00000207613
ENSG00000207614
ENSG00000207624
ENSG00000207627

 62%|██████▏   | 846/1375 [00:31<00:19, 27.73it/s]

ENSG00000207638
ENSG00000207639
ENSG00000207645
ENSG00000207649
ENSG00000207651
ENSG00000207654
ENSG00000207698

 62%|██████▏   | 855/1375 [00:31<00:18, 27.92it/s]

ENSG00000207705
ENSG00000207708
ENSG00000207713
ENSG00000207721
ENSG00000207725
ENSG00000207726
ENSG00000207728
ENSG00000207730
ENSG00000207731

 63%|██████▎   | 864/1375 [00:32<00:18, 27.90it/s]

ENSG00000207732
ENSG00000207735
ENSG00000207738
ENSG00000207741
ENSG00000207742
ENSG00000207744
ENSG00000207757
ENSG00000207758
ENSG00000207759
ENSG00000207761
ENSG00000207768

 63%|██████▎   | 873/1375 [00:32<00:17, 27.96it/s]

ENSG00000207779
ENSG00000207781
ENSG00000207782
ENSG00000207784
ENSG00000207789
ENSG00000207798
ENSG00000207803
ENSG00000207805

 64%|██████▍   | 879/1375 [00:32<00:17, 27.95it/s]

ENSG00000207808
ENSG00000207811
ENSG00000207813
ENSG00000207820
ENSG00000207827
ENSG00000207864
ENSG00000207870

 65%|██████▍   | 888/1375 [00:32<00:17, 27.79it/s]

ENSG00000207923
ENSG00000207924
ENSG00000207927
ENSG00000207932
ENSG00000207933
ENSG00000207935
ENSG00000207938
ENSG00000207942

 65%|██████▌   | 894/1375 [00:33<00:18, 26.30it/s]

ENSG00000207943
ENSG00000207944
ENSG00000207947
ENSG00000207948
ENSG00000207952
ENSG00000207954

 65%|██████▌   | 900/1375 [00:33<00:17, 27.04it/s]

ENSG00000207962
ENSG00000207965
ENSG00000207971
ENSG00000207973
ENSG00000207974
ENSG00000207975
ENSG00000207978

 66%|██████▌   | 909/1375 [00:33<00:16, 27.49it/s]

ENSG00000207979
ENSG00000207980
ENSG00000207982
ENSG00000207983
ENSG00000207990
ENSG00000207994
ENSG00000207996

 67%|██████▋   | 915/1375 [00:33<00:16, 27.59it/s]

ENSG00000208006
ENSG00000208008
ENSG00000208009
ENSG00000208013
ENSG00000208015
ENSG00000208017
ENSG00000208023
ENSG00000208027

 67%|██████▋   | 924/1375 [00:34<00:16, 27.00it/s]

ENSG00000208032
ENSG00000208036
ENSG00000210741
ENSG00000211137
ENSG00000211514
ENSG00000211520
ENSG00000211563
ENSG00000211574

 68%|██████▊   | 930/1375 [00:34<00:16, 27.46it/s]

ENSG00000211578
ENSG00000211579
ENSG00000211581
ENSG00000211997
ENSG00000212017
ENSG00000212027
ENSG00000212102

 68%|██████▊   | 939/1375 [00:34<00:15, 27.75it/s]

ENSG00000212719
ENSG00000212866
ENSG00000213551
ENSG00000213639
ENSG00000213719
ENSG00000213782
ENSG00000213853
ENSG00000213981

 69%|██████▊   | 945/1375 [00:35<00:16, 26.22it/s]

ENSG00000214274
ENSG00000214353
ENSG00000214753
ENSG00000215301
ENSG00000215425
ENSG00000215930

 69%|██████▉   | 951/1375 [00:35<00:15, 26.99it/s]

ENSG00000215938
ENSG00000215939
ENSG00000215957
ENSG00000216005
ENSG00000216009
ENSG00000216031
ENSG00000216069

 70%|██████▉   | 960/1375 [00:35<00:14, 27.71it/s]

ENSG00000216101
ENSG00000216192
ENSG00000221017
ENSG00000221033
ENSG00000221052
ENSG00000221176
ENSG00000221265
ENSG00000221369

 70%|███████   | 966/1375 [00:35<00:14, 27.92it/s]

ENSG00000221371
ENSG00000221400
ENSG00000221421
ENSG00000221463
ENSG00000221464
ENSG00000221525

 71%|███████   | 972/1375 [00:36<00:15, 26.68it/s]

ENSG00000221537
ENSG00000221545
ENSG00000221552
ENSG00000221585
ENSG00000221586
ENSG00000221594
ENSG00000221650

 71%|███████▏  | 981/1375 [00:36<00:14, 27.53it/s]

ENSG00000221669
ENSG00000221697
ENSG00000221754
ENSG00000221783
ENSG00000221817
ENSG00000222071
ENSG00000222321

 72%|███████▏  | 990/1375 [00:36<00:13, 27.76it/s]

ENSG00000222958
ENSG00000223367
ENSG00000223639
ENSG00000223960
ENSG00000224086
ENSG00000224165
ENSG00000224212
ENSG00000224424
ENSG00000224501

 72%|███████▏  | 996/1375 [00:36<00:14, 26.85it/s]

ENSG00000224699
ENSG00000224794
ENSG00000225073
ENSG00000225335
ENSG00000225342
ENSG00000225725
ENSG00000225859

 73%|███████▎  | 1002/1375 [00:37<00:13, 27.27it/s]

ENSG00000226026
ENSG00000226171
ENSG00000226173
ENSG00000226225
ENSG00000226248
ENSG00000226417
ENSG00000226419

 74%|███████▎  | 1011/1375 [00:37<00:13, 27.67it/s]

ENSG00000226651
ENSG00000226746
ENSG00000226891
ENSG00000226950
ENSG00000227061
ENSG00000227195
ENSG00000227214

 74%|███████▍  | 1017/1375 [00:37<00:14, 25.34it/s]

ENSG00000227333
ENSG00000227769
ENSG00000227804
ENSG00000227816
ENSG00000227953
ENSG00000228630
ENSG00000228794

 74%|███████▍  | 1023/1375 [00:37<00:13, 26.37it/s]

ENSG00000228809
ENSG00000228812
ENSG00000228925
ENSG00000229496
ENSG00000230427
ENSG00000230500
ENSG00000230624

 75%|███████▌  | 1032/1375 [00:38<00:12, 27.14it/s]

ENSG00000230685
ENSG00000230705
ENSG00000230937
ENSG00000230995
ENSG00000231064
ENSG00000231154
ENSG00000231290
ENSG00000231377

 75%|███████▌  | 1038/1375 [00:38<00:12, 26.52it/s]

ENSG00000231500
ENSG00000231555
ENSG00000231638
ENSG00000231737
ENSG00000231889
ENSG00000232045
ENSG00000232057

 76%|███████▌  | 1047/1375 [00:38<00:12, 27.03it/s]

ENSG00000232367
ENSG00000232564
ENSG00000232756
ENSG00000232804
ENSG00000232807
ENSG00000232913
ENSG00000233002

 77%|███████▋  | 1053/1375 [00:39<00:11, 27.27it/s]

ENSG00000233049
ENSG00000233144
ENSG00000233223
ENSG00000233360
ENSG00000233418
ENSG00000233452
ENSG00000233485
ENSG00000233561

 77%|███████▋  | 1062/1375 [00:39<00:11, 27.03it/s]

ENSG00000233581
ENSG00000233871
ENSG00000234222
ENSG00000234377
ENSG00000234741
ENSG00000234883
ENSG00000234899

 78%|███████▊  | 1068/1375 [00:39<00:11, 27.37it/s]

ENSG00000235291
ENSG00000235437
ENSG00000235439
ENSG00000235513
ENSG00000235650
ENSG00000235706
ENSG00000235724
ENSG00000235726

 78%|███████▊  | 1077/1375 [00:39<00:11, 26.86it/s]

ENSG00000235749
ENSG00000235865
ENSG00000236088
ENSG00000236759
ENSG00000236882
ENSG00000237017
ENSG00000237070
ENSG00000237187
ENSG00000237479

 79%|███████▉  | 1086/1375 [00:40<00:10, 27.21it/s]

ENSG00000237945
ENSG00000238020
ENSG00000238104
ENSG00000238133
ENSG00000238134
ENSG00000238140
ENSG00000238279
ENSG00000238531

 79%|███████▉  | 1092/1375 [00:40<00:10, 26.71it/s]

ENSG00000238728
ENSG00000238795
ENSG00000239002
ENSG00000239118
ENSG00000239306
ENSG00000239865
ENSG00000239927

 80%|████████  | 1101/1375 [00:40<00:10, 27.23it/s]

ENSG00000241345
ENSG00000241370
ENSG00000241779
ENSG00000241863
ENSG00000242726
ENSG00000243009
ENSG00000243766
ENSG00000244040

 81%|████████  | 1107/1375 [00:41<00:09, 26.82it/s]

ENSG00000244161
ENSG00000244383
ENSG00000244462
ENSG00000244513
ENSG00000244879
ENSG00000245552
ENSG00000245910

 81%|████████  | 1113/1375 [00:41<00:09, 27.23it/s]

ENSG00000245928
ENSG00000246273
ENSG00000246731
ENSG00000246740
ENSG00000246889
ENSG00000247092

 82%|████████▏ | 1122/1375 [00:41<00:09, 26.51it/s]

ENSG00000247271
ENSG00000247324
ENSG00000247416
ENSG00000247556
ENSG00000247735
ENSG00000247809
ENSG00000248333

 82%|████████▏ | 1128/1375 [00:41<00:09, 27.09it/s]

ENSG00000248801
ENSG00000249635
ENSG00000249695
ENSG00000249915
ENSG00000250012
ENSG00000250091
ENSG00000250131
ENSG00000250410

 82%|████████▏ | 1134/1375 [00:42<00:08, 27.44it/s]

ENSG00000250988
ENSG00000251002
ENSG00000251562
ENSG00000251856
ENSG00000252466
ENSG00000252824

 83%|████████▎ | 1143/1375 [00:42<00:08, 27.84it/s]

ENSG00000253563
ENSG00000253636
ENSG00000253706
ENSG00000253729
ENSG00000254324
ENSG00000254635
ENSG00000254911
ENSG00000255240

 84%|████████▎ | 1149/1375 [00:42<00:08, 27.87it/s]

ENSG00000255389
ENSG00000255394
ENSG00000255399
ENSG00000255559
ENSG00000255717
ENSG00000256925
ENSG00000257176

 84%|████████▍ | 1158/1375 [00:42<00:07, 28.01it/s]

ENSG00000257337
ENSG00000257681
ENSG00000258643
ENSG00000258657
ENSG00000258891
ENSG00000259073
ENSG00000259163
ENSG00000259602

 85%|████████▍ | 1164/1375 [00:43<00:07, 28.01it/s]

ENSG00000259663
ENSG00000259709
ENSG00000260005
ENSG00000260027
ENSG00000260034
ENSG00000260213
ENSG00000260495

 85%|████████▌ | 1173/1375 [00:43<00:07, 28.02it/s]

ENSG00000260565
ENSG00000260719
ENSG00000260855
ENSG00000260969
ENSG00000261441
ENSG00000261659
ENSG00000261668
ENSG00000261693

 86%|████████▌ | 1179/1375 [00:43<00:07, 27.99it/s]

ENSG00000261762
ENSG00000261822
ENSG00000262732
ENSG00000262833
ENSG00000263001
ENSG00000263345
ENSG00000263414

 86%|████████▋ | 1188/1375 [00:43<00:06, 28.03it/s]

ENSG00000263476
ENSG00000263528
ENSG00000263586
ENSG00000263823
ENSG00000263908
ENSG00000264419
ENSG00000264513

 87%|████████▋ | 1197/1375 [00:44<00:06, 26.43it/s]

ENSG00000264559
ENSG00000264589
ENSG00000264607
ENSG00000264725
ENSG00000264739
ENSG00000264763
ENSG00000264788
ENSG00000264823
ENSG00000264864
ENSG00000264940

 87%|████████▋ | 1203/1375 [00:44<00:06, 27.12it/s]

ENSG00000265005
ENSG00000265194
ENSG00000265215
ENSG00000265237
ENSG00000265241
ENSG00000265333
ENSG00000265537

 88%|████████▊ | 1212/1375 [00:44<00:05, 27.76it/s]

ENSG00000265681
ENSG00000265725
ENSG00000265873
ENSG00000265932
ENSG00000266192
ENSG00000266291
ENSG00000266297

 89%|████████▉ | 1221/1375 [00:45<00:05, 26.86it/s]

ENSG00000266396
ENSG00000266423
ENSG00000266680
ENSG00000267177
ENSG00000267192
ENSG00000267195
ENSG00000267200
ENSG00000267322
ENSG00000267383
ENSG00000267532

 89%|████████▉ | 1227/1375 [00:45<00:05, 27.26it/s]

ENSG00000267551
ENSG00000267560
ENSG00000267750
ENSG00000267751
ENSG00000267801
ENSG00000268119
ENSG00000268575

 90%|████████▉ | 1236/1375 [00:45<00:05, 27.75it/s]

ENSG00000268686
ENSG00000269821
ENSG00000269834
ENSG00000269858
ENSG00000270049
ENSG00000270641
ENSG00000270647

 90%|█████████ | 1242/1375 [00:45<00:05, 26.29it/s]

ENSG00000270722
ENSG00000271335
ENSG00000271886
ENSG00000272036
ENSG00000272356
ENSG00000272405
ENSG00000272702

 91%|█████████ | 1248/1375 [00:46<00:04, 27.01it/s]

ENSG00000273761
ENSG00000273772
ENSG00000273899
ENSG00000274442
ENSG00000275272
ENSG00000275349
ENSG00000275453

 91%|█████████▏| 1257/1375 [00:46<00:04, 27.64it/s]

ENSG00000275538
ENSG00000275620
ENSG00000276365
ENSG00000276404
ENSG00000276833
ENSG00000277564
ENSG00000277757

 92%|█████████▏| 1263/1375 [00:46<00:04, 26.24it/s]

ENSG00000277773
ENSG00000277918
ENSG00000278140
ENSG00000278229
ENSG00000279080
ENSG00000279110
ENSG00000279159
ENSG00000279317

 93%|█████████▎| 1272/1375 [00:47<00:03, 27.37it/s]

ENSG00000279467
ENSG00000280548
ENSG00000280607
ENSG00000280734
ENSG00000280858
ENSG00000281103
ENSG00000281398
ENSG00000281516
ENSG00000281540

 93%|█████████▎| 1281/1375 [00:47<00:03, 27.86it/s]

ENSG00000281696
ENSG00000282685
ENSG00000282947
ENSG00000282958
ENSG00000283152
ENSG00000283200
ENSG00000283289
ENSG00000283344
ENSG00000283429

 94%|█████████▍| 1290/1375 [00:47<00:03, 27.24it/s]

ENSG00000283475
ENSG00000283498
ENSG00000283519
ENSG00000283550
ENSG00000283556
ENSG00000283588
ENSG00000283604
ENSG00000283705

 94%|█████████▍| 1296/1375 [00:47<00:02, 27.65it/s]

ENSG00000283733
ENSG00000283736
ENSG00000283745
ENSG00000283762
ENSG00000283774
ENSG00000283785
ENSG00000283797

 95%|█████████▍| 1305/1375 [00:48<00:02, 26.90it/s]

ENSG00000283799
ENSG00000283803
ENSG00000283815
ENSG00000283819
ENSG00000283824
ENSG00000283844
ENSG00000283857
ENSG00000283871
ENSG00000283891

 96%|█████████▌| 1314/1375 [00:48<00:02, 27.68it/s]

ENSG00000283904
ENSG00000283926
ENSG00000283931
ENSG00000283935
ENSG00000283936
ENSG00000283958
ENSG00000284010
ENSG00000284027
ENSG00000284032

 96%|█████████▌| 1323/1375 [00:48<00:01, 27.25it/s]

ENSG00000284038
ENSG00000284040
ENSG00000284043
ENSG00000284107
ENSG00000284112
ENSG00000284125
ENSG00000284155
ENSG00000284157

 97%|█████████▋| 1329/1375 [00:49<00:01, 26.99it/s]

ENSG00000284163
ENSG00000284179
ENSG00000284182
ENSG00000284190
ENSG00000284191
ENSG00000284202
ENSG00000284203

 97%|█████████▋| 1338/1375 [00:49<00:01, 26.95it/s]

ENSG00000284204
ENSG00000284214
ENSG00000284231
ENSG00000284254
ENSG00000284321
ENSG00000284353
ENSG00000284357
ENSG00000284363

 98%|█████████▊| 1344/1375 [00:49<00:01, 27.33it/s]

ENSG00000284375
ENSG00000284378
ENSG00000284399
ENSG00000284419
ENSG00000284433
ENSG00000284440
ENSG00000284443

 98%|█████████▊| 1353/1375 [00:50<00:00, 26.95it/s]

ENSG00000284453
ENSG00000284458
ENSG00000284459
ENSG00000284463
ENSG00000284464
ENSG00000284485
ENSG00000284503
ENSG00000284520

 99%|█████████▉| 1359/1375 [00:50<00:00, 27.29it/s]

ENSG00000284536
ENSG00000284538
ENSG00000284564
ENSG00000284565
ENSG00000284567
ENSG00000284586
ENSG00000285049

 99%|█████████▉| 1368/1375 [00:50<00:00, 26.92it/s]

ENSG00000285056
ENSG00000285161
ENSG00000285317
ENSG00000285438
ENSG00000288121
ENSG00000288130
ENSG00000288145

100%|██████████| 1375/1375 [00:50<00:00, 27.04it/s]

ENSG00000288183
ENSG00000288210
ENSG00000288237
ENSG00000288367
ENSG00000288397
ENSG00000288462

In [94]:
go_terms_npinterv4_tarid_go_terms_v2

{'ENSG00000001631': ['GO:0005856',
  'GO:0005737',
  'GO:0008017',
  'GO:0005515',
  'GO:0045454',
  'GO:0005615',
  'GO:0005886',
  'GO:2000114',
  'GO:0001937',
  'GO:0010596',
  'GO:0050790',
  'GO:0005911',
  'GO:0005546',
  'GO:0030695',
  'GO:0001525',
  'GO:2000352',
  'GO:0016525',
  'GO:0007264',
  'GO:0033622'],
 'ENSG00000003756': ['GO:0006396',
  'GO:0000398',
  'GO:0005654',
  'GO:0003723',
  'GO:0005634',
  'GO:0046872',
  'GO:0003729',
  'GO:0003677',
  'GO:0005681',
  'GO:0043065',
  'GO:0005515',
  'GO:0006915',
  'GO:0000381',
  'GO:0000245',
  'GO:0008285'],
 'ENSG00000004478': ['GO:0005739',
  'GO:0070062',
  'GO:0061077',
  'GO:0048156',
  'GO:0031111',
  'GO:0003723',
  'GO:0031503',
  'GO:0006457',
  'GO:0005525',
  'GO:0032991',
  'GO:0031115',
  'GO:0005737',
  'GO:0005515',
  'GO:0030850',
  'GO:0005528',
  'GO:0003755',
  'GO:0007566',
  'GO:0044295',
  'GO:0035259',
  'GO:0010977',
  'GO:0032767',
  'GO:0005524',
  'GO:0043025',
  'GO:0005654',
  'GO:0006825',
  'GO:0005829',
  'GO:0005874',
  'GO:0030521',
  'GO:0051219',
  'GO:0000413',
  'GO:0031072',
  'GO:0046661',
  'GO:0030674',
  'GO:0006463',
  'GO:0048471'],
 'ENSG00000004487': ['GO:0090308',
  'GO:0120162',
  'GO:0010976',
  'GO:0043426',
  'GO:0035563',
  'GO:0045793',
  'GO:1990841',
  'GO:2000648',
  'GO:0002052',
  'GO:0000785',
  'GO:0000781',
  'GO:0032880',
  'GO:0032991',
  'GO:0045892',
  'GO:0005515',
  'GO:0003682',
  'GO:0006325',
  'GO:0051573',
  'GO:0010569',
  'GO:0034644',
  'GO:0016491',
  'GO:0032454',
  'GO:0042162',
  'GO:0002039',
  'GO:0060992',
  'GO:0034720',
  'GO:0042551',
  'GO:1990391',
  'GO:0006482',
  'GO:0060765',
  'GO:0000380',
  'GO:0071480',
  'GO:0043392',
  'GO:0032451',
  'GO:0061752',
  'GO:0005654',
  'GO:0033184',
  'GO:0045944',
  'GO:0021987',
  'GO:0019899',
  'GO:0140682',
  'GO:0051091',
  'GO:0043518',
  'GO:0005667',
  'GO:0000122',
  'GO:0051572',
  'GO:2000179',
  'GO:1902166',
  'GO:0032453',
  'GO:0032452',
  'GO:0033169',
  'GO:0030374',
  'GO:0008134',
  'GO:0055001',
  'GO:0050660',
  'GO:0005634',
  'GO:0050681',
  'GO:0061629',
  'GO:0043433',
  'GO:0046098',
  'GO:0071320',
  'GO:0032091',
  'GO:0140297',
  'GO:0006357'],
 'ENSG00000004534': ['GO:0006396',
  'GO:0000398',
  'GO:0003723',
  'GO:0005634',
  'GO:0003677',
  'GO:0005515'],
 'ENSG00000004700': ['GO:0016887',
  'GO:1990814',
  'GO:0005524',
  'GO:0006268',
  'GO:0003678',
  'GO:0032508',
  'GO:0016020',
  'GO:0005654',
  'GO:0043138',
  'GO:0005634',
  'GO:0006281',
  'GO:0005737',
  'GO:0000724',
  'GO:0009378',
  'GO:0005515',
  'GO:0006310',
  'GO:0005694'],
 'ENSG00000005007': ['GO:0000785',
  'GO:0003723',
  'GO:0000184',
  'GO:0006449',
  'GO:0036121',
  'GO:0000781',
  'GO:0005737',
  'GO:0071044',
  'GO:0005515',
  'GO:0061158',
  'GO:0003682',
  'GO:0016887',
  'GO:0044530',
  'GO:0042162',
  'GO:0032201',
  'GO:0008270',
  'GO:0000932',
  'GO:0004386',
  'GO:0006406',
  'GO:0071222',
  'GO:0005524',
  'GO:0032508',
  'GO:0000294',
  'GO:0005654',
  'GO:0006281',
  'GO:0005829',
  'GO:0009048',
  'GO:0035145',
  'GO:0000956',
  'GO:0003724',
  'GO:0006260',
  'GO:0032204',
  'GO:0071347',
  'GO:0061014',
  'GO:0005634',
  'GO:0044770',
  'GO:0044877'],
 'ENSG00000005421': ['GO:0070062',
  'GO:0032411',
  'GO:0046395',
  'GO:0046434',
  'GO:0004064',
  'GO:0070542',
  'GO:0005615',
  'GO:0034445',
  'GO:0008203',
  'GO:1902617',
  'GO:0034366',
  'GO:0043231',
  'GO:0046470',
  'GO:0031667',
  'GO:0009636',
  'GO:0051099',
  'GO:0010875',
  'GO:0016311',
  'GO:0005576',
  'GO:0005509',
  'GO:0102007',
  'GO:0034364',
  'GO:0005543',
  'GO:0072562',
  'GO:0042803',
  'GO:0019439',
  'GO:0004063'],
 'ENSG00000006712': ['GO:0001711',
  'GO:0010390',
  'GO:0034504',
  'GO:0030054',
  'GO:0031442',
  'GO:0005737',
  'GO:0000791',
  'GO:0005515',
  'GO:0003682',
  'GO:0031062',
  'GO:0045638',
  'GO:0016020',
  'GO:1902808',
  'GO:0019827',
  'GO:0006378',
  'GO:0071222',
  'GO:0005654',
  'GO:0016055',
  'GO:0000122',
  'GO:0033523',
  'GO:0016584',
  'GO:0006368',
  'GO:0016593',
  'GO:0000993'],
 'ENSG00000006744': ['GO:0005739',
  'GO:0004549',
  'GO:0005654',
  'GO:0005829',
  'GO:0003723',
  'GO:0042780',
  'GO:0005634',
  'GO:0046872',
  'GO:0042781',
  'GO:0016078',
  'GO:0004521',
  'GO:0005759',
  'GO:0072684',
  'GO:0090646',
  'GO:0042645'],
 'ENSG00000007372': ['GO:0071837',
  'GO:0002052',
  'GO:2000178',
  'GO:0007435',
  'GO:0009950',
  'GO:0005737',
  'GO:0005515',
  'GO:0007417',
  'GO:0035035',
  'GO:0009786',
  'GO:0010467',
  'GO:0019901',
  'GO:0009611',
  'GO:0021905',
  'GO:0032808',
  'GO:0048708',
  'GO:0005634',
  'GO:0007224',
  'GO:0001568',
  'GO:0000979',
  'GO:0000785',
  'GO:0021798',
  'GO:0003723',
  'GO:0000976',
  'GO:0003700',
  'GO:0000132',
  'GO:1904798',
  'GO:0003322',
  'GO:0070410',
  'GO:0002088',
  'GO:0001228',
  'GO:0005654',
  'GO:0045944',
  'GO:0030216',
  'GO:0021902',
  'GO:0007411',
  'GO:0048663',
  'GO:0001764',
  'GO:0007601',
  'GO:0009887',
  'GO:0001654',
  'GO:0061303',
  'GO:0000981',
  'GO:0042462',
  'GO:0048856',
  'GO:0033365',
  'GO:0021517',
  'GO:0000122',
  'GO:0021986',
  'GO:0003309',
  'GO:0030334',
  'GO:1990830',
  'GO:0048596',
  'GO:1990837',
  'GO:0006357',
  'GO:0001709',
  'GO:0030858',
  'GO:0001933',
  'GO:0003682',
  'GO:0001221',
  'GO:0060041',
  'GO:0061072',
  'GO:0048505',
  'GO:0045665',
  'GO:0070412',
  'GO:0010628',
  'GO:0021983',
  'GO:0050680',
  'GO:0000978',
  'GO:0005829',
  'GO:0001227',
  'GO:0042593',
  'GO:0023019',
  'GO:0003677',
  'GO:0031625',
  'GO:0021796',
  'GO:0045893',
  'GO:0050768',
  'GO:0021778'],
 'ENSG00000007392': ['GO:0006376',
  'GO:0042802',
  'GO:0050733',
  'GO:0003729',
  'GO:0005515',
  'GO:0071004',
  'GO:0045843',
  'GO:0005685'],
 'ENSG00000007908': ['GO:0004888',
  'GO:0002092',
  'GO:0033691',
  'GO:0034612',
  'GO:0005515',
  'GO:0005615',
  'GO:0043274',
  'GO:0009897',
  'GO:1903238',
  'GO:0005886',
  'GO:0045121',
  'GO:0005887',
  'GO:0007202',
  'GO:0032496',
  'GO:0019722',
  'GO:0034097',
  'GO:0070555',
  'GO:0030029',
  'GO:0050727',
  'GO:0005905',
  'GO:0070492',
  'GO:0050901',
  'GO:0005901',
  'GO:0007159',
  'GO:0007157',
  'GO:0030863',
  'GO:0046872',
  'GO:0002523',
  'GO:0006954',
  'GO:0048471'],
 'ENSG00000011243': ['GO:0005521',
  'GO:0000785',
  'GO:0003723',
  'GO:1990904',
  'GO:0005737',
  'GO:0005515',
  'GO:0031065',
  'GO:0051081',
  'GO:0044839',
  'GO:0016363',
  'GO:0034237',
  'GO:0016607',
  'GO:0016605',
  'GO:0010793',
  'GO:0033127',
  'GO:0006397',
  'GO:0007076',
  'GO:0045944',
  'GO:0008380',
  'GO:0017151',
  'GO:0005634',
  'GO:0046872',
  'GO:0003677',
  'GO:0042826'],
 'ENSG00000011304': ['GO:0070062',
  'GO:0003723',
  'GO:0003729',
  'GO:0043484',
  'GO:0005515',
  'GO:0048025',
  'GO:0016020',
  'GO:0045595',
  'GO:0035307',
  'GO:0036002',
  'GO:0075522',
  'GO:0006397',
  'GO:0005654',
  'GO:0008187',
  'GO:0000381',
  'GO:0005730',
  'GO:0008380',
  'GO:0033119',
  'GO:0070886',
  'GO:0005634',
  'GO:0051148'],
 'ENSG00000012048': ['GO:0051726',
  'GO:0003713',
  'GO:0008630',
  'GO:0046600',
  'GO:0003723',
  'GO:0085020',
  'GO:0003684',
  'GO:0000976',
  'GO:0032991',
  'GO:0005737',
  'GO:0010575',
  'GO:0045892',
  'GO:0005515',
  'GO:0051571',
  'GO:0051574',
  'GO:0005694',
  'GO:0035066',
  'GO:0051573',
  'GO:0016604',
  'GO:0000931',
  'GO:0043009',
  'GO:0000800',
  'GO:0005886',
  'GO:0004842',
  'GO:1990904',
  'GO:0070063',
  'GO:0071356',
  'GO:1990391',
  'GO:0006301',
  'GO:0008270',
  'GO:0016567',
  'GO:0071479',
  'GO:0000151',
  'GO:0070532',
  'GO:0051865',
  'GO:0010628',
  'GO:2000620',
  'GO:0006633',
  'GO:0045717',
  'GO:1902042',
  'GO:0007095',
  'GO:0045766',
  'GO:0005654',
  'GO:2000378',
  'GO:0000152',
  'GO:0044030',
  'GO:0045944',
  'GO:0009048',
  'GO:0019899',
  'GO:0000724',
  'GO:0033147',
  'GO:0043627',
  'GO:0071681',
  'GO:0006357',
  'GO:0007098',
  'GO:0051572',
  'GO:2000617',
  'GO:0070531',
  'GO:0035067',
  'GO:0045739',
  'GO:0006302',
  'GO:0070512',
  'GO:0007059',
  'GO:0005634',
  'GO:0003677',
  'GO:0006349',
  'GO:0031436',
  'GO:0031625',
  'GO:0070533',
  'GO:0045893',
  'GO:0015631',
  'GO:0031398',
  'GO:0010212',
  'GO:0000209'],
 'ENSG00000015479': ['GO:0016363',
  'GO:0042802',
  'GO:0045087',
  'GO:0016020',
  'GO:0035198',
  'GO:0003723',
  'GO:0005634',
  'GO:0010608',
  'GO:0002218',
  'GO:0005198',
  'GO:0003170',
  'GO:0005515',
  'GO:0008270',
  'GO:0003281',
  'GO:0005637'],
 'ENSG00000019549': ['GO:0014032',
  'GO:0033629',
  'GO:2000811',
  'GO:0000785',
  'GO:0005737',
  'GO:0050872',
  'GO:0005515',
  'GO:0035921',
  'GO:0003682',
  'GO:0035066',
  'GO:2000647',
  'GO:0070888',
  'GO:0032331',
  'GO:1902230',
  'GO:0006933',
  'GO:0090090',
  'GO:0032642',
  'GO:0000981',
  'GO:0000977',
  'GO:0043565',
  'GO:0071479',
  'GO:0010957',
  'GO:0010839',
  'GO:0007219',
  'GO:0045600',
  'GO:0071364',
  'GO:0000978',
  'GO:0005654',
  'GO:0043473',
  'GO:0060429',
  'GO:0045667',
  'GO:0003273',
  'GO:0003198',
  'GO:0060536',
  'GO:0070563',
  'GO:0043518',
  'GO:2001240',
  'GO:0000122',
  'GO:0001227',
  'GO:0006355',
  'GO:0060693',
  'GO:0060021',
  'GO:0001837',
  'GO:0003180',
  'GO:0005634',
  'GO:0046872',
  'GO:0061314',
  'GO:2000810',
  'GO:0001649',
  'GO:0030335',
  'GO:1990837',
  'GO:0007605'],
 'ENSG00000019991': ['GO:2000573',
  'GO:0042802',
  'GO:0005102',
  'GO:0043154',
  'GO:0044877',
  'GO:0060326',
  'GO:0043066',
  'GO:1900744',
  'GO:0060665',
  'GO:0005515',
  'GO:0031093',
  'GO:0005615',
  'GO:0042056',
  'GO:0045669',
  'GO:0016020',
  'GO:0050673',
  'GO:0004175',
  'GO:0043410',
  'GO:0032715',
  'GO:1901299',
  'GO:0014068',
  'GO:0004252',
  'GO:1902947',
  'GO:0006508',
  'GO:0090201',
  'GO:1902042',
  'GO:0005576',
  'GO:0031100',
  'GO:0045766',
  'GO:0001934',
  'GO:0008083',
  'GO:0050731',
  'GO:0070572',
  'GO:0045944',
  'GO:0033137',
  'GO:0010507',
  'GO:0048012',
  'GO:0050728',
  'GO:0001837',
  'GO:0000902',
  'GO:0031643',
  'GO:0050918',
  'GO:0001889',
  'GO:0030335',
  'GO:0032733',
  'GO:0051450',
  'GO:0035729',
  'GO:0000278'],
 'ENSG00000020633': ['GO:0000785',
  'GO:0071559',
  'GO:0005737',
  'GO:0005515',
  'GO:0002062',
  'GO:0001503',
  'GO:0003700',
  'GO:0043231',
  'GO:0000981',
  'GO:0045595',
  'GO:0000977',
  'GO:0030097',
  'GO:0050680',
  'GO:0005524',
  'GO:0043371',
  'GO:0000978',
  'GO:0048935',
  'GO:0005654',
  'GO:0005829',
  'GO:0045786',
  'GO:0006355',
  'GO:0000122',
  'GO:0001222',
  'GO:0030182',
  'GO:0006468',
  'GO:0005730',
  'GO:0043378',
  'GO:0005634',
  'GO:0016513',
  'GO:0045893',
  'GO:1990837',
  'GO:0006357'],
 'ENSG00000021776': ['GO:0016887',
  'GO:0005524',
  'GO:0034458',
  'GO:0000398',
  'GO:0071013',
  'GO:0003727',
  'GO:0005654',
  'GO:0016020',
  'GO:0003723',
  'GO:0005634',
  'GO:0003729',
  'GO:0005515',
  'GO:0071007'],
 'ENSG00000023608': ['GO:0000995',
  'GO:0042796',
  'GO:0042795',
  'GO:0005654',
  'GO:0016251',
  'GO:0043565',
  'GO:0005515',
  'GO:0005730',
  'GO:0019185'],
 'ENSG00000026025': ['GO:0070062',
  'GO:0005856',
  'GO:0042802',
  'GO:0060395',
  'GO:0043005',
  'GO:0005200',
  'GO:1990904',
  'GO:0005737',
  'GO:0014002',
  'GO:0005844',
  'GO:0005515',
  'GO:0060020',
  'GO:0005886',
  'GO:0019904',
  'GO:0005925',
  'GO:0016363',
  'GO:0030424',
  'GO:0071346',
  'GO:0005882',
  'GO:0010977',
  'GO:0005212',
  'GO:0032967',
  'GO:0045727',
  'GO:0005777',
  'GO:0045109',
  'GO:0097110',
  'GO:0071222',
  'GO:0005829',
  'GO:0043488',
  'GO:0045111',
  'GO:0045335',
  'GO:0070307',
  'GO:0071225',
  'GO:1990254',
  'GO:0031252',
  'GO:0005815',
  'GO:0003725'],
 'ENSG00000028137': ['GO:0005031',
  'GO:0008630',
  'GO:0097191',
  'GO:0003176',
  'GO:0035579',
  'GO:1902339',
  'GO:0003332',
  'GO:0005515',
  'GO:0002724',
  'GO:0150077',
  'GO:0005886',
  'GO:0045121',
  'GO:0016020',
  'GO:0043120',
  'GO:0051044',
  'GO:0033209',
  'GO:1901215',
  'GO:0071222',
  'GO:0016021',
  'GO:0006955',
  'GO:0007568',
  'GO:0043025',
  'GO:0005576',
  'GO:0050779',
  'GO:0010614',
  'GO:0150098',
  'GO:0060548',
  'GO:0006954',
  'GO:2001141',
  'GO:0071363',
  'GO:0042129',
  'GO:0150079',
  'GO:0005634',
  'GO:0048714',
  'GO:0031643',
  'GO:0031625',
  'GO:0043196',
  'GO:0048471',
  'GO:0002947',
  'GO:0002718',
  'GO:0003177',
  'GO:0031641'],
 'ENSG00000029363': ['GO:2001022',
  'GO:0005654',
  'GO:0003723',
  'GO:0043620',
  'GO:1990830',
  'GO:2000144',
  'GO:0003677',
  'GO:2001244',
  'GO:0005634',
  'GO:0005737',
  'GO:0045944',
  'GO:0045892',
  'GO:0043065',
  'GO:0005515',
  'GO:0016607',
  'GO:0006915',
  'GO:0016592',
  'GO:0003712'],
 'ENSG00000029993': ['GO:0045578',
  'GO:0003690',
  'GO:0045087',
  'GO:0045638',
  'GO:0003723',
  'GO:0005634',
  'GO:0000400',
  'GO:0032392',
  'GO:0005737',
  'GO:0005694',
  'GO:0005515',
  'GO:0006310',
  'GO:0008301',
  'GO:0006357'],
 'ENSG00000030582': ['GO:0070062',
  'GO:1903334',
  'GO:0003723',
  'GO:1903979',
  'GO:0005515',
  'GO:0005615',
  'GO:0050679',
  'GO:0005886',
  'GO:0016020',
  'GO:1905673',
  'GO:0051087',
  'GO:0007040',
  'GO:0050821',
  'GO:1905247',
  'GO:0005765',
  'GO:0007165',
  'GO:0010595',
  'GO:0005770',
  'GO:0005125',
  'GO:0005576',
  'GO:0002265',
  'GO:0045766',
  'GO:0005764',
  'GO:0008083',
  'GO:0007041',
  'GO:0005794',
  'GO:0050727',
  'GO:0002282',
  'GO:0005802',
  'GO:0048680',
  'GO:1902564',
  'GO:0005783',
  'GO:0043525',
  'GO:0035578',
  'GO:0106016',
  'GO:0060266',
  'GO:1900426',
  'GO:0005768',
  'GO:0043524',
  'GO:0030335',
  'GO:0007042'],
 'ENSG00000037474': ['GO:0005739',
  'GO:0070062',
  'GO:0048820',
  'GO:0003723',
  'GO:0006400',
  'GO:0036416',
  'GO:0005737',
  'GO:2000736',
  'GO:0080009',
  'GO:0001510',
  'GO:0000049',
  'GO:0033313',
  'GO:0010793',
  'GO:0062152',
  'GO:0005654',
  'GO:0008168',
  'GO:0005730',
  'GO:0016428',
  'GO:0005819',
  'GO:0030488',
  'GO:0033391',
  'GO:0005634',
  'GO:0001701',
  'GO:0007286',
  'GO:0051301'],
 'ENSG00000039123': ['GO:0016887',
  'GO:0006364',
  'GO:0005524',
  'GO:0006974',
  'GO:0000398',
  'GO:0071013',
  'GO:0005654',
  'GO:0003723',
  'GO:0005634',
  'GO:0000460',
  'GO:0016076',
  'GO:0005515',
  'GO:0016607',
  'GO:0003724',
  'GO:0031499',
  'GO:0006401',
  'GO:0005730'],
 'ENSG00000039650': ['GO:0005739',
  'GO:0003690',
  'GO:0051103',
  'GO:2001034',
  'GO:0003684',
  'GO:0006287',
  'GO:0004519',
  'GO:0006303',
  'GO:0005515',
  'GO:0009314',
  'GO:0006979',
  'GO:1904355',
  'GO:0016020',
  'GO:0098506',
  'GO:0051973',
  'GO:0005524',
  'GO:0000718',
  'GO:0005654',
  'GO:0006281',
  'GO:0005730',
  'GO:0046403',
  'GO:0090305',
  'GO:0046404',
  'GO:0005634',
  'GO:0010836',
  'GO:0035861',
  'GO:0017076',
  'GO:0006261',
  'GO:0046939',
  'GO:0032212'],
 'ENSG00000044574': ['GO:0005739',
  'GO:0030433',
  'GO:0010976',
  'GO:0030512',
  'GO:0001554',
  'GO:0035437',
  'GO:0042470',
  'GO:0070062',
  'GO:0021589',
  'GO:1903897',
  'GO:0043066',
  'GO:0034663',
  'GO:0005790',
  'GO:0071277',
  'GO:0005737',
  'GO:0032991',
  'GO:0005515',
  'GO:0021680',
  'GO:0031333',
  'GO:1901998',
  'GO:0030496',
  'GO:0016887',
  'GO:0005886',
  'GO:0019904',
  'GO:1903894',
  'GO:0051082',
  'GO:0005925',
  'GO:0030176',
  'GO:0016020',
  'GO:0051087',
  'GO:0043231',
  'GO:1990440',
  'GO:0045296',
  'GO:0051787',
  'GO:0051402',
  'GO:0005789',
  'GO:0071466',
  'GO:0071480',
  'GO:0030968',
  'GO:0005524',
  'GO:0005509',
  'GO:0005793',
  'GO:0005788',
  'GO:0031204',
  'GO:0005829',
  'GO:0071287',
  'GO:0009986',
  'GO:0019899',
  'GO:0034620',
  'GO:0006983',
  'GO:0071353',
  'GO:0030182',
  'GO:1903891',
  'GO:0034975',
  'GO:0005783',
  'GO:0021762',
  'GO:0042220',
  'GO:0071236',
  'GO:1903895',
  'GO:0031072',
  'GO:1990090',
  'GO:1904313',
  'GO:0042026',
  'GO:0097501',
  'GO:0005634',
  'GO:0071320',
  'GO:0031625',
  'GO:0030335',
  'GO:0044183',
  'GO:0060904',
  'GO:0042149',
  'GO:0043022',
  'GO:0031398',
  'GO:0051085'],
 'ENSG00000047346': ['GO:0005515'],
 'ENSG00000047410': ['GO:0034605',
  'GO:0005643',
  'GO:0031453',
  'GO:0010965',
  'GO:0003723',
  'GO:0031990',
  'GO:0003729',
  'GO:0032880',
  'GO:0005737',
  'GO:0006404',
  'GO:0005515',
  'GO:0090316',
  'GO:0042405',
  'GO:0003682',
  'GO:0005868',
  'GO:0043495',
  'GO:0035457',
  'GO:0051292',
  'GO:0044615',
  'GO:0051019',
  'GO:0031965',
  'GO:0006405',
  'GO:0046825',
  'GO:0072686',
  'GO:0042306',
  'GO:1901673',
  'GO:0007094',
  'GO:0010793',
  'GO:0046832',
  'GO:0070840',
  'GO:0006406',
  'GO:0070849',
  'GO:0005635',
  'GO:0005654',
  'GO:0006999',
  'GO:0043578',
  'GO:0046827',
  'GO:0090267',
  'GO:0006611',
  'GO:0006606',
  'GO:0000122',
  'GO:0031647',
  'GO:0034399',
  'GO:0017056',
  'GO:0031072',
  'GO:0019898',
  'GO:0045947',
  'GO:0042307',
  'GO:0042803',
  'GO:0005634',
  'GO:0000776',
  'GO:0015631',
  'GO:0051301'],
 'ENSG00000048052': ['GO:0007507',
  'GO:0016575',
  'GO:0005737',
  'GO:0045892',
  'GO:0005515',
  'GO:0032041',
  'GO:0006325',
  'GO:0000118',
  'GO:0048742',
  'GO:0042113',
  'GO:0035097',
  'GO:0051005',
  'GO:1990678',
  'GO:0051153',
  'GO:0003714',
  'GO:0005654',
  'GO:0032869',
  'GO:0042632',
  'GO:0005667',
  'GO:0030183',
  'GO:0000122',
  'GO:0070932',
  'GO:0070933',
  'GO:0034739',
  'GO:0008134',
  'GO:0090050',
  'GO:0034983',
  'GO:0033558',
  'GO:0001818',
  'GO:0005080',
  'GO:0005634',
  'GO:0046872',
  'GO:0042826',
  'GO:0061629',
  'GO:0004407',
  'GO:0140297',
  'GO:0006954'],
 'ENSG00000048828': ['GO:0005886',
  'GO:0016020',
  'GO:0005829',
  'GO:0003723',
  'GO:0005634'],
 'ENSG00000051180': ['GO:0005739',
  'GO:0000793',
  'GO:0003690',
  'GO:0010165',
  'GO:0000785',
  'GO:0042802',
  'GO:0051321',
  'GO:0000781',
  'GO:0032991',
  'GO:0005737',
  'GO:0000722',
  'GO:0005515',
  'GO:0005759',
  'GO:0003682',
  'GO:0006312',
  'GO:0010569',
  'GO:0000800',
  'GO:0006268',
  'GO:1990426',
  'GO:0036297',
  'GO:0007131',
  'GO:1990414',
  'GO:0072719',
  'GO:0070192',
  'GO:0000730',
  'GO:0072711',
  'GO:0008094',
  'GO:0006310',
  'GO:0009636',
  'GO:0017116',
  'GO:0071479',
  'GO:0072757',
  'GO:0003697',
  'GO:0071480',
  'GO:0016605',
  'GO:0005524',
  'GO:0001932',
  'GO:0031297',
  'GO:0005654',
  'GO:0006281',
  'GO:0000152',
  'GO:0009410',
  'GO:0000150',
  'GO:0019899',
  'GO:0000724',
  'GO:1904631',
  'GO:0006974',
  'GO:0070182',
  'GO:0000794',
  'GO:0005634',
  'GO:0000228',
  'GO:0035861',
  'GO:0042148',
  'GO:0005815',
  'GO:0010833',
  'GO:0051106',
  'GO:0008022',
  'GO:0048471'],
 'ENSG00000053372': ['GO:0006364',
  'GO:0000027',
  'GO:0003723',
  'GO:0005737',
  'GO:0000956',
  'GO:0030687',
  'GO:0005515',
  'GO:0042273',
  'GO:0005730'],
 'ENSG00000054118': ['GO:0070062',
  'GO:0003713',
  'GO:0042753',
  'GO:0048026',
  'GO:0003723',
  'GO:0007623',
  'GO:0005515',
  'GO:0016592',
  'GO:0016607',
  'GO:0042809',
  'GO:0000978',
  'GO:0005524',
  'GO:0006397',
  'GO:0005654',
  'GO:0046966',
  'GO:0045944',
  'GO:0000956',
  'GO:0051219',
  'GO:0000381',
  'GO:0003712',
  'GO:0030374',
  'GO:0008380',
  'GO:0005634',
  'GO:0003677',
  'GO:0045893',
  'GO:0048255'],
 'ENSG00000055917': ['GO:0035198',
  'GO:0003723',
  'GO:0003729',
  'GO:0005737',
  'GO:0034063',
  'GO:0005515',
  'GO:0010494',
  'GO:0060964',
  'GO:0003730',
  'GO:0010608',
  'GO:0031965',
  'GO:0051983',
  'GO:0005829',
  'GO:0006417',
  'GO:0043488',
  'GO:1900246',
  'GO:0035196',
  'GO:2000637',
  'GO:0048471'],
 'ENSG00000056972': ['GO:0061630',
  'GO:0005102',
  'GO:0007507',
  'GO:0110012',
  'GO:0001783',
  'GO:0005515',
  'GO:0042092',
  'GO:0002269',
  'GO:0001782',
  'GO:0002447',
  'GO:0048536',
  'GO:0002334',
  'GO:0070254',
  'GO:0042119',
  'GO:0006959',
  'GO:0001768',
  'GO:0070534',
  'GO:0033209',
  'GO:0038173',
  'GO:1990959',
  'GO:0023035',
  'GO:0009410',
  'GO:0005575',
  'GO:0048535',
  'GO:0031410',
  'GO:0006606',
  'GO:0097400',
  'GO:0002230',
  'GO:0001822',
  'GO:0035556',

In [95]:
go_terms_npinterv4_tarid_go_terms_df_v2 = pd.DataFrame({"ensg_npintertar": list(go_terms_npinterv4_tarid_go_terms_v2.keys()), "go_terms": list(go_terms_npinterv4_tarid_go_terms_v2.values())})
go_terms_npinterv4_tarid_go_terms_df_v2

      ensg_npintertar                                           go_terms
0     ENSG00000001631  [GO:0005856, GO:0005737, GO:0008017, GO:000551...
1     ENSG00000003756  [GO:0006396, GO:0000398, GO:0005654, GO:000372...
2     ENSG00000004478  [GO:0005739, GO:0070062, GO:0061077, GO:004815...
3     ENSG00000004487  [GO:0090308, GO:0120162, GO:0010976, GO:004342...
4     ENSG00000004534  [GO:0006396, GO:0000398, GO:0003723, GO:000563...
...               ...                                                ...
1370  ENSG00000288210  [GO:0006336, GO:0030154, GO:0000785, GO:000565...
1371  ENSG00000288237                                                NaN
1372  ENSG00000288367                                                NaN
1373  ENSG00000288397                                                NaN
1374  ENSG00000288462                                                NaN

[1375 rows x 2 columns]

In [97]:
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2.join(go_terms_npinterv4_tarid_go_terms_df_v2.set_index("ensg_npintertar"), on="tarID_ensembl_code")
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[~npinterv4_tarid_go_terms_v2["go_terms"].isnull()]
npinterv4_tarid_go_terms_v2

,index,interID,ncName,ncID,ncType,tarName,tarID,tarType,interDescription,experiment,...,tissueOrCell,tag,class,level,datasource,ncID_rnacentral_code,ncID_ensembl_code,tarID_rnacentral_code,tarID_ensembl_code,go_terms
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,"[GO:0106140, GO:0004860, GO:0042802, GO:000750..."
1,7,ncRI-40000008,7SK,NONHSAG040596,lncRNA,Tat,P17735,protein,Tat efficiently replaces HEXIM1 on the 7SK snR...,-,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000198650,"[GO:0005739, GO:0016597, GO:0006559, GO:000483..."
2,8,ncRI-40000009,7SK,NONHSAG040596,lncRNA,CDK9,P50750,protein,Northern hybridization was performed to confir...,Northern Blot,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000136807,"[GO:0004712, GO:0051726, GO:0004672, GO:190365..."
3,9,ncRI-40000010,7SK,NONHSAG040596,lncRNA,PPP1CA,P62136,protein,PP2B and PP1alpha cooperatively disrupt 7SK sn...,-,...,-,regulatory,regulatory,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000172531,"[GO:0070062, GO:0032922, GO:0004721, GO:009864..."
4,10,ncRI-40000011,7SK,NONHSAG040596,lncRNA,PP2B,P62140,protein,PP2B and PP1alpha cooperatively disrupt 7SK sn...,-,...,-,regulatory,regulatory,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000213639,"[GO:0070062, GO:0032922, GO:0000165, GO:000078..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479697,970575,ncRI-40970577,GAS5,NONHSAG003504,lncRNA,TRAIL,P50591,protein,Pi-sno75 significantly induces epigenetic alte...,RIP,...,MCF7,expression correlation,expression correlation,RNA-Protein,Literature Mining,URS00008C4009,ENSG00000234741,NaN,ENSG00000121858,"[GO:0070062, GO:0005102, GO:0042802, GO:000551..."
479698,970575,ncRI-40970577,GAS5,NONHSAG003504,lncRNA,TRAIL,P50591,protein,Pi-sno75 significantly induces epigenetic alte...,RIP,...,MCF7,expression correlation,expression correlation,RNA-Protein,Literature Mining,URS00009B629F,ENSG00000234741,NaN,ENSG00000121858,"[GO:0070062, GO:0005102, GO:0042802, GO:000551..."
479699,970575,ncRI-40970577,GAS5,NONHSAG003504,lncRNA,TRAIL,P50591,protein,Pi-sno75 significantly induces epigenetic alte...,RIP,...,MCF7,expression correlation,expression correlation,RNA-Protein,Literature Mining,URS00009BCE1D,ENSG00000234741,NaN,ENSG00000121858,"[GO:0070062, GO:0005102, GO:0042802, GO:000551..."
479700,970575,ncRI-40970577,GAS5,NONHSAG003504,lncRNA,TRAIL,P50591,protein,Pi-sno75 significantly induces epigenetic alte...,RIP,...,MCF7,expression correlation,expression correlation,RNA-Protein,Literature Mining,URS00009C227F,ENSG00000234741,NaN,ENSG00000121858,"[GO:0070062, GO:0005102, GO:0042802, GO:000551..."
479701,970578,ncRI-40970580,SNORD50B,ENSG00000275072,snoRNA,KRAS,P01116,protein,SNORD50A and SNORD50B snoRNAs thus directly bi...,"RIP,Luciferase reporter assay",...,-,ncRNA-protein binding,binding,RNA-Protein,Literature Mining,URS00006F8A66,ENSG00000275072,NaN,ENSG00000133703,"[GO:0042802, GO:0000165, GO:0045596, GO:000574..."

In [99]:
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2.explode('go_terms')
npinterv4_tarid_go_terms_v2

,index,interID,ncName,ncID,ncType,tarName,tarID,tarType,interDescription,experiment,...,tissueOrCell,tag,class,level,datasource,ncID_rnacentral_code,ncID_ensembl_code,tarID_rnacentral_code,tarID_ensembl_code,go_terms
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0106140
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0004860
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0042802
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0007507
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0017069
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479701,970578,ncRI-40970580,SNORD50B,ENSG00000275072,snoRNA,KRAS,P01116,protein,SNORD50A and SNORD50B snoRNAs thus directly bi...,"RIP,Luciferase reporter assay",...,-,ncRNA-protein binding,binding,RNA-Protein,Literature Mining,URS00006F8A66,ENSG00000275072,NaN,ENSG00000133703,GO:0043524
479701,970578,ncRI-40970580,SNORD50B,ENSG00000275072,snoRNA,KRAS,P01116,protein,SNORD50A and SNORD50B snoRNAs thus directly bi...,"RIP,Luciferase reporter assay",...,-,ncRNA-protein binding,binding,RNA-Protein,Literature Mining,URS00006F8A66,ENSG00000275072,NaN,ENSG00000133703,GO:0019003
479701,970578,ncRI-40970580,SNORD50B,ENSG00000275072,snoRNA,KRAS,P01116,protein,SNORD50A and SNORD50B snoRNAs thus directly bi...,"RIP,Luciferase reporter assay",...,-,ncRNA-protein binding,binding,RNA-Protein,Literature Mining,URS00006F8A66,ENSG00000275072,NaN,ENSG00000133703,GO:0060441
479701,970578,ncRI-40970580,SNORD50B,ENSG00000275072,snoRNA,KRAS,P01116,protein,SNORD50A and SNORD50B snoRNAs thus directly bi...,"RIP,Luciferase reporter assay",...,-,ncRNA-protein binding,binding,RNA-Protein,Literature Mining,URS00006F8A66,ENSG00000275072,NaN,ENSG00000133703,GO:0007265
479701,970578,ncRI-40970580,SNORD50B,ENSG00000275072,snoRNA,KRAS,P01116,protein,SNORD50A and SNORD50B snoRNAs thus directly bi...,"RIP,Luciferase reporter assay",...,-,ncRNA-protein binding,binding,RNA-Protein,Literature Mining,URS00006F8A66,ENSG00000275072,NaN,ENSG00000133703,GO:0044877

In [101]:
len(np.unique(npinterv4_tarid_go_terms_v2["go_terms"]))

5497

In [102]:
for go_term in np.unique(npinterv4_tarid_go_terms_v2["go_terms"]):
    try:
        obodag[go_term]
    except KeyError:
        print(go_term)

GO:0003925
GO:0062152
GO:0062153
GO:0062176
GO:0106226
GO:0106230
GO:0106231
GO:0106256
GO:0106310
GO:0106312
GO:0106313
GO:0106363
GO:0120223
GO:0120259
GO:0120283
GO:0120293
GO:0120301
GO:0140416
GO:0140431
GO:0140447
GO:0140448
GO:0140492
GO:0140517
GO:0140545
GO:0140585
GO:0140658
GO:0140668
GO:0140672
GO:0140681
GO:0140682
GO:0140684

In [81]:
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[npinterv4_tarid_go_terms_v2["go_terms"] != 'GO:0120259']
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[npinterv4_tarid_go_terms_v2["go_terms"] != 'GO:0120259']
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[npinterv4_tarid_go_terms_v2["go_terms"] != 'GO:0120259']
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[npinterv4_tarid_go_terms_v2["go_terms"] != 'GO:0120259']
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[npinterv4_tarid_go_terms_v2["go_terms"] != 'GO:0120259']
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[npinterv4_tarid_go_terms_v2["go_terms"] != 'GO:0120259']
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[npinterv4_tarid_go_terms_v2["go_terms"] != 'GO:0120259']
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[npinterv4_tarid_go_terms_v2["go_terms"] != 'GO:0140545']
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[npinterv4_tarid_go_terms_v2["go_terms"] != 'GO:0140585']
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[npinterv4_tarid_go_terms_v2["go_terms"] != 'GO:0140658']
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[npinterv4_tarid_go_terms_v2["go_terms"] != 'GO:0140668']
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[npinterv4_tarid_go_terms_v2["go_terms"] != 'GO:0140672']
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[npinterv4_tarid_go_terms_v2["go_terms"] != 'GO:0140681']
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[npinterv4_tarid_go_terms_v2["go_terms"] != 'GO:0140682']
npinterv4_tarid_go_terms_v2 = npinterv4_tarid_go_terms_v2[npinterv4_tarid_go_terms_v2["go_terms"] != 'GO:0140684']
npinterv4_tarid_go_terms_v2

,index,interID,ncName,ncID,ncType,tarName,tarID,tarType,interDescription,experiment,...,tissueOrCell,tag,class,level,datasource,ncID_rnacentral_code,ncID_ensembl_code,tarID_rnacentral_code,tarID_ensembl_code,go_terms
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0106140
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:1901798
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0004860
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0042802
0,5,ncRI-40000006,7SK,NONHSAG040596,lncRNA,HEXIM1,O94992,protein,Binding of the 7SK snRNA turns the HEXIM1 prot...,Yeast two-hybrid analysis;Immunofluorescence;M...,...,-,ncRNA-protein binding,binding,RNA-Protein,Literature mining,URS00004E902D,ENSG00000249352,NaN,ENSG00000186834,GO:0007507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,GO:0035522
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,GO:0035455
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,GO:0006995
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,GO:0005852
487274,1100455,ncRI-41100457,SNORD43,ENSG00000263764,snoRNA,SNHG1,ENSG00000255717,ncRNA,RNA-RNA interaction from RISE database,LIGRseq,...,HEK293T,RNA-RNA interaction,binding,RNA-RNA,RISE database,URS000063F175,ENSG00000263764,URS0000EF6DD5,ENSG00000255717,GO:0070315

##### Save file

In [142]:
npinterv4_tarid_go_terms_df_v2 = pd.DataFrame({
    0: ["NPInter"] * len(npinterv4_tarid_go_terms_v2),
    1: npinterv4_tarid_go_terms_v2["tarID_ensembl_code"],
    2: list(npinterv4_tarid_go_terms_v2.join(ensembl_gene_gene_name.set_index("Gene stable ID"), on="tarID_ensembl_code")["Gene name"].astype("str")),
    3: ["enables"]  * len(npinterv4_tarid_go_terms_v2),
    4: npinterv4_tarid_go_terms_v2["go_terms"],
    5: ["GO_REF:0000001"] * len(npinterv4_tarid_go_terms_v2),
    6: ["EXP"] * len(npinterv4_tarid_go_terms_v2),
    7: ["NPInter"] * len(npinterv4_tarid_go_terms_v2),
    8: [np.nan if go_term not in list(obodag.keys()) else "P" if obodag[go_term].namespace == "biological_process" else "F" if obodag[go_term].namespace == "molecular_function" else "C" for go_term in npinterv4_tarid_go_terms_v2["go_terms"]], 
    9: [np.nan if go_term not in list(obodag.keys()) else obodag[go_term].name for go_term in npinterv4_tarid_go_terms_v2["go_terms"]],
    10: list(npinterv4_tarid_go_terms_v2.join(ensembl_gene_gene_name.set_index("Gene stable ID"), on="tarID_ensembl_code")["Gene name"].astype("str")),
    11: ["ncRNA"] * len(npinterv4_tarid_go_terms_v2),
    12: ["taxon:9606"] * len(npinterv4_tarid_go_terms_v2),
    13: [20220215] * len(npinterv4_tarid_go_terms_v2),
    14: ["NPInter"] * len(npinterv4_tarid_go_terms_v2),
    15: [np.nan] * len(npinterv4_tarid_go_terms_v2),
    16: [np.nan] * len(npinterv4_tarid_go_terms_v2)
})

npinterv4_tarid_go_terms_df_v2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0106140,GO_REF:0000001,EXP,NPInter,F,P-TEFb complex binding,HEXIM1,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0004860,GO_REF:0000001,EXP,NPInter,F,protein kinase inhibitor activity,HEXIM1,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0042802,GO_REF:0000001,EXP,NPInter,F,identical protein binding,HEXIM1,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0007507,GO_REF:0000001,EXP,NPInter,P,heart development,HEXIM1,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0017069,GO_REF:0000001,EXP,NPInter,F,snRNA binding,HEXIM1,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0043524,GO_REF:0000001,EXP,NPInter,P,negative regulation of neuron apoptotic process,KRAS,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0019003,GO_REF:0000001,EXP,NPInter,F,GDP binding,KRAS,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0060441,GO_REF:0000001,EXP,NPInter,P,epithelial tube branching involved in lung mor...,KRAS,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0007265,GO_REF:0000001,EXP,NPInter,P,Ras protein signal transduction,KRAS,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0044877,GO_REF:0000001,EXP,NPInter,F,protein-containing complex binding,KRAS,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN

In [106]:
npinterv4_tarid_go_terms_df_v2 = pd.DataFrame({
    0: ["NPInter"] * len(npinterv4_tarid_go_terms_v2),
    1: npinterv4_tarid_go_terms_v2["tarID_ensembl_code"],
    2: list(npinterv4_tarid_go_terms_v2.join(ensembl_gene_gene_name.set_index("Gene stable ID"), on="tarID_ensembl_code")["Gene name"].astype("str")),
    3: ["enables"]  * len(npinterv4_tarid_go_terms_v2),
    4: npinterv4_tarid_go_terms_v2["go_terms"],
    5: ["GO_REF:0000001"] * len(npinterv4_tarid_go_terms_v2),
    6: ["EXP"] * len(npinterv4_tarid_go_terms_v2),
    7: ["NPInter"] * len(npinterv4_tarid_go_terms_v2),
    8: [np.nan if go_term not in list(obodag.keys()) else "P" if obodag[go_term].namespace == "biological_process" else "F" if obodag[go_term].namespace == "molecular_function" else "C" for go_term in npinterv4_tarid_go_terms_v2["go_terms"]], 
    9: [np.nan if go_term not in list(obodag.keys()) else obodag[go_term].name for go_term in npinterv4_tarid_go_terms_v2["go_terms"]],
    10: list(npinterv4_tarid_go_terms_v2.join(ensembl_gene_gene_name.set_index("Gene stable ID"), on="tarID_ensembl_code")["Gene name"].astype("str")),
    11: ["ncRNA"] * len(npinterv4_tarid_go_terms_v2),
    12: ["taxon:9606"] * len(npinterv4_tarid_go_terms_v2),
    13: [20220215] * len(npinterv4_tarid_go_terms_v2),
    14: ["NPInter"] * len(npinterv4_tarid_go_terms_v2),
    15: [np.nan] * len(npinterv4_tarid_go_terms_v2),
    16: [np.nan] * len(npinterv4_tarid_go_terms_v2)
})

npinterv4_tarid_go_terms_df_v2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0106140,NPInter,EXP,NPInter,F,P-TEFb complex binding,HEXIM1,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0004860,NPInter,EXP,NPInter,F,protein kinase inhibitor activity,HEXIM1,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0042802,NPInter,EXP,NPInter,F,identical protein binding,HEXIM1,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0007507,NPInter,EXP,NPInter,P,heart development,HEXIM1,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0017069,NPInter,EXP,NPInter,F,snRNA binding,HEXIM1,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0043524,NPInter,EXP,NPInter,P,negative regulation of neuron apoptotic process,KRAS,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0019003,NPInter,EXP,NPInter,F,GDP binding,KRAS,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0060441,NPInter,EXP,NPInter,P,epithelial tube branching involved in lung mor...,KRAS,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0007265,NPInter,EXP,NPInter,P,Ras protein signal transduction,KRAS,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0044877,NPInter,EXP,NPInter,F,protein-containing complex binding,KRAS,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN

In [143]:
npinterv4_tarid_go_terms_df_v2 = npinterv4_tarid_go_terms_df_v2[~npinterv4_tarid_go_terms_df_v2[8].isnull()]
npinterv4_tarid_go_terms_df_v2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0106140,GO_REF:0000001,EXP,NPInter,F,P-TEFb complex binding,HEXIM1,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0004860,GO_REF:0000001,EXP,NPInter,F,protein kinase inhibitor activity,HEXIM1,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0042802,GO_REF:0000001,EXP,NPInter,F,identical protein binding,HEXIM1,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0007507,GO_REF:0000001,EXP,NPInter,P,heart development,HEXIM1,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0017069,GO_REF:0000001,EXP,NPInter,F,snRNA binding,HEXIM1,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0043524,GO_REF:0000001,EXP,NPInter,P,negative regulation of neuron apoptotic process,KRAS,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0019003,GO_REF:0000001,EXP,NPInter,F,GDP binding,KRAS,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0060441,GO_REF:0000001,EXP,NPInter,P,epithelial tube branching involved in lung mor...,KRAS,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0007265,GO_REF:0000001,EXP,NPInter,P,Ras protein signal transduction,KRAS,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0044877,GO_REF:0000001,EXP,NPInter,F,protein-containing complex binding,KRAS,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN

In [107]:
npinterv4_tarid_go_terms_df_v2 = npinterv4_tarid_go_terms_df_v2[~npinterv4_tarid_go_terms_df_v2[8].isnull()]
npinterv4_tarid_go_terms_df_v2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0106140,NPInter,EXP,NPInter,F,P-TEFb complex binding,HEXIM1,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0004860,NPInter,EXP,NPInter,F,protein kinase inhibitor activity,HEXIM1,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0042802,NPInter,EXP,NPInter,F,identical protein binding,HEXIM1,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0007507,NPInter,EXP,NPInter,P,heart development,HEXIM1,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0017069,NPInter,EXP,NPInter,F,snRNA binding,HEXIM1,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0043524,NPInter,EXP,NPInter,P,negative regulation of neuron apoptotic process,KRAS,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0019003,NPInter,EXP,NPInter,F,GDP binding,KRAS,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0060441,NPInter,EXP,NPInter,P,epithelial tube branching involved in lung mor...,KRAS,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0007265,NPInter,EXP,NPInter,P,Ras protein signal transduction,KRAS,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0044877,NPInter,EXP,NPInter,F,protein-containing complex binding,KRAS,ncRNA,taxon:9606,NPInter,NPInter,NaN,NaN

In [144]:
from itertools import islice
with open('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human.gaf', "r") as myfile:
    head = list(islice(myfile, 41))
head

['!gaf-version: 2.2\n',
 '!\n',
 '!generated-by: GOC\n',
 '!\n',
 '!date-generated: 2022-01-14T16:45\n',
 '!\n',
 '!Header from source association file:\n',
 '!=================================\n',
 '!\n',
 '!generated-by: GOC\n',
 '!\n',
 '!date-generated: 2022-01-14T04:41\n',
 '!\n',
 '!Header from goa_human source association file:\n',
 '!=================================\n',
 '!\n',
 '!The set of protein accessions included in this file is based on UniProt reference proteomes, which provide one protein per gene.\n',
 '!They include the protein sequences annotated in Swiss-Prot or the longest TrEMBL transcript if there is no Swiss-Prot record.\n',
 '!If a particular protein accession is not annotated with GO, then it will not appear in this file.\n',
 '!\n',
 '!Note that the annotation set in this file is filtered in order to reduce redundancy; the full, unfiltered set can be found in\n',
 '!ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gz\n',
 '!\n',
 '!date-generated: 2021-11-08 15:48\n',
 '!generated-by: UniProt\n',
 '!go-version: http://purl.obolibrary.org/obo/go/releases/2021-11-06/extensions/go-plus.owl\n',
 '!\n',
 '!=================================\n',
 '!\n',
 '!Header copied from paint_goa_human_valid.gaf\n',
 '!=================================\n',
 '!Created on Sun Jan  2 19:01:56 2022.\n',
 '!generated-by: PANTHER\n',
 '!date-generated: 2022-01-02\n',
 '!PANTHER version: v.15.0.\n',
 '!GO version: 2021-11-16.\n',
 '!\n',
 '!=================================\n',
 '!\n',
 '!Documentation about this header can be found here: https://github.com/geneontology/go-site/blob/master/docs/gaf_validation.md\n',
 '!\n']

In [145]:
# always remember, use files in a with statement
with open('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_npinter_tar_v2_ensembl_gene_mapping.gaf', "w") as f2:
    for item in head:
        f2.write(item)

In [146]:
npinterv4_tarid_go_terms_df_v2.to_csv('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_npinter_tar_v2_ensembl_gene_mapping.gaf', mode="a", sep="\t", header=False, index=False)

## Create Transcript NPInter versions

In [149]:
from pybiomart import Server

server = Server(host='http://www.ensembl.org')

dataset = (server.marts['ENSEMBL_MART_ENSEMBL']
                 .datasets['hsapiens_gene_ensembl'])

In [151]:
ensembl_gene_ensembl_transcript = dataset.query(attributes=['ensembl_gene_id', 'ensembl_transcript_id'])
ensembl_gene_ensembl_transcript

         Gene stable ID Transcript stable ID
0       ENSG00000210049      ENST00000387314
1       ENSG00000211459      ENST00000389680
2       ENSG00000210077      ENST00000387342
3       ENSG00000210082      ENST00000387347
4       ENSG00000209082      ENST00000386347
...                 ...                  ...
266610  ENSG00000086619      ENST00000689343
266611  ENSG00000086619      ENST00000691519
266612  ENSG00000086619      ENST00000686625
266613  ENSG00000086619      ENST00000366589
266614  ENSG00000086619      ENST00000687604

[266615 rows x 2 columns]

In [157]:
npinterv4_ncid_go_terms_transcript_df = npinterv4_ncid_go_terms_df.copy()
npinterv4_ncid_go_terms_transcript_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
3,NPInter,ENSG00000249352,LINC02198,enables,GO:0010468,GO_REF:0000001,EXP,NPInter,P,regulation of gene expression,LINC02198,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
3,NPInter,ENSG00000249352,LINC02198,enables,GO:0040033,GO_REF:0000001,EXP,NPInter,P,"negative regulation of translation, ncRNA-medi...",LINC02198,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
3,NPInter,ENSG00000249352,LINC02198,enables,GO:0003723,GO_REF:0000001,EXP,NPInter,F,RNA binding,LINC02198,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
3,NPInter,ENSG00000249352,LINC02198,enables,GO:0034660,GO_REF:0000001,EXP,NPInter,P,ncRNA metabolic process,LINC02198,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
3,NPInter,ENSG00000249352,LINC02198,enables,GO:0005515,GO_REF:0000001,EXP,NPInter,F,protein binding,LINC02198,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1100456,NPInter,ENSG00000208892,SNORA49,enables,GO:0034660,GO_REF:0000001,EXP,NPInter,P,ncRNA metabolic process,SNORA49,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
1100460,NPInter,ENSG00000200753,nan,enables,GO:0003723,GO_REF:0000001,EXP,NPInter,F,RNA binding,nan,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
1100460,NPInter,ENSG00000200753,nan,enables,GO:0034660,GO_REF:0000001,EXP,NPInter,P,ncRNA metabolic process,nan,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
1100515,NPInter,ENSG00000283146,MIR548AU,enables,GO:0003723,GO_REF:0000001,EXP,NPInter,F,RNA binding,MIR548AU,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
1100515,NPInter,ENSG00000283146,MIR548AU,enables,GO:0034660,GO_REF:0000001,EXP,NPInter,P,ncRNA metabolic process,MIR548AU,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN

In [156]:
npinterv4_tarid_go_terms_transcript_df_v2 = npinterv4_tarid_go_terms_df_v2.copy()
npinterv4_tarid_go_terms_transcript_df_v2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0106140,GO_REF:0000001,EXP,NPInter,F,P-TEFb complex binding,HEXIM1,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0004860,GO_REF:0000001,EXP,NPInter,F,protein kinase inhibitor activity,HEXIM1,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0042802,GO_REF:0000001,EXP,NPInter,F,identical protein binding,HEXIM1,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0007507,GO_REF:0000001,EXP,NPInter,P,heart development,HEXIM1,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
0,NPInter,ENSG00000186834,HEXIM1,enables,GO:0017069,GO_REF:0000001,EXP,NPInter,F,snRNA binding,HEXIM1,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0043524,GO_REF:0000001,EXP,NPInter,P,negative regulation of neuron apoptotic process,KRAS,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0019003,GO_REF:0000001,EXP,NPInter,F,GDP binding,KRAS,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0060441,GO_REF:0000001,EXP,NPInter,P,epithelial tube branching involved in lung mor...,KRAS,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0007265,GO_REF:0000001,EXP,NPInter,P,Ras protein signal transduction,KRAS,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
479701,NPInter,ENSG00000133703,KRAS,enables,GO:0044877,GO_REF:0000001,EXP,NPInter,F,protein-containing complex binding,KRAS,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN

In [ ]:
######

In [158]:
npinterv4_ncid_go_terms_transcript_df = npinterv4_ncid_go_terms_transcript_df.join(ensembl_gene_ensembl_transcript.set_index("Gene stable ID"), on=[1])
npinterv4_ncid_go_terms_transcript_df = npinterv4_ncid_go_terms_transcript_df[~npinterv4_ncid_go_terms_transcript_df["Transcript stable ID"].isnull()]
npinterv4_ncid_go_terms_transcript_df[1] = npinterv4_ncid_go_terms_transcript_df["Transcript stable ID"]
del npinterv4_ncid_go_terms_transcript_df["Transcript stable ID"]
npinterv4_ncid_go_terms_transcript_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
3,NPInter,ENST00000505371,LINC02198,enables,GO:0010468,GO_REF:0000001,EXP,NPInter,P,regulation of gene expression,LINC02198,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
3,NPInter,ENST00000504280,LINC02198,enables,GO:0010468,GO_REF:0000001,EXP,NPInter,P,regulation of gene expression,LINC02198,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
3,NPInter,ENST00000505371,LINC02198,enables,GO:0040033,GO_REF:0000001,EXP,NPInter,P,"negative regulation of translation, ncRNA-medi...",LINC02198,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
3,NPInter,ENST00000504280,LINC02198,enables,GO:0040033,GO_REF:0000001,EXP,NPInter,P,"negative regulation of translation, ncRNA-medi...",LINC02198,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
3,NPInter,ENST00000505371,LINC02198,enables,GO:0003723,GO_REF:0000001,EXP,NPInter,F,RNA binding,LINC02198,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1100456,NPInter,ENST00000386157,SNORA49,enables,GO:0034660,GO_REF:0000001,EXP,NPInter,P,ncRNA metabolic process,SNORA49,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
1100460,NPInter,ENST00000363883,nan,enables,GO:0003723,GO_REF:0000001,EXP,NPInter,F,RNA binding,nan,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
1100460,NPInter,ENST00000363883,nan,enables,GO:0034660,GO_REF:0000001,EXP,NPInter,P,ncRNA metabolic process,nan,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
1100515,NPInter,ENST00000637016,MIR548AU,enables,GO:0003723,GO_REF:0000001,EXP,NPInter,F,RNA binding,MIR548AU,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN
1100515,NPInter,ENST00000637016,MIR548AU,enables,GO:0034660,GO_REF:0000001,EXP,NPInter,P,ncRNA metabolic process,MIR548AU,ncRNA,taxon:9606,20220215,NPInter,NaN,NaN

In [ ]:
npinterv4_tarid_go_terms_transcript_df_v2 = npinterv4_tarid_go_terms_transcript_df_v2.join(ensembl_gene_ensembl_transcript.set_index("Gene stable ID"), on=[1])
npinterv4_tarid_go_terms_transcript_df_v2 = npinterv4_tarid_go_terms_transcript_df_v2[~npinterv4_tarid_go_terms_transcript_df_v2["Transcript stable ID"].isnull()]
npinterv4_tarid_go_terms_transcript_df_v2[1] = npinterv4_tarid_go_terms_transcript_df_v2["Transcript stable ID"]
del npinterv4_tarid_go_terms_transcript_df_v2["Transcript stable ID"]
npinterv4_tarid_go_terms_transcript_df_v2

In [160]:
from itertools import islice
with open('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human.gaf', "r") as myfile:
    head = list(islice(myfile, 41))
head

['!gaf-version: 2.2\n',
 '!\n',
 '!generated-by: GOC\n',
 '!\n',
 '!date-generated: 2022-01-14T16:45\n',
 '!\n',
 '!Header from source association file:\n',
 '!=================================\n',
 '!\n',
 '!generated-by: GOC\n',
 '!\n',
 '!date-generated: 2022-01-14T04:41\n',
 '!\n',
 '!Header from goa_human source association file:\n',
 '!=================================\n',
 '!\n',
 '!The set of protein accessions included in this file is based on UniProt reference proteomes, which provide one protein per gene.\n',
 '!They include the protein sequences annotated in Swiss-Prot or the longest TrEMBL transcript if there is no Swiss-Prot record.\n',
 '!If a particular protein accession is not annotated with GO, then it will not appear in this file.\n',
 '!\n',
 '!Note that the annotation set in this file is filtered in order to reduce redundancy; the full, unfiltered set can be found in\n',
 '!ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gz\n',
 '!\n',
 '!date-generated: 2021-11-08 15:48\n',
 '!generated-by: UniProt\n',
 '!go-version: http://purl.obolibrary.org/obo/go/releases/2021-11-06/extensions/go-plus.owl\n',
 '!\n',
 '!=================================\n',
 '!\n',
 '!Header copied from paint_goa_human_valid.gaf\n',
 '!=================================\n',
 '!Created on Sun Jan  2 19:01:56 2022.\n',
 '!generated-by: PANTHER\n',
 '!date-generated: 2022-01-02\n',
 '!PANTHER version: v.15.0.\n',
 '!GO version: 2021-11-16.\n',
 '!\n',
 '!=================================\n',
 '!\n',
 '!Documentation about this header can be found here: https://github.com/geneontology/go-site/blob/master/docs/gaf_validation.md\n',
 '!\n']

In [161]:
# always remember, use files in a with statement
with open('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_npinter_nc_ensembl_transcript_mapping.gaf', "w") as f2:
    for item in head:
        f2.write(item)

In [162]:
npinterv4_ncid_go_terms_transcript_df.to_csv('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_npinter_nc_ensembl_transcript_mapping.gaf', mode="a", sep="\t", header=False, index=False)

In [145]:
# always remember, use files in a with statement
with open('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_npinter_tar_v2_ensembl_transcript_mapping.gaf', "w") as f2:
    for item in head:
        f2.write(item)

In [146]:
npinterv4_tarid_go_terms_transcript_df_v2.to_csv('/dh-projects/uk_bb_intergenics/analysis/development/hollmann/data/agnostic/goa_human_npinter_tar_v2_ensembl_transcript_mapping.gaf', mode="a", sep="\t", header=False, index=False)